### ISSUE TITLE
GDCR22: Sessions - Big Picture?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#100]
@codecop @heidererkatrin @CareForCode @maosmurf @rolger 

Ich überlege das "Big Picture" von unserem Retreat in ein Bild zu fassen, weil ich glaube das es helfen kann unsere Geschichte zu transportieren und den jeweiligen Fokus zu veranschaulichen.

Hier ein primitiver Versuch:

![big picture](https://user-images.githubusercontent.com/16005912/199320352-5fb77346-3e82-4ec4-83b2-0b6b65f3b77e.png)

Was meint ihr?

Die Pfeile symbolisieren nicht 1:1 Sessions sondern, dass wir das Thema von verschiedenen Seiten angehen (wäre Teil der Erklärung).

In Sinn des Bildes:
1. Session: Fokus auf Requirements
2. Session: Fokus auf Code
3. Session: Fokus auf ...
4. Session: Fokus auf Feature Request als Motivation den Code via SOLID weiter zu entwickeln
5. Session: Fokus auf ...

**Comment by codecop** [comment]
Es ist eher eine Linie bzw Pipeline:
Requirements -> clean code - separate concerns - separate classen - separate domains bzw modules

**Comment by caichinger** [comment]
> Es ist eher eine Linie bzw Pipeline: Requirements -> clean code - separate concerns - separate classen - separate domains bzw modules

Interessant, d.h. du würdest lieber die Sessions/Progression darstellen?

Die Sessions/Progression selbst habe ich gar nicht dargestellt. Macht wohl Sinn, das auch zu tun!

**Comment by codecop** [comment]
Die Quadranten sind natürlich auch gut. Es sind 4 Sachen die wir brauchen
1. Clean Code
2. Separation of Concerns (IO/Storage getrennt, das geht schon in Richtung SRP) = Separate Concerns
3. Class Design nach SOLID = Decouple Collaborators
4. Separate Domains
Alles zusammen ergibt Hexagon. So könnte man es auch sagen.

**Comment by caichinger** [comment]
# Neuer Anlauf mit mehr Kontext

*Bitte auch Text lesen.*

![image](https://user-images.githubusercontent.com/16005912/199785037-8e933f56-1446-437b-a6bb-f813366260d7.png)

## Linke Seite: Ausgangslage

**Das Material und Szenario mit dem wir arbeiten**

* Requirements (links oben)
* Code Base (rechts oben)
* Feature Requests (links unten)
  [Die Feature Requests sind der dahinter liegende Grund, warum für uns überhaupt für Design interessieren.]
* Fiktive Code Base die alle neuen Features enthält (rechts unten)

**Die zu Grunde liegende Frage**

> Wie komme ich zur dieser fikitven Code base?

Naja...
* Das ist in der Praxis nicht so einfach.
* Kopplung ist ein Problem.
* Wie lösen wir das Problem?
* Decoupling!
* Aber wie machen wir das?
* Das ist das Thema unseres Retreats. :point_left: 

**Die Methode des Coderetreats:**

> Approach the same problem repeatedly from different angles

*Wir wissen natürlich, was unser Zugang ist, die Teilnehmenden wissen es an dieser Stelle noch nicht.*


## Rechte Seite: Entwicklung/Prozess + Strategien

Jede Session ist einem Thema gewidmet. Sagen wir einer **Strategy to decouple**.

Diese Pfeile weisen den Weg, einer nach dem anderen. Diesen Weg gehen wir, er führt uns Richtung **Decoupled Design**.

*Wir können auch tatsächlich die Pfeile nehmen und von links nach rechts wandern lassen, sodass sie dann rechts die Abfolge bilden, von der wir sprechen.*

> Alles zusammen ergibt Hexagon. So könnte man es auch sagen.

---

Disclaimer:
* Das ist eine Moderationshilfe mit dem Ziel, den Tag greifbarer zu machen
* Wir haben uns nicht so leicht getan den Tag zu gestalten, um so wichtiger ist mir die Kommunikation
* Moderationshilfe != Schematische Darstellung der Method(en)
* Ausgangslage, Ideen, Methoden, Lösungen sind unterschiedliche Dinge
* Ich würde das gerne besser darstellen können aber ich kann es auf die Schnelle nicht

**Comment by ReaSu** [comment]
a) ich find so eine Darstellung eine großartige Idee
b) ich find deinen Gedankengang schlüssig
c) zur Darstellung kann ich nicht viel sagen, denn ich wüsste überhaupt nicht wo anfangen, und daher ist das für mich die beste Darstellung, die ich mir vorstellen kann.
d) Issue #100! 🎉


------- Original Message -------

**Comment by codecop** [comment]
Was schön, gut gemacht

**Comment by caichinger** [comment]
@ReaSu das Ergebnis via referenzierten Commit dokumentiert.

**Comment by codecop** [comment]
@caichinger Du wolltest noch die Fotos teilen

**Comment by caichinger** [comment]
@codecop ist im obigen [Commit](https://github.com/swkWien/sessions/commit/c00f65592147221a255dd8252222cff05c30f283)
