### ISSUE TITLE
GDCR22: Final Info for Facilitators

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#101]
Hier noch einmal die wichtigsten Infos für morgen gesammelt:
- [Zeitplan](https://docs.google.com/spreadsheets/d/1LZTn6zvJuXAMqxj3W5W8Th6H8htvVfU4Z-XXorQW65w/edit?usp=sharing) (eure Verantwortung pro Session)
- [Facilitation Guide](https://github.com/swkWien/sessions/blob/master/2022/gdcr/facilitation_guide.md) (Code of conduct, Retros, ...)
- [Kata](https://github.com/swkWien/SupermarketReceipt-Refactoring-Kata) (inkl. Feature Requests)
- [Slides](https://swkwien.github.io/gdcr22/)

In order of appearance: @codecop @heidererkatrin @CareForCode @maosmurf @rolger

**Comment by maosmurf** [comment]
Assuming Zeitplan sheet stimmt: lt slides wäre lunch break um 12:30

**Comment by codecop** [comment]
12:00 wäre auch schön für Lunch, weil 12 ist Mittags ;-)

**Comment by caichinger** [comment]
> Assuming Zeitplan sheet stimmt: lt slides wäre lunch break um 12:30

War ein TODO, ist jetzt angepasst. Danke für's Mitschauen.

> 12:00 wäre auch schön für Lunch, weil 12 ist Mittags ;-)

Der Zeitplan ist das Ergebnis der Besprechung, die wir dazu hatten. Zu spät für Änderungen ;-) 
Es wird ohnedies etwas anders kommen...

(Es gibt Frühstück und daher den ganzen Vormittag Essen; macht Sinn, wenn die Mittagspause etwas später ist.)
