### ISSUE TITLE
Wer darf in's Orga Team?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#103]
@codecop oder @dertseha wann wird jemand in's Organizer Team aufgenommen?

Beim GDCR hat sich jemand gemeldet, der gerne aktiv werden würde und ich überlege daher die Person aufzunehmen.

**Comment by codecop** [comment]
Hier ist sowieso nichts privat. Würde sagen jeder. Einfach GitHub User zu Orga Gruppe adden

**Comment by caichinger** [comment]
Okay.
