### ISSUE TITLE
Willkommen bei swkWien/organiser

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#106]
Hallo @jdurstberger, @heidererkatrin und @CareForCode!

Willkommen im Organiser Team der swkWien GitHub Organisation!

*Wenn ihr wollt, sagt unten in den Kommentaren kurz hallo.*

**Wer sind wir?**

Wir sind ein lose organisierter Haufen an Menschen die sich für Softwareentwicklung und Events rund um dieses Thema interessieren.

**Welche Events gibt es und wer kümmert sich darum?**

Es gibt verschiedene Formate:
* Coding Dojos (meist zwei Sessions, typischerweise am Abend)
* Code Retreats (Ganz- oder Halbtag, typischerweise Freitag oder Samsag)
* Zero Overhead Coderetreat (Ganz- oder Halbtag, typischerweise Freitag oder Samsag)
  * Wie der Name schon sagt: "zero overhead", d.h. "bring your own topic", quasi ein Open Space

Ein Event findet statt, wenn es jemand organisiert.

Wenn ein Event stattfindet, dann kündigen wir es via https://softwerkskammer.org/ an.

Die Termine für Zero Overhead Coderetreat sind in hier: https://github.com/swkWien/sessions/issues/102.

**Wie kann ich mitmachen?**

Ganz wie du magst - wir freuen und immer über Initiativen!

**Was ist sonst noch gut zu wissen?**

Wenn nicht anders besprochen, läuft die Kommunikation über Issues.

Schau dir Folgendes an
* https://github.com/swkWien/sessions/issues
* https://github.com/swkWien/sessions/wiki
* https://github.com/swkWien/sessions/tree/master/templates

**Was ist am allerwichtigsten?**

> Wenn du was magst/brauchst/wissen willst, melde dich einfach!

---

FYI @swkWien/organiser (bitte ebenfalls gerne kommentieren)

**Comment by paulroho** [comment]
Hi  @JDurstberger, @heidererkatrin und @CareForCode, welcome to the show. The more, the merry!

Freue mich schon, wenn ich wieder einmal bei einem Event dabei sein kann.

CU, P

**Comment by heidererkatrin** [comment]
Hallo an alle,
vielen Dank für das Hinzufügen in diese Gruppe :) 
Freue mich schon auf weitere Events gemeinsam,
LG Katrin
