### ISSUE TITLE
Coding Dojos 2023

### ISSUE THREAD

**Issue by ReaSu** [swkWien/sessions#107]
The Coding Dojo is a two hour practice session. It is run during the week in the evening after work.
Dojos will take place every last Wednesday of the month.

> Our 2023 Coding Dojos will focus on OO design principles like SOLID.
> That means there will be (planned) 12 sessions practising different design aspects.

Month-> Who @ Where (when) [- what]

Jan -> Bernhard @ online - refactor the Bowling Game to Cyclomatic Complexity One (remove conditionals using OO)
Feb -> Rea @ online - explore the Single Responsibility Principle while refactoring the Fantasy Battle Kata
Mar -> Christopher (+Peter) @ Squer - SOLID violations and testability using Racing Car Katas 1+2
(Apr/May became) Jun -> Bernhard + Rea @ online - SOLID Tennis discussion
Summer Break
Oct -> Bernhard @
Nov 21. -> Rea @ gather - follow-up to GDCR: Tetris outside-in without mocks
Dec -> Christopher @

past events ... #4 #5 #9 #6 #47 #53, #73

**Comment by codecop** [comment]
@swkWien/organiser just letting you know a schedule for this year's Coding Dojos has been defined. In addition the facilitators defined a focus topic for 2023: **Our 2023 Coding Dojos will focus on OO design principles like SOLID. That means there will be 12* sessions practising different design aspects.** That is amazing! Of course there is still room for additional Coding Dojos if there are organisers planning to do...

**Comment by gregorriegler** [comment]
Very cool!!

**Comment by caichinger** [comment]
Very nice! I like that :)

**Comment by ReaSu** [comment]
Hi everyone,

Just in case you didn't get the invite (or forgot about it) - there's a dojo tomorrow evening - usual time & place: 6pm @gather.town.
We'll be exploring the Single Responsibility Principle (as a part of this ongoing series about OO design principles).

**Comment by gregorriegler** [comment]
I recedived the invite, and I added it to my calendar and look forward to join.

**Comment by ReaSu** [comment]
Thanks Bernhard and Gregor for an interesting discussion! Some highlights:

- While we did consider the SRP when planning what to do, we ended up just cleaning up the code (get rid of Feature Envy, Message Chains) and got the same result.
- What's the difference between SRP and Separation of Concerns? We couldn't find one. While there's only cross-cutting concerns and no cross-cutting responsibilities, we believe it's just a matter of the lexicon, not the semantics.
- There's more ways than one to break a problem into responsibilities. Conway's law comes to mind.

Anything important I forgot?

**Comment by codecop** [comment]
Das nächste Coding Dojo ist in Person und wird von Squer gehostet: https://www.meetup.com/squer-brainfood-talks/events/292356953/

**Comment by ReaSu** [comment]
Well, we haven't been doing too well with sticking to our schedule, have we. :joy: 

How do we get back on track? Shall we just resume with Christopher's September event?

@BernhardGruber and @redseacomputing, what do you need to actually stick to the schedule?

For myself, I think there are two main problems:
a) I forget about it, despite the date being in my calendar. So I need to set myself better timed reminders - early enough to have a think and send out invites, but not too early.
b) I don't have a clear idea of what I want to do, and want to achieve with these dojos.

I think it would also help to have more attendees. While it's nice to talk to one or two people, I find it also a bit disheartening to put time and effort into organising something and then have only one person show up. One way to achieve this would certainly be to send out the invites a bit earlier, another is to use more channels outside the swk website. I haven't been very good at this. :grimacing:

**Comment by ReaSu** [comment]
I agtree, a summer break is worth considering for next year.

**Comment by codecop** [comment]
@ReaSu @redseacomputing @BernhardGruber do you plan do run another Coding Dojo this year? There would be 3 left? Or we drop the idea in favour of preparing for GDCR?

**Comment by codecop** [comment]
Rea will run a dojo at 21st Nov as followup to the Coderetreat

**Comment by caichinger** [comment]
@ReaSu wie ist dein Dojo gelaufen? Erstes Dojo nach GDCR und mit Meetup? :)

**Comment by ReaSu** [comment]
Ich war ein bisschen nervös mit so vielen Anmeldungen von Leuten, die ich noch nie gesehen habe, aber schließlich sind nur 3 Leute aufgetaucht - zwei kannte ich schon, den dritten habe ich zumindest schon auf Slack gelesen. Einerseits schade, andererseits gut für meine Nerven. : )

Wir hatten eine sehr angeregte Diskussion darüber, wie weit außen wir beginnen wollen/können, was wir eigentlich testen, und was/wie wir vereinfachen. Ich wollte die Notizen dazu auch hier irgendwo verlinken, danke für die Erinnerung!

**Comment by caichinger** [comment]
> Ich war ein bisschen nervös mit so vielen Anmeldungen von Leuten, die ich noch nie gesehen habe, aber schließlich sind nur 3 Leute aufgetaucht - zwei kannte ich schon, den dritten habe ich zumindest schon auf Slack gelesen. Einerseits schade, andererseits gut für meine Nerven. : )

Das klingt nach Nervenkitzel und Entlastung in einem. :)

> Wir hatten eine sehr angeregte Diskussion darüber, wie weit außen wir beginnen wollen/können, was wir eigentlich testen, und was/wie wir vereinfachen. Ich wollte die Notizen dazu auch hier irgendwo verlinken, danke für die Erinnerung!

*Angeregte Diskussion* hört sich gut an! Schön, dass ihr offenbar eine produktive Session hattet! :)

Danke für's Teilen und danke für's Abhalten!

Denke bei drei Personen stellt sich die Frage kaum aber weißt du:
* Waren sie beim GDCR und sind jetzt wieder gekommen?
* Sind sie via Meetup zu uns gestoßen?

**Comment by ReaSu** [comment]
So, jetzt hab ichs geschafft: Die Notizen zur Diskussion sind [hier](https://github.com/swkWien/kata-bootstraps-gdcr20/tree/2023-11-21-tetris-outside-in/kotlin/junit) zu finden.

Zu den Teilnehmern: 

- Stefan ist aus der Gegend von Köln, war also nicht beim GDCR, er war aber schon früher hin und wieder bei unseren Dojos dabei. Er hat sich über die SWK angemeldet.
- Bernie (hallo, Bernie!) war beim GDCR, kennt uns natürlich.
- Jakob war am GDCR verhindert, kannte uns aber auch schon. Er und Bernie waren über Meetup angemeldet.

**Comment by ReaSu** [comment]
> Das klingt nach Nervenkitzel und Entlastung in einem. :)

Kann man so sagen, ja. : )

> Angeregte Diskussion hört sich gut an! Schön, dass ihr offenbar eine produktive Session hattet! :)

Ja, das war auch unser Fazit am Ende. Das bisschen coden war nett, aber die Diskussion war der interessante und produktive Teil.

**Comment by caichinger** [comment]
@ReaSu danke für die Infos :)

(Ad "Ja, das war auch unser Fazit am Ende. Das bisschen coden war nett, aber die Diskussion war der interessante und produktive Teil.": mir scheint Outside In und das Kata machen echt Platz für interessanten Austausch.)
