### ISSUE TITLE
GDCR Guide

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#109]
Issue für Austausch

**Comment by ReaSu** [comment]
Cool, danke - bei mir wirds auch noch dauern.

**Comment by ReaSu** [comment]
Hier die Notizen, die ich mit heim genommen hab. Ich hoff, ich hab nichts verdreht!
@caichinger, hast du deine noch?

# Wozu brauchen wir Sponsoring/Budget, wie können uns Firmen unterstützen?

- Venue
    - Anforderungen? s. unten
- Catering
    - Anforderungen?
        - vegan
        - vegetarisch
        - sonstiges?
- Einladen von Facilitators, Gästen
- Material
    - Blöcke
    - Stifte
    - Swag

# Interne Kommunikation 

## Was sollten wir kommunizieren?

- Vision - warum veranstalten wir den GDCR, und was erwarten wir uns davon?
    - Was ist unser Ziel?
        - Community Building
        - Spaß
    - Wer soll unsere Zielgruppe sein?
        - Code of Conduct darauf abgestimmt
    - Bigger Picture (was hatten wir damit gemeint?)
- Wer ist eigentlich im Team?
    - Onboarding von Neuen im Team
- Rollen
    - vor dem Event
        - Organisation des Events
        - Programm erarbeiten (in kleiner Gruppe)
        - Ansprechperson für Onboarding
    - beim Event
        - Host
        - Moderator
        - Facilitator
        - Assistant Facilitator
- Retro
    - nach dem Event, fürs Team
- Follow-up
    - Enthusiasmus der TN nutzen
    - Kontinuität gewährleisten
- Mailings
    - Mustertexte / Templates
- Zeitplan
    - Outreach (s. Zielgruppe!)
    - Programm-Prozess
        1. Allgemeine Diskussion, Ideen sammeln
        1. in kleiner Gruppe bestimmen
            - Details ausarbeiten
            - Constraints festlegen
        1. Finale Fassung
    - Event-Plan
    - Deadlines festlegen für
        - Catering
        - Venue
        - etc.

## Kommunikation und Organisation

- Wie (über welche Kanäle) kommunizieren wir?
    - Github Issues
    - andere?

- Kommunikation zum/beim Event
    - Venue
    - Covid Policy
    - Zugänglichkeit 
        - ist das Gebäude offen?
        - wer hat Schlüssel?
        - wie kommen Gäste rein?
    - Barrierefreiheit
    - Empfang
        - ist Registrierung notwendig?
        - wie identifizieren wir TN?
        - Name Badges sind hilfreich
    - Navigation im Gebäude
        - Beschilderung
        - Wo sind WCs, Notausgänge
    - Raumplanung
        - Sessions
        - Retros
        - Pausen
    - Infrastruktur
        - WLAN
        - Steckdosen/Stromversorgung
        - Infrastruktur f. Präsentation
            - Beamer
            - Flipchart
            - ...
    - Catering

**Comment by caichinger** [comment]
Cool!

Ja, habe meine noch und spüre gerade voll den Motivationsschub :D

**Comment by caichinger** [comment]
Bin in der Zwischenzeit übersiedelt und finde die Unterlagen gerade nicht. Hast du @ReaSu  damals zufällig ein Foto gemacht?

**Comment by caichinger** [comment]
> Ich hab damals ein Foto gemacht, von einem Blatt, aber das war so verzittert, dass ich es gleich wieder gelöscht habe.

Vielleicht ein Learning für mich. Immer Foto machen und sofort hochladen. :)

Ich habe die Blätter sicher noch...
