### ISSUE TITLE
GDCR 2023 Organisation

### ISSUE THREAD

**Issue by ReaSu** [swkWien/sessions#111]
Here is a thread for the organisation of GDCR 2023.

### Who is willing to help organising? (Please add your name)
- Rea
- Claus
- ...

### Who is willing to (co-) facilitate? (Please add your name)
- Rea
- Claus
- Adam
- Gregor
- ?

### Brainstorming ideas for topics of the day:
- Refactoring
- AI-aided coding
- Design Patterns
- Write various versions of bad code (cf. paradoxical intervention)
- Claus (not really topics, more ideas; not censoring myself)
  - For me a topic can be more than "let's focus on design xyz", it can also be more abstract in nature and e.g. focus on other properties/goals of the day
  - Classic CR (Game of Life); we haven't done that in a while
  - Whatever overarching topic because it allows us to tell a story
  - Some kind of collaborative game like https://www.leanpoker.org/
  - Development (not design!) patterns: How do we behave? What are the small (!) changes in our behavior and our coding that we can foster to become better developers (and vice versa, what are the behaviors that keep us from improving?). I am currently reading a book, *Atomic Habits*, and the author therein strongly emphasizes "incremental marginal gains". It would interesting to work on these ideas.
  - A Kata where we face an inner conflict, where our thinking about the domain might distract us from thinking about the implementation. I would say this is the case when you have to to come up with an algorithm or problem solving strategy on your own. While thinking about the strategy, you may loose sight of the implementation. There some resemblance with lean poker.
  - [CUPID instead of SOLID](https://github.com/Softwerkskammer-Linz/SoCraTes2023/tree/main/solid-cupid-grasp)
  - Contrasting different TDD [styles](https://www.tddstpau.li/) (see "Comparison to other schools of TDD") and/or testing styles (approval tests, property based tests, ghostwritten/generated tests, ...)
  - Bad code: [refucktoring](https://github.com/katieamazing/refucktoring)
  - Just sharing because it is cool: https://symflower.com/
  - [Tetris, Wolfram suggested it to me as a topic at SoCraTes](https://picostitch.com/blog/2017/11/25-jscoderetreat-12/)
  - Additional topics:
    - Why do we organize a CR?
    - Who assumes which role?
- ...

### Brainstorming ideas for objectives of the day:
Claus:
- Announce a follow up event at the CR to keep the energy we create at this event and carry it further
- A dedicated push to try to invite participants from underrepresented groups

---

Some years ago I tried to compile some sort of checklist of things that need to be done. It's not complete yet, but it's a start. Feel free to add to it!

# Checklist: ToDo for GDCR

## t-2 months

- Decide on date: **04.11.2023 (?)**
- Find sponsor(s):
  - **Nagarro (?)**
- Find Facilitator(s)

## t-1 month

- Create event on Eventbrite
- Programme
    - what problem? (GoL? Snake?)
    - what constraints?
- Other organisational stuff:
    - who is on Check-in?
    - Any materials needed?
- Invitations, Announcements (have sample invitation text)
    - SWK-Event
    - SWK-Mail
    - SWK-Twitter
    - Coderetreat.org
    - UGs
    - Clients
    - FHs

## t-1 week

- Repeat invitations (Twitter, whereever)
- Catering for lunch
- Restaurant/bar for after-party (vegan options?)
- orientation around venue (doors open? contact? signs?)
- Create slides

## t-1 day

- Test everything

**Comment by ReaSu** [comment]
Which date do you prefer?

- For Friday, 3.11., react with :three: 
- For Saturday, 4.11., react with :four:

**Comment by ReaSu** [comment]
Who can sponsor the event?

- EBCONT @gregorriegler
- SQUER @paulroho
- Nagarro @rolger
- Frequentis @dertseha
- ???
- ???

**Comment by rolger** [comment]
Nagarro would sponsor the event again. Same location in Europlaca, same food from Dewan. I would host it again

**Comment by rolger** [comment]
> 

I'll prefer 4.11

**Comment by caichinger** [comment]
Unless someone extremely motivated shows up I am very happy to go with Nagarro again. Thank you @rolger.

**Comment by caichinger** [comment]
Website is up: https://swkwien.github.io/gdcr23/  :rocket: (and we now have a link to share to invite people)

Source: https://github.com/swkWien/gdcr23/

At the moment it lists Nagarro as host and the 4.11. as date, that's not meant to forestall the decision.

**Comment by codecop** [comment]
Nice thank you. fyi Page title is "index"

**Comment by codecop** [comment]
Friday could be a Small Coderetreat online to warm up for the Saturday one. Would just need some Zoom account if we are > 10 participants. Or limit at 10 would also be good. I could run that small online one.... Just ideas

**Comment by ReaSu** [comment]
I like your ideas, @codecop!

**Comment by ReaSu** [comment]
Thanks for the website, @caichinger!

Since it mentions a topic on the second slide, I think we should start thinking about what we actually want to do! Do we even want to have an overarching topic again this year? 

There's a new section for suggestions in the first post, please add anything that comes to mind, no censoring yourself (or others) at this stage! Even the silliest ideas are welcome, no matter if they are actually doable or not.

**Comment by ReaSu** [comment]
@rolger, thanks for organising sponsoring, and for hosting! :orange_heart:

**Comment by dertseha** [comment]
Thank you for the ping!
Sadly, FRQ is hardly sponsoring things.

Saturday, 4th of November is great for me.
I'll let the thought sink in to consider facilitating a session.

**Comment by gregorriegler** [comment]
I'm happy to co-facilitate and I'm happy to just participate 😄

**Comment by caichinger** [comment]
> Since it mentions a topic on the second slide, I think we should start thinking about what we actually want to do! Do we even want to have an overarching topic again this year?
> 
> There's a new section for suggestions in the first post, please add anything that comes to mind, no censoring yourself (or others) at this stage! Even the silliest ideas are welcome, no matter if they are actually doable or not.

In addition to the topic-question, I want to suggest that we also ask ourselves if there we have any other ideas/goals that we would like to pursue this year. I added an additional brainstorming section to document these.

What could be an additional idea?
- Announce a follow up event at the CR to keep the energy we create at this event and carry it further
- A dedicated push to try to invite participants from underrepresented groups
- ...

**Comment by gregorriegler** [comment]
What is a goal that you would like us to pursue this year, @caichinger ?

**Comment by ReaSu** [comment]
I think both goals suggested by @caichinger are worth pursuing: using the momentum and enthusiasm of the GDCR to get more people to join us more regularly, and making an effort to increase the number of participants from underrepresented groups. 
Are they mutually exclusive? I don't think so, what are your thoughts?

**Comment by ReaSu** [comment]
Thanks for more ideas on topics for the day, @caichinger. I agree that an overarching topic helps to tell a story, and that's what I was aiming at with the question.
I like the idea of development patterns - especially because I spontaneously have no idea what they could be. Things like using keyboard shortcuts instead of using the mouse? Or thinking patterns? :thinking: 

The choice of Kata can be influenced by the topic of the day (as it was last year), or not. I agree that we haven't done GoL in a long time.

**Comment by caichinger** [comment]
> What is a goal that you would like us to pursue this year, @caichinger ?

The two goals that came to my mind initially are "follow up event" and "try for more diversity".

For me one question is why we do organize the GDCR CR? We could just attend such an event elsewhere.
I think one reason is local community (building) and if we do that, it would make sense to try to go a step further like we already tried with the regular dojos. The GDCR is in my opinion a good opportunity to gather people.

> Are they mutually exclusive? I don't think so, what are your thoughts?

No, they are not exclusive.

I think "follow up" event would be easy to do and is basically *organized* once a person volunteers and sets a date.
"More diversity" needs more dedication on our side.

---

I suggest we wait another few days to collect more ideas and then we have a call/meeting to discuss topics (and eventually additional goals).

**Comment by rolger** [comment]
I created a page on EventBrite to register. Next I'll register us on the GDCR homepage.

https://www.eventbrite.com/e/global-day-of-coderetreat-vienna-2023-tickets-719761033627?aff=oddtdtcreator

Still missing are some questions for registering. I'm going to add it soon

**Comment by codecop** [comment]
I created a second issue #112 for 3rd of November

**Comment by caichinger** [comment]
> I created a second issue #112 for 3rd of November

@codecop are there any implications of you doing this pre-event with regards to GDCR that we should know of? Such as having less resources, ...

**Comment by caichinger** [comment]
> I created a page on EventBrite to register. Next I'll register us on the GDCR homepage.
> 
> https://www.eventbrite.com/e/global-day-of-coderetreat-vienna-2023-tickets-719761033627?aff=oddtdtcreator
> 
> Still missing are some questions for registering. I'm going to add it soon

Thank you.

---

**Registration for organizers**
In line we our approach last year, I suggest that also organizers purchase tickets to help Roland keep an overview of the number of expected participants (for catering and reservations).


**Recall that we have text templates**
We have a collection of resources that are readily available if you want to start making announcements in your community. If you make changes, please consider updating our collection as well.

https://github.com/swkWien/sessions/tree/master/2023/cr20231104_gdrc

(Check for errors/missing details before copy-pasting;)

**Comment by rolger** [comment]
> Friday could be a Small Coderetreat online to warm up for the Saturday one. Would just need some Zoom account if we are > 10 participants. Or limit at 10 would also be good. I could run that small online one.... Just ideas... Maybe together with some other locations, thinking of Berlin/Wroclaw... Ah now more and more ideas ...

I reserved our Nagarro zoom session for Friday 3.11.2023

**Comment by rolger** [comment]
> > I created a page on EventBrite to register. Next I'll register us on the GDCR homepage.
> > https://www.eventbrite.com/e/global-day-of-coderetreat-vienna-2023-tickets-719761033627?aff=oddtdtcreator
> > Still missing are some questions for registering. I'm going to add it soon
> 
> Thank you (also for setting up the new resources folder).
> 
> **Registration for organizers** In line we our approach last year, I suggest that also organizers purchase tickets to help Roland keep an overview of the number of expected participants (for catering and reservations).
> 
> **Recall that we have text templates** We have a collection of resources that are readily available if you want to start making announcements in your community. If you make changes, please consider updating our collection as well.
> 
> https://github.com/swkWien/sessions/tree/master/2023/cr20231104_gdrc
> 
> (Check for errors/missing details before copy-pasting;)

Added the same questions as last year and documented [here in our sessions] (https://github.com/swkWien/sessions/tree/master/2023/cr20231104_gdrc)


-     Have you participated in a coding dojo or code retreat before?
-     Which programming languages are you familiar with?
-     How did you find out about us?
-     Do you join for breakfast?
-     Do you join for dinner?

**Comment by ReaSu** [comment]
I have updated some language in the Readme (sorry @rolger for interfering with your changes!)

Now that we start advertising (and I think it's a great idea to start, thanks!) we should also come up with a topic so we can include it in the invites. Claus has already brought up some great ideas, please feel free to add yours in the first post of this issue (https://github.com/swkWien/sessions/issues/111#issue-1879254321)! An overarching topic allows us to tell a story through the sessions of the day.

I propose we schedule a call towards the end of this or early next week to decide. Who wants to join?

**Comment by caichinger** [comment]
> I propose we schedule a call towards the end of this or early next week to decide. Who wants to join?

I am in.

[SoCraTes](https://socrates-conference.at/) takes place Friday and Saturday, so maybe not end of the week.

What about Monday or Tuesday evening?

**Please respond: I am want to join and ...**
* :+1:  I am available on Monday
* :smile: I am available on Tuesday
* :tada: I am available Monday and Tuesday
* :-1: neither of the proposed dates work (and therefore I suggest the following alternative;)

**Comment by caichinger** [comment]
For planning purposes, I suggest we meet **Montag, 25.11.2023, 19:00** in Gather (and I am open for alternatives).

In this call we **brainstorm about the topic**.
Hence everyone who wants to share their ideas is welcome and invited to join! :)
(We do not intend finalize the program nor is it implied that you have to work out the details or facilitate a session)

*Pinging* @gregorriegler @rolger @dertseha @goerge @paulroho @BernhardGruber @redseacomputing @maosmurf @heidererkatrin

**Comment by maosmurf** [comment]
👋 Hello GDCR team!
I managed to change the vacation schedule and actually can attend GDCR and I'm happy to assist where necessary.
(I will not be able to spend much time on Friday 3rd #112 though)
See you on Monday 7PM - or maybe on [Socrates](https://socrates-conference.at/)? 🚀

**Comment by caichinger** [comment]
I just created this very plain poster/invitation and [share it here](https://docs.google.com/document/d/15RtOAmlTa_LJRQ9lmYWBzMzWu2KV5J9zS-Jwjz_6qXA/edit?usp=sharing) with you in case you want to use it as well.

I will prepare printouts for SoCraTes.

@maosmurf looking forward to seeing you there and happy to hear you can join/assisst in this year's CR :)

**Comment by caichinger** [comment]
Result of discussion:
* Title/focus/topic: Different **TDD styles**
* Kata: **Tetris** (from the ground up)

Follow up work on the program in #113.

Yesterday's meeting notes are [here](https://github.com/swkWien/sessions/blob/master/2023/cr20231104_gdrc/meeting_20230925_discuss_topic.md).

It was cool to see how we managed to extract a session plan out of a heap of vague ideas. Thank you @ReaSu @codecop @maosmurf for that experience.

**Comment by caichinger** [comment]
Call for facilitators:

We are still short of facilitators. If you want to contribute or know someone who wants to contribute, please raise your hand in #113

**Comment by rolger** [comment]
I asked Andi Kleinbichler for facilitating a session. He attended last year and stated his interest in supporting the team. He agreed but his constraint is that he has to leave at 3 pm this year. Shall I invite him to our github team?

**Comment by caichinger** [comment]
> I asked Andi Kleinbichler for facilitating a session. He attended last year and stated his interest in supporting the team. He agreed but his constraint is that he has to leave at 3 pm this year. Shall I invite him to our github team?

Sure! Thank you. He can join our discussion and then we decide what is feasible and what is not.

**Comment by caichinger** [comment]
I just did a pen & paper session on Tetris and I think it is interesting. I also think it is kind of hard (for a CR) and I want to do a few sessions to understand it better.
If you feel like experimenting with it, let me know.

**Comment by codecop** [comment]
Just reminding you:
* SWK Event page could be created
* Copy on Meetup could be created
* Submit JSON to global site
* Tweet and other forms of advertisement...

**Comment by caichinger** [comment]
**Clarify level of involvement**

* What do you feel responsible for?
* To which extend to you plan to be involved?
* What do you want/plan to do?

I understand that we are loosely organized. For me this is also a bit difficult.

If you want to share, please do so. It would help me define my role in this project. Thank you.

**Comment by maosmurf** [comment]
* Roadmap
  * ❓who faciliates 1 more session before GDCR
  * @caichinger Moderation / Intro / Outro - 1 common laptop for presentations
  * ❓5 Sessions -> 5x2 Facilitators (Lead + Support)
* Announcments
  * @ReaSu - create event @ [softwerkskammer](https://www.softwerkskammer.org/) and send email
  * @gregorriegler upload GDCR infos
  * ✅ [eventbrite event](https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2023-tickets-719761033627)
    * @caichinger - check eventbrite for correct theme, then tell christopher to update meetup if needed
    * ❗️check eventbrite text if matches 
    *❗️all facilitators are also asked to register via eventbrite
  * ✅ [meetup event](https://www.meetup.com/software-craftsmanship-vienna/events/296536991/)
  * ❓more invitations
    * @caichinger and @ReaSu - focus on diversity
  * reminder email via eventbrite - incl. setup instructions + link to SWK 

* Hosting - does @rolger need support for checkin/kitchen
  * instructions at street level  + phone#
* @ReaSu - will provide follow-up DoJo on Due Nov 21st
 
[Sessions](https://github.com/swkWien/sessions/issues/113)
1. @caichinger pen & paper
2. ❓Focus: Pair programming & Ping Pong; Test first; Test least ("Inside out")
  * Demo video?
3. @gregorriegler  "Outside in" without mocks
4. @maosmurf Outside in with predefined interface to be mo
5. ❓1x ensemble session @ main room and/or Constraint/free Constraint

@dertseha @paulroho @goerge @rolger  - would one of you be available and motiviated to host one session, either #3 (TDD Outside in) or #5 (last session - choose your own constraint!)

**Comment by gregorriegler** [comment]
we are now on https://www.coderetreat.org/events/

**Comment by ReaSu** [comment]
@redseacomputing  has already created the event at https://www.softwerkskammer.org/activities/04112023
I don't have the rights to edit/send emails.

**Comment by rolger** [comment]
> we are now on https://www.coderetreat.org/events/ thank you @caichinger for taking the lead to push and initiate a collaborative planning and discussion about what needs to be done and by whom. I feel this was necessary and helpful

Friday is online, but I didn't find the event for Saturday. I forked the repository https://github.com/rolger/coderetreat.org and found both entires. @gregorriegler did you receive any issues on your PR?

**Comment by rolger** [comment]
> > we are now on https://www.coderetreat.org/events/ thank you @caichinger for taking the lead to push and initiate a collaborative planning and discussion about what needs to be done and by whom. I feel this was necessary and helpful
> 
> Friday is online, but I didn't find the event for Saturday. I forked the repository https://github.com/rolger/coderetreat.org and found both entires. @gregorriegler did you receive any issues on your PR?

Sorry @gregorriegler it's here. Just needed to refresh the page and scroll down to 4.11.2023 :-)

**Comment by rolger** [comment]
> * Roadmap
>       
>       * ❓who faciliates 1 more session before GDCR
>       * @caichinger Moderation / Intro / Outro - 1 common laptop for presentations
>       * ❓5 Sessions -> 5x2 Facilitators (Lead + Support)
> 
>     * Announcments
>       
>       * @ReaSu - create event @ [softwerkskammer](https://www.softwerkskammer.org/) and send email
>         
>         * Event was already created by @redseacomputing. I (Rea) don't have the rights to edit/send emails.
>       * ✅ @gregorriegler upload GDCR infos to https://www.coderetreat.org/events/
>       * ✅ [eventbrite event](https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2023-tickets-719761033627)
>         
>         * @caichinger - check eventbrite for correct theme, then tell christopher to update meetup if needed
>         * ❗️check eventbrite text if matches
>         * ❗️all facilitators are also asked to register via eventbrite
>       * ✅ [meetup event](https://www.meetup.com/software-craftsmanship-vienna/events/296536991/)
>       * ❓more invitations
>         
>         * @caichinger and @ReaSu - focus on diversity
>       * reminder email via eventbrite - incl. setup instructions + link to SWK
> 
>     * Hosting - does @rolger need support for checkin/kitchen
>       
>       * instructions at street level  + phone#
> 
>     * @ReaSu - will provide follow-up DoJo on Due Nov 21st
> 
> 
> [Sessions](https://github.com/swkWien/sessions/issues/113)
> 
>     1. @caichinger pen & paper
> 
>     2. @ReaSu Focus: Pair programming & Ping Pong; Test first; Test least ("Inside out")
> 
> 
>     * Demo video?
> 
> 
>     3. @gregorriegler  "Outside in" without mocks
> 
>     4. @maosmurf Outside in with predefined interface to be mo
> 
>     5. ❓1x ensemble session @ main room and/or Constraint/free Constraint
> 
> 
> @dertseha @paulroho @goerge @rolger - would one of you be available and motiviated to host one session, either #3 (TDD Outside in) or #5 (last session - choose your own constraint!)

What do we expect from the 5th session? Is there still the option between 1x ensemble session @ main room and/or Constraint/free Constraint?

ad ensemble session:
I would suggest different room outside the main room, where we have seats to sit around a table. There is a room nearby, I'd suggest to use this. It's also easier to restrict the number of participants in this session. 

ad constraints:
I'd provide a prepared list of constraints to choose max. of 4-5 constraints? Otherwise people tend to discuss and need to much time to decide. the moderator should explain the constraints briefly and they should align with our topic

**Comment by paulroho** [comment]
I totally would love to host that TDD Outside in session, but unfortunately, I am not sure if I can make it to the GDCR at all. Sorry - you're all amazing!

**Comment by maosmurf** [comment]
Hi @rolger , thank you for the feedback! 

> What do we expect from the 5th session? Is there still the option between 1x ensemble session @ main room and/or Constraint/free Constraint?

Yes!

> ad ensemble session:
I would suggest different room outside the main room, where we have seats to sit around a table. There is a room nearby, I'd suggest to use this. It's also easier to restrict the number of participants in this session.

Valid points. I'd leave it also to @gregorriegler if he wants to facilitate a dedicated ensemble session (on top of session 3)


> ad constraints:
I'd provide a prepared list of constraints to choose max. of 4-5 constraints? Otherwise people tend to discuss and need to much time to decide. the moderator should explain the constraints briefly and they should align with our topic

That sounds perfectly fair for me! I agree, that less constrains (but then with a brief explanation about why constraint X might be valuable) is preferred. May we count you in? 🤞

**Comment by dertseha** [comment]
Thank you for the ask regarding hosting. I'm happy to be a co-host, to assist for any main person, if necessary.
I'm too far removed this year from any primary tasks.

**Comment by caichinger** [comment]
Unfortunately, I **withdraw from the organization of the GDCR**. I can still take over a single session and would also take part in a "final program coordination appointment" to help with alignment but otherwise I take myself out for this year.

(I will try to respond if you ask/require something specific from me.)

I am sorry about that, at the same time I need my resources elsewhere at the moment.

**Comment by ReaSu** [comment]
> I see. Can you try it again (as an editor), @ReaSu ?

Sorry for disappearing. As you noticed ( I hope! 😄 ) I managed to send the invite now.
I sent it to the Vienna, Linz, and Salzburg groups, and plan to send a reminder a week or so before the event.

**Comment by ReaSu** [comment]
I'm sorry to hear it, @caichinger, and thank you for communicating this. Lets see how we manage without you! 😁

**Comment by ReaSu** [comment]
@dertseha thanks for the offer, that's really helpful. Is there a particular session in which you *don't* want to co-facilitate?

**Comment by dertseha** [comment]
> @dertseha thanks for the offer, that's really helpful. Is there a particular session in which you _don't_ want to co-facilitate?

I should be fine with any listed. Whoever is the main person in said session will probably set the tone anyway, so I can adjust with my side-comments.

Also, all the best to you, Claus - and thank you for all you did and are doing.

**Comment by ReaSu** [comment]
@rolger thanks for your thoughts, I agree with your suggestions! 
Is there a monitor/projector in the room you mentioned for the ensemble?

**Comment by ReaSu** [comment]
@dertseha I'm sure you can adjust to every session. My thinking was that there may be (a) session(s) you'd rather participate in! 😄

**Comment by gregorriegler** [comment]
I'm at DevFest Vienna right now, and learned about https://www.thenewitgirls.com/ where we could announce our event to maybe achieve more diversity

**Comment by caichinger** [comment]
Thank you for your understanding and kind words! :)

**Comment by rolger** [comment]
FYI - we have got 15 registrations until now.

**Comment by rolger** [comment]
> @rolger thanks for your thoughts, I agree with your suggestions! Is there a monitor/projector in the room you mentioned for the ensemble?

Yes there are monitors in each of our meeting rooms available

**Comment by maosmurf** [comment]
danke @ReaSu ! 
Für mich wäre morgen (ab 18:30 bzw ab 17 if-need-be) ideal, weil ich am Donnerstag bis 2.11 nicht in Wien bin

**Comment by ReaSu** [comment]
Ah ja - Link zum Poll: https://nuudel.digitalcourage.de/zD7GRgNTIYWlil9w

Ihr könnt gern auch andere Vorschläge machen!

**Comment by ReaSu** [comment]
Ah, jetzt hab ich @maosmurf übersehen. Da wär natürlich morgen super, aber ich kann frühestens ab 19:30.

**Comment by ReaSu** [comment]
@gregorriegler wann wär denn passend für dich? Ich schätze, wir werden auf Adam verzichten müssen.
https://nuudel.digitalcourage.de/zD7GRgNTIYWlil9w

**Comment by maosmurf** [comment]
@ReaSu whst's the decision? I'll try to accomodate

**Comment by ReaSu** [comment]
Waiting for @gregorriegler  - I hope we can find a time tomorrow, 26th.

**Comment by rolger** [comment]
Ich habe mich auch eingetragen und würde gerne heute Abend dabei sein

**Comment by ReaSu** [comment]
Dann lasst uns heute Nachmittag/Abend 17:30 anpeilen, OK? 
@rolger @caichinger @maosmurf @gregorriegler

**Comment by caichinger** [comment]
> Dann lasst uns heute Nachmittag/Abend 17:30 anpeilen, OK? @rolger @caichinger @maosmurf @gregorriegler

Passt für mich. Wenn niemand was anderes sagt, treffen wir uns via Gather https://app.gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo

**Comment by caichinger** [comment]
### Update vom Call

Teilgenommen: Rea, Roland, Claus

Notizen & Ergebnisse (bitte gerne ergänzen):
- Seitens @rolger
  - Macht Moderation zu Beginn
  - Übernimmt die letzte Session
  - Hat alles im Griff und braucht keine Unterstützung
  - Bemüht sich um bessere/n Orientierung/Empfang vor Ort
  - Wir stehen bei 20 Anmeldungen
- Seitens @ReaSu 
  - Wird mit Claus eine Pair Programming & TDD Demo am Beginn der Session machen
  - Wird einen finalen Abstimmungstermin ankündigen
- Seitens @caichinger
  - Übernimmt Closing Retro und Outro

-  Programm
  - Wir sehen offene Fragen in [Session 4: Outside-In mit Mocks](#120 )
  - [Zeitplan](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)

Bitte in diesem Issue **keine Beiträge mehr zu den Sessions oder zum Programm**. Dazu gibt es jetzt eigene Issues.

**Comment by ReaSu** [comment]
Danke für die ganze Arbeit, Claus!

**Comment by ReaSu** [comment]
Vorschlag für eine letzte Abstimmungsrunde vor dem Event:

**Freitag, 3.11., 16:30 Uhr** - also in Anschluss (mit Pause) an den Warm-up-Event. Wie gehabt in Gather: https://app.gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo

Wenn dieser Termin nicht passt, bitte melden!
Das geht v.a. an die Facilitators, aber auch Co-Facilitators und andere sind natürlich herzlich willkommen.

**Comment by rolger** [comment]
Aktuell haben sich 26 Teilnehmer via Eventbrite registriert und ich glaube es gibt zusätzliche Anmeldungen vie Meetup

**Comment by caichinger** [comment]
> [...] und ich glaube es gibt zusätzliche Anmeldungen vie Meetup

@redseacomputing bitte schicke auf Meetup zur Sicherheit eine Nachricht an die Angemeldeten (oder in den Kommentaren des Events), dass sie sich auch auf Eventbrite registrieren müssen. Manchmal hilft es, Dinge öfter zu sagen.
Danke!

**Comment by codecop** [comment]
@caichinger @ReaSu @maosmurf @gregorriegler @rolger gratuliere noch einmal zum sehr gelungenen Gdcr. Das überspannende Topic habt ihr sehr gut gemacht. Session Zusammenstellung war ideal. Zeitplan usw. alles funktioniert, Organisation etc. Top Event.

**Comment by gregorriegler** [comment]
Ich würde gerne eine Retro mit euch machen. Habe viele Inputs. Ich bin recht flexibel im November.
Wenn ihr kurz beschreiben würdet ob und wann es bei euch grundsätzlich ginge oder wann nicht, kann ich ein paar Doodle Termine überlegen.
Ich stelle mir sowas wie "Freitags ist gut", oder "Unter der Woche Abends", oder "die Woche bin ich nicht da". Das hilft mir schon sehr um ein paar passende Doodle Termine vorzuschlagen.

@caichinger @maosmurf @ReaSu @rolger @codecop @dertseha

**Comment by caichinger** [comment]
> Ich stelle mir sowas wie "Freitags ist gut", oder "Unter der Woche Abends", oder "die Woche bin ich nicht da". Das hilft mir schon sehr um ein paar passende Doodle Termine vorzuschlagen.

Danke für die Initiative, bin für eine zeitnahe Retro, wenn wir das hinbekommen. Mag, wie du deine Erwartung beschrieben hast. :)

Bei mir wäre auch noch Freitag gut.


> update: Ich hab mal ein provisorisches Doodle für die folgenden 3 Tage erstellt. Vielleicht finden wir ja da schon etwas: https://doodle.com/meeting/participate/id/bmEVyR3b

Ausgefüllt.

**Comment by maosmurf** [comment]
Yey! Heute oder morgen Abend jeweils ab 17h gut, Mittwoch geht gar nicht, Donnerstag ab 19h if-need-be.
Doodle ausgefülllt (bis inkl. Mittwoch=)

**Comment by gregorriegler** [comment]
Das erste Doodle war nicht Erfolgreich. Ich habe darum ein neues für Do/Fr erstellt.
https://doodle.com/meeting/participate/id/bmEVzjrb
@caichinger @maosmurf @ReaSu @rolger @codecop @dertseha

**Comment by dertseha** [comment]
Danke für die Einladung, doch nehmt bitte keine Rücksicht auf mich; Ich bin glücklich, großteils ausgesetzt haben zu dürfen - und als einfaches Workshop-Mitglied zu gelten. :)

**Comment by ReaSu** [comment]
Hm, ich hab offensichtlich meinen Kommentar nicht abgeschickt heute Nachmittag.

Ich bin auch für eine zeitnahe Retro, und danke Gregor für die Initiative. Nur ist die erste Wochenhälfte bei mir schon extrem dicht. Donnerstag und Freitag wären deutlich einfacher für mich. 
Do bis 16:30
Fr immer **außer** 14:00-15:00

**Comment by gregorriegler** [comment]
Der Termin steht, es ist Freitag, 10. November (diese Woche) 10:00-11:00
Invite ist raus, wir treffen uns in Gather Town.
Claus, Rea, ihr seid doppelt eingeladen weil ich von euch zwei E-Mails gefunden habe. Wenn ich eine von beiden löschen kann, bitte anweisen.
@caichinger @maosmurf @ReaSu @rolger @codecop
