### ISSUE TITLE
GDCR 2023 Pre/Warmup Remote Event Organisation

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#112]
Idea: Friday could be a Small Coderetreat online to warm up for the Saturday one. Would just need some Zoom account if we are > 10 participants. Or limit at 10 would also be good. I could run that small online one.... Just ideas... Maybe together with some other locations, thinking of Berlin/Wroclaw... Ah now more and more ideas ...

**Friday, 03.11.2023 GDCR23 1st day (09:00 - 16:00) = Pre/Warmup Remote Event**

* run by @codecop 
* hosted (Zoom) by @rolger 
* maybe supported by Martin Klose

**Comment by codecop** [comment]
Setup tasks

* Core @ Github Group / Google Group
* SWK-Event
* SWK-Mail
* SWK-Twitter
* Coderetreat.org
* Share with friends at Calgary and Grenoble and Berlin/Wroclaw?

Maybe create t2o

**Comment by caichinger** [comment]
Do you want to add the pre/warmup event to our website?

If so, we could put it [here](https://github.com/swkWien/gdcr23/blob/main/sessions/_00_landing/_content.qmd) (for now).

**Comment by codecop** [comment]
Yes @caichinger please do

**Comment by caichinger** [comment]
> Yes @caichinger please do. But registration is not ready yet I believe

Added a reference to the warmup event to be updated in the future. Feel free to make amendments.

**Comment by ReaSu** [comment]
Deceivingly, registration is not via Softwerkskammer, but via google forms. So actually reading the text is definitely an advantage here. :-)

**Comment by codecop** [comment]
@gregorriegler @rolger @redseacomputing falls Ihr Feedback zum remote warmup Event hättet, bitte schreibt es kurz hier.

**Comment by gregorriegler** [comment]
@codecop Feedback:
Zwei Halbtage war Interessant. Es hat Leute dazu bewegt auch später noch zu joinen.
In der End-Retro war ich unsicher ob ich auch den ersten Teil berücksichtigen soll, da ja manche Personen nicht mehr da waren, und neue Personen dazukamen. Ich wollte auch den ersten Teil berücksichtigen, aber die Personen waren ja schon weg, haben es nicht gehört. Die neuen Teilnehmer hätten den Kontext nicht gehabt.
In einer Pause war ich nicht rechtzeitig zurück. Ich habe aber teilweise gehört was besprochen wurde. Und ich war rechtzeitig zurück um die anderen Teilnehmer zu fragen was wir tun, bevor sie in Breakouts gingen.
Freie Themenwahl war erfrischend.
Das auffordern der Teilnehmer ihren Code in der Retro zu zeigen, um darüber zu sprechen fand ich gut und wichtig.
