### ISSUE TITLE
GDCR23: Program and Sessions

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#113]
Result should be documented here:
https://github.com/swkWien/sessions/blob/master/2023/cr20231104_gdrc/sessions.md

---

# Topic: Different TDD Styles

## Target audience

Diverse, should be doable for beginners but provide enough
challenge/room for experienced developers as well, e.g. through optional constraints

## Kata: [Tetris](https://en.wikipedia.org/wiki/Tetris)

Tetris from the ground up.

Description: TODO

Links:
- TODO

## Sessions

1. Pen & Paper (Skizze machen, UML, C1-C4; ev. Testlist, etc.)
1. Inside Out (TDD, Pair Programming; Detroit/Chicago; ev. Demo, mit bisschen Design up front)
1. Outside In (mit Fakes oder Mocks; London)

Lunch

1. TDD as if you meant it (ist Inside Out, no Design up front, emergent, -> refactoring
1. Outside In (Extreme fake it till you make it, [Munich](https://de.slideshare.net/davidvoelkel/fake-it-outsidein-tdd-xp2017))
1. Ensemble/verrücktes Constraint/freies Constraint ()

## See also

See also https://picostitch.com/blog/2017/11/25-jscoderetreat-12/

**Comment by gregorriegler** [comment]
I'm happy to help with facilitation.

**Comment by codecop** [comment]
https://youtu.be/_S5iUf0ANyQ?si=9sYe7hu0ZvIt7AI9

**Comment by caichinger** [comment]
Picking up the idea from our discussion, I think it would be useful to introduce each style with a very brief demo at the beginning of the corresponding session. To this end it would be nice to have a suitable example at hand where we can showcase the different approaches.
Maybe we can think of something until our next meeting.

**Comment by caichinger** [comment]
Given the discussion we had last week, I believe one of the challenges with doing the Kata outside-in is identifying suitable collaborators. I guess that is often a challenge but in the Kata the collaborator is maybe not another obvious actor/system but rather an abstraction within the game/domain; for example the [bottom/pile that @maosmurf and  @codecop used in their approach](https://github.com/swkWien/sessions/issues/102#issuecomment-1758399621).

Pile = all pieces that have already descended and settled on the floor/bottom of the game


![Typical_Tetris_Game svg](https://github.com/swkWien/sessions/assets/16005912/528b429b-5591-489d-8e6b-479e62af5e2d)

(Just not as bounding box ;)

**Comment by ReaSu** [comment]
Sessions from


    @caichinger pen & paper
    @ReaSu Focus: Pair programming & Ping Pong; Test first; Test least ("Inside out")

    Demo video?

    @gregorriegler "Outside in" without mocks
    @maosmurf Outside in with predefined interface to be mo
    ❓1x ensemble session @ main room and/or Constraint/free Constraint

**Comment by ReaSu** [comment]
> Sessions from #111
> 
>     1. @caichinger pen & paper
> 
>     2. @ReaSu Focus: Pair programming & Ping Pong; Test first; Test least ("Inside out")
>        Demo Fizzbuzz @caichinger & @ReaSu: was heißt Test first? Was heißt Ping Pont
> 
>     3. @gregorriegler "Outside in" without mocks
> 
>     4. @maosmurf Outside in with predefined interface to be mock
> 
>     5. @rolger selection of constraints  (@gregorriegler 1x ensemble session @ different room)

**Comment by ReaSu** [comment]
@maosmurf session 4: 
Wie stellen wir sicher, dass alle wissen, was ein Mock ist?
Brauchen wir ein Interface - wenn ja, in welchen Sprachen?
Ist das Ziel, dass alle ein Mockingframework verwenden?

**Comment by caichinger** [comment]
In diesem Issue bitte nur mehr Beiträge zum Programm in seiner Gesamtheit.

Etwaige Detailabstimmungen in den jeweiligen Issues:
* [Session 1: Pen & Paper (Claus)](https://github.com/swkWien/sessions/issues/117)
[Session 2: Classical TDD (Rea)](https://github.com/swkWien/sessions/issues/118)
* [Session 3: Outside-In without Mocks (Gregor)](https://github.com/swkWien/sessions/issues/119)
* [Session 4: Outside-In with Mocks (Adam)](https://github.com/swkWien/sessions/issues/120)
* [Session 5: TBD (Roland)](https://github.com/swkWien/sessions/issues/121)

Zur Erinnerung (danke Rea;), unser diesjähriges Motto/Thema:
**Explore different TDD Styles, i.e. strategies to facilitate test-driven development**

Verantwortlichkeiten als Facilitator:
* Vorbereitung & Moderation der Session
* Einhaltung des [Zeitplans](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
* Proaktives Einholen von Unterstützung bei Bedarf

**Comment by caichinger** [comment]
Wenn ihr der Meinung seid, dass ihr mehr/weniger Zeit braucht, bitte melden.

Der Zeitplan ist mehr oder weniger übernommen vom letzten Jahr.

**Comment by caichinger** [comment]
Die Slides sind jetzt *public*. :partying_face:
