### ISSUE TITLE
GDCR23: Update Texts to Reflect Topic

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#114]
We need to update our resources to reflect the topic.
This includes:
* https://github.com/swkWien/sessions/blob/master/2023/cr20231104_gdrc/README.md
* [x] @caichinger https://github.com/swkWien/gdcr23
* [x] @rolger  Eventbrite 

Refs
* #111
* #113

**Comment by rolger** [comment]
I updated the Eventbrite registation page and the 2023 README.md with our topic.

@caichinger there is an update on the swk page, but only if I navigate to the sub-page. Is this correct?

**Comment by caichinger** [comment]
> I updated the Eventbrite registation page and the 2023 README.md with our topic.

Thanks. This means we are ready to send out announcements?

> @caichinger there is an update on the swk page, but only if I navigate to the sub-page. Is this correct?

Not sure what you mean. Do you refer to https://swkwien.github.io/gdcr23/? Then yes, we only show the description on the second slide. That's indeed a bit unfortunate, it would be nicer as the landing page but I failed to implement that quickly. :shrug: 

In case someone wants to take a look:
The title attribute in the config file is the culprit. However, without this attribute, the browser window shows "index".

---

With regards to the content, I rephrased the line as follows:

> 🤓 Focus on different **TDD styles** to facilitate test-first development

To make more explicit what we aim to do.

**Comment by caichinger** [comment]
@rolger I leave it to you if you want to update the texts again. I think "Focus on different TDD styles to facilitate test-first development" is better than the original "Focus on different TDD styles (test-first development)" but ...

From my side we can close this issue.
