### ISSUE TITLE
Meetup-> Group name

### ISSUE THREAD

**Issue by redseacomputing** [swkWien/sessions#115]
There have been past discussions around this topic.
To increase the visibility of the Softwerkskammer there will be a meetup group for our events.

The content of the Softwerkskammer homepage will be used as description. 
An internet link to the official softwerkskammer.org page will be included.

Possible names of the group are
"Software Crafters" or
"Software Craftsmanship"

I ask you for feedback and suggestions regarding the name of the group.
Best regards, Christopher

@codecop @maosmurf @gregorriegler @ReaSu @caichinger @goerge @rolger

**Comment by codecop** [comment]
To add more context. Redsea will create a meetup account to amplify our reach. I propose to create it similar to software crafters Zurich or Berlin. Details of name and description are for discussion

**Comment by caichinger** [comment]
From the examples offered so far I would go for "Software Crafters Vienna" (not sure about upper/lower case).

**Comment by caichinger** [comment]
Out of interest, can you provide more context please?

---

> There have been past discussions around this topic.

What happened since the last discussion?


> To increase the visibility of the Softwerkskammer there will be a meetup group for our events.

I guess visibility is a good thing.

How are we going to use meetup.com? Like a mirror for softwerkskammer.org events?
Who manages the account and eventual events?
Who pays for the account?

**Comment by ReaSu** [comment]
I'm late to this party, sorry for that.
* I'm glad you decided on Software Crafters and not Software Craftsmanship - I, for one, don't identify as a craftsman, but I do as a crafter, so this feels more inclusive.
* I think what would help to attract more people would be, most of all, earlier announcements and possibly a regular schedule. If meetup helps/forces us to do so - great!

What do you mean by "The next CR is limited"?

**Comment by caichinger** [comment]
Ich merke da beschäftigt mich was und ich schreibe hier und möchte gerne am Freitag kurz daran anknüpfen.

Damit es gar nicht zu einem Missverständnis kommt:
**Danke @redseacomputing für die Initiative! Das ist sicher ein guter Impuls!**

---

Wir sind ein loser Haufen und daher ist mir wichtig, dass wir in der Kommunikation transparent sind. Dann habe ich auch ein Gefühl von "wir machen da was gemeinsam".
Für mich sind Lücken zwischen den Botschaften, die per Issue transportiert werden.


> @ReaSu and myself has noticed that it's no fun to prepare stuff for dojos if nobody shows up.

Verstehe ich nur zu gut.

In https://github.com/swkWien/sessions/issues/107 habt ihr Punkte besprochen die euch beschäfitgen. Es gibt aber keinen direkten Hinweis darauf, dass eurer Meinung nach kein-meetup.com das Problem ist.


> Since there was no output from existing "lets change to meetup" discussions I want to pay and manage the account from now on.

In https://github.com/swkWien/sessions/issues/108 hat sich aus mir und Christian niemand dazu geäußert. D.h. an dem Punkt war es (laut Issue) auch niemandem wichtig genug. Das ist also das Ergebnis der Diskussion: nicht wichtig (auch euch nicht).


> And yes, it should be a mirror of the swk events of course.

Danke für die Klärung.

Ich fand es deswegen gar nicht so klar, weil meinem Empfinden nach die *größeren* Fragen "Wie planen wir Events? Wie kündigen wir sie an?" immer wieder anders beantwortet werden.

**Comment by caichinger** [comment]
> Yes, i thinks SWK more than a movement than something else. Hence, i think, i panic once a year if i have not brought me in from my side properly. :)

Really appreciated! Thank you for responding.

> If one of my tasks would be a absolute no-go for someone, it is the best thing to communicate that like @caichinger did.
> I appreciate that.

Definitely not a no-go. 

I wanted to share my part of the experience regarding movement (and moving together).

> We can close the meetup group of course and I use the account for anything else. Or maybe we can use this thing in another manner if it rather exists.

Again, I am more discussing the process, not the outcome. There is definitely potential in using meetup.com!

**Comment by maosmurf** [comment]
I like the initiative @redseacomputing , too!
Whatever serves the Vienna Group getting more attention and attendees, I welcome!

On another note, I also support the naming "Software Crafters Vienna". I just noticed the "URL slug" is still "software-craftsmanship-vienna". Wonder if we could change that too (before we get too big)

**Comment by ReaSu** [comment]
Ich find auch, dass alles gut ist, was uns hilft, mehr Leute anzuziehen. Meetup ist da sicher kein Fehler. Ich glaub aber auch, dass es nicht reicht, eine Meetup - Gruppe zu haben. So wie immer bei social media: Was zählt ist, was wir draus machen.

Und wie Claus sind da bei mir viele Fragen offen:
Was sind unsere Ziele? 
Wen wollen wir erreichen, und wie kommen wir an diese Leute? 
Was hat bisher gut geklappt, was nicht, und was können wir draus lernen?
Wo zahlt es sich aus, unterschiedliche Resourcen zu investieren, und wo nicht?
Was ist meine Rolle, wofür bin ich verantwortlich, und wofür nicht? Wo kann ich wie viel Initiative aufbringen, ohne dass sich jemand übergangen fühlt?

Vielleicht können wir wirklich am Freitag uns ein bisschen Zeit für solche Dinge nehmen - und wenns über Mittag ist.

**Comment by caichinger** [comment]
@redseacomputing 

Wie @maosmurf meinte:

> On another note, I also support the naming "Software Crafters Vienna". I just noticed the "URL slug" is still "software-craftsmanship-vienna". Wonder if we could change that too (before we get too big)

Können wir da noch was machen?

Bzw wie tun wir damit?

Wir werden den GDCR nutzen, um die Teilnehmenden auch auf Meetup einzuladen, daher die Frage.

**Comment by ReaSu** [comment]
Since the name of the group is Software Crafters Vienna, I think software-crafters-vienna would work rather well.

**Comment by caichinger** [comment]
> @caichinger yes, the URL can be changed. I have used same as the other two recommended crafter groups in first place. What exact url should we use? @ReaSu @maosmurf @codecop

Thank you for the quick response. I understand your reasoning.
Since it is possible, I am :+1: for changing it to reflect the name of *our* group.

> Since the name of the group is Software Crafters Vienna, I think software-crafters-vienna would work rather well.

And I agree with @ReaSu.

**Comment by caichinger** [comment]
Danke @redseacomputing für das Update und die QR-Codes!

Follow up Issues:
- Website update: https://github.com/swkWien/sessions/issues/122
- Zettel für GDCR: https://github.com/swkWien/sessions/issues/123
