### ISSUE TITLE
GDCR23: Topic Poster "Different TDD Styles"

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#116]
Unser Motto

> Explore different strategies to facilitate test-driven development

Es gibt [verschiedene Stile/Zugänge (Schulen)](https://www.tddstpau.li/) und wir schauen uns ein paar davon an.

![image](https://github.com/swkWien/sessions/assets/16005912/cc03d75b-c227-4d27-83dd-ff92e878c610)

@ReaSu und ich haben uns gedacht, es wäre interessant, dazu ein Poster / Flip Chart zu gestalten um vor Ort damit arbeiten zu können:

> Was ist das Thema des Tages?
> Was ist der Fokus der Session?

Unser Poster könnte so aussehen:

| Aspect | Classical TDD | Outside in without Doubles | Outside in with Doubles |
|------------|--------------|----------------|----------------|
| Direction | Inside-Out | Outside-in | Outside-In |
| Start with ... | simplified system | simplified system | complex system |
| Use of Mocks | avoid | avoid | embrace |
| Schools | Detroit | Munich, St. Pauli | London |

Hier sind:
- Spalten (=Strategie):
  - Titel der Session
  - Nicht die "Schulen" (Detroit, London, etc.), erwähnen wir aber ist zu *willkürlich* und nicht unser Fokus
- Zeilen (=Eigenschaften):
  - Direction: Klar
  - Use of Mocks: Klar
  - **First Test Case? Unklar** :point_left:  :thinking: 

**Bitte um euren Input zu:**
* Was heißt für euch "First Test Case? Simple ODER Complex"?
* Welche Testfälle werdet ihr anmoderieren und was soll daher in der Tabelle stehen?
* Macht ihr einen Guiding Test?

**Comment by caichinger** [comment]
| Aspect | Classical TDD (Detroit) | Outside in without Mocks (St Pauli or Munich) | Outside in with Mocks (London) |
|------------|--------------|----------------|----------------|
| Direction | Inside-Out | Outside-in | Outside-In |
| First Test Case? | Simple | TBD: Simple OR Complex | Simple |
| Use of Mocks | avoid | avoid | embrace |

**Comment by ReaSu** [comment]
Ich werde es freistellen, mit welchem Test aus der P&P-Session sie beginnen wollen. Als Extra-Challenge hab ich vorgeschlagen, die andere Richtung zu versuchen, als man üblicherweise macht.

Und während ich das schreibe fällt mir auf, dass das nicht ist, was wir ausgemacht hatten. Ich sollte ja Detroit/Standard inside-out machen, also mit einem einfachen/simplen Test beginnen. Back to the drawing board. :facepalm:

**Comment by caichinger** [comment]
> Ich werde es freistellen, mit welchem Test aus der P&P-Session sie beginnen wollen. Als Extra-Challenge hab ich vorgeschlagen, die andere Richtung zu versuchen, als man üblicherweise macht.
> 
> Und während ich das schreibe fällt mir auf, dass das nicht ist, was wir ausgemacht hatten. Ich sollte ja Detroit/Standard inside-out machen, also mit einem einfachen/simplen Test beginnen. Back to the drawing board. 🤦

Danke für das Lachen, das du mir mit deinem Kommentar geschenkt hast :D

Noch ein Gedanke:

Ich finde es schon fein, wenn es eine wirkliche eine Aufwärmsession gibt, damit man mal in Ruhe reinkommen und ankommen kann. Einfach sauber PP und TDD machen, das ist eh schon einiges. Extra Challenges sind cool aber sie können mMn auch den Fokus stören.

**Comment by caichinger** [comment]
Gedanken:
* Im Rahmen der Retro befüllen:
  * Wie unterscheiden die TN die Stile --> das könnte Teil der **Abschlussretro** sein
* Man könnte auch fragen, wann/wo/wie Design passiert

**Comment by caichinger** [comment]
Wenn man obige Idee aufgreift, ist diese Abschlussretro aber mehr als nur eine Retro. MMn mehr eine Reflektionsrunde zum Thema.

**Comment by caichinger** [comment]
@ReaSu was ist dein Gefühl dazu?

**Comment by caichinger** [comment]
@ReaSu 

Danke für's Update des Posters und deine Kommentare und allen, die mitdiskutiert haben.

> Start with ...

Fühlt sich stimmig an.

---

> Rahmen präsentieren

Ja! Dieser Rahmen, das ist unser Angebot. Und: Unser Anspruch. Denn wir haben einen Anspruch formuliert.

> Das Problem mit der Tabelle war [...]

Ja. Wir haben uns entschieden, den Tag unter ein Motto zu stellen und da ist es mein Wunsch und meine Hoffnung, dass wir in der Lage sind den Rahmen auch zu artikulieren, bspw. in Form einer Grafik (Tabelle). Die Form war TBD und es scheint mir, dass wir wo angekommen sind.

**Comment by maosmurf** [comment]
Has someone taken a photo of the poster?
In any case, I suggest closing this issue.

**Comment by caichinger** [comment]
> Has someone taken a photo of the poster?

Ja, ich habe ein Foto gemacht und werde es noch hochladen.


> In any case, I suggest closing this issue.

Das mache ich dann.

**Comment by caichinger** [comment]
![image](https://github.com/swkWien/sessions/assets/16005912/72133960-e1cd-40eb-bc9a-5c468f42af97)


![image](https://github.com/swkWien/sessions/assets/16005912/36979cfc-351b-4c74-9317-91a695480e40)
