### ISSUE TITLE
GDCR23: Session 1: Pen & Paper / Final Retro / Closing

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#117]
**Facilitator: Claus**

- [x] Co-Facilitator: not needed (reach out proactively if you believe support during the session would be helpful)
- [x] [Schedule](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
- [x] [Slides](https://github.com/swkWien/gdcr23) until Thursday, 2023-11-02
  - [x] Session
  - [x] Final Retro
  - [x] Closing
    - [x] Join us on meetup (QR code?)
    - [x] Join our next dojo
- [x] What is your first test case? Pls provide input on #116

**Comment by caichinger** [comment]
@ReaSu für's Closing:

Das Follow Up Dojo, magst du, dass ich auch gleich ein Thema ankündige?

**Comment by caichinger** [comment]
> @ReaSu für's Closing:
> 
> Das Follow Up Dojo, magst du, dass ich auch gleich ein Thema ankündige?

Wenn ja, dann bitte in den Slides vermerken. Habe dich mal "nur" mit Termin angekündigt.

**Comment by caichinger** [comment]
Von meiner Seite ist der Entwurf fertig. Gerne Feedback.

**Comment by gregorriegler** [comment]
@caichinger wenn ich die Slides durchsehe erscheint deine session noch nicht.
https://swkwien.github.io/gdcr23/#/1/3

**Comment by ReaSu** [comment]
> @caichinger wenn ich die Slides durchsehe erscheint deine session noch nicht.

Das liegt daran, dass im index.qmd die Sessions noch auskommentiert sind. Du kannst sie lokal bei dir anzeigen lassen. Da die Seite so schon online ist, werden die Sessions erst kurz vor dem Event auch live geschaltet.

**Comment by caichinger** [comment]
@rolger ich vermute es gibt vor Ort wieder Blöcke und Stifte, richtig?

**Comment by gregorriegler** [comment]
@caichinger @ReaSu @maosmurf kann mich jemand adden damit ich meine slides pushen kann?

**Comment by gregorriegler** [comment]
Nevermind. Mergerequest: https://github.com/swkWien/gdcr23/pull/1/commits/8480ddd9698f668913a470a6b7052ba1088b0a52

**Comment by caichinger** [comment]
> @caichinger @ReaSu @maosmurf kann mich jemand adden damit ich meine slides pushen kann?

Falls du morgen ad hoc was ändern magst/musst frage ich:

Du hast keine Rechte?

Die ganze https://github.com/orgs/swkWien/teams/organiser Gruppe hat Maintainer Rechte auf https://github.com/swkWien/gdcr23/ und du bist in der Gruppe drinnen. Ich kann dich zur SIcherheit auch noch einzeln hinzufügen.

**Comment by caichinger** [comment]
Ich habe dich @gregorriegler einfach auch noch mal direkt hinzugefügt, falls was sein sollte.

Können dann immer noch Ursachenforschung betreiben.

**Comment by caichinger** [comment]
> @rolger ich vermute es gibt vor Ort wieder Blöcke und Stifte, richtig?

Ja, gibt es. Ich schließe das Issue.
