### ISSUE TITLE
GDCR23: Session 2: Pair Programming & TDD Demo / Classical TDD

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#118]
**Facilitator: Rea**

- [x] Co-Facilitator: @dertseha 
- [x] Session Title: Classic TDD
- [x] [Schedule](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
- [x] [Slides](https://github.com/swkWien/gdcr23) until Thursday, 2023-11-02
  - [x] Pair Programming
  - [x] TDD
  - [x] Demo
  - [x] Session
- [x] What is your first test case? Pls provide input on #116 

---

*Please amend issue to your needs.*

**Comment by caichinger** [comment]
Noch ein Gedanke zur Demo:

Wir könnten auch einen Testfall aus dem Publikum aufgreifen. Also zuerst Fragen, welche für Testfälle gesammelt wurden (manche sind noch aus der Retro präsent) und dann nehmen wir einen davon. In dem man sieht, dass es offenbar verschiedene Möglichkeiten gibt und wir sagen, dass man halt auch irgendwo anfangen muss, können wir denke ich unsere Sorge "Oje, biasen wir sie zu sehr?" verabschieden.

Was meinst du?

---

Wir können zur Sicherheit trotzdem einen Fall vorbereiten bzw. vorab durchbesprechen. Das ist wahrscheinlich gut, um uns Vertrauen zu geben.

**Comment by ReaSu** [comment]
Find ich gut, die Idee mit dem Testfall aus der vorigen Session!

**Comment by caichinger** [comment]
> Find ich gut, die Idee mit dem Testfall aus der vorigen Session!

Okay :)

**Comment by caichinger** [comment]
Zur Info: Test cases sind ein explizites Ergebnis von Session 1, vgl https://github.com/swkWien/gdcr23/commit/17d7c4fd7e36a4ec0f7cfa37f492807e638ae32e

**Comment by ReaSu** [comment]
Wer mag mit mir Co-Facilitaten? 26+ Anmeldungen sind sehr viel für allein, find ich.

**Comment by dertseha** [comment]
Mein Angebot steht noch - und von all den Optionen ist für mich "classic TDD" wohl am einfachsten :)

**Comment by ReaSu** [comment]
Danke, Christian!

**Comment by caichinger** [comment]
> Wer mag mit mir Co-Facilitaten? 26+ Anmeldungen sind sehr viel für allein, find ich.

Wenn neben Christian noch Bedarf besteht, kann ich auch dazu kommen (bspw. wenn es mehrere Paare ohne TDD Erfahrung gibt, damit die nicht zu lange warten müssen).

**Comment by ReaSu** [comment]
Danke! Das werden wir ja dann sehen.

**Comment by maosmurf** [comment]
Happy to assist (any session), too!
Note I will be away 8:50-9:15 👦
