### ISSUE TITLE
GDCR23: Session 4: Outside-In with Mocks

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#120]
**Facilitator: Adam**

- [ ] Co-Facilitator: ______ (reach out proactively if you believe support during the session would be helpful)
- [ ] Session Title: ______
- [ ] [Schedule](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
- [ ] [Slides](https://github.com/swkWien/gdcr23) until Thursday, 2023-11-02
- [ ] What is your first test case? Pls provide input on #116 

---

*Please amend issue to your needs.*

**Comment by caichinger** [comment]
Cf https://github.com/swkWien/sessions/issues/113#issuecomment-1781428546

**Comment by caichinger** [comment]
Ich glaube das ist eine extrem coole Session und ich glaube sie ist nicht so leicht auf den Boden zu bringen.
Sie kann ruhig anspruchsvoll sein, das finde ich gut; es muss auch nicht bei allen das gleiche passieren oder raus kommen. Im Moment sehe ich aber Hürden für weniger erfahrene Personen und stelle mir die Frage, wie man für diejenigen ein Erfolgserlebnis (das kann ja auch anders ausschauen) gestalten kann.

Gedanken meinerseits:
- Wie gesagt, ich finde sie sehr cool :)
- Moderation/Aufbereitung/Anleitung glaube ich nicht so ohne
  - In welcher Form stellst du das Interface dar oder zur Verfügung?
  - Wenn als Code, dann müssten wir das noch vorbereiten (unsere Zeit)
  - Wenn als Beschreibung, dann sollten das möglichst viele verstehen und zumindest in Teilen implementieren können (das braucht Zeit)
  - Wenn es in deiner Session Sinn macht ein Mock Framework zu verwenden, dann wäre es gut wenn wir dazu schon konkrete Vorschläge haben (evtl Demo; Installation und verstehen wie man einen Mock macht braucht auch wieder Zeit)

Roland meinte gestern, dass in seinen Trainings "Outside-In mit Mocks" schon Zeit braucht.

FYI @ReaSu @rolger

**Comment by rolger** [comment]
Wie kann man out-side-in und mit dieser Domäne zusammen bringen? Es gab die Idee des Blocks als Interface, dsa müsste man genauer beschreiben. Zu wenig Hilfe könnte zur Frustration führen, zu viel schränkt die Initiative ein und wirkt wie ein Training.

Mögliche Hilfestellungen, die ich sonst in meinen Trainings verwende

- Collaborators vorgeben / nicht vorgeben und im Plenum diskutieren
  - Test-Double Art: Stubs sind einfacher als Mocks
  - Schnittstellen detailiert beschreiben oder wie oben diskutieren oder sie soll durch den Code entstehen
- Beispiele
  - können ebenso vorgeben werden oder im Plenum diskutiert werden
  - man könnte ein Format vorgeben z.B.

| Testfall | Testobject | Collaborator |
|             | IN   | OUT | IN        | OUT |
+++++++++++++++++++++++
...

**Comment by maosmurf** [comment]
Note: while preparing the slides, I suggest to change the title to a more generic one: `Outside-In with test doubles` (vs. with Mocks), as the example we prepared is actually built around stubs. Happy to elaborate tomorrow.

**Comment by ReaSu** [comment]
Feel free to change the title as it suits you - it's your session!
