### ISSUE TITLE
GDCR23: Opening / Topic / Kata / Session 5: TBA

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#121]
**Facilitator: Roland**

- [ ] Co-Facilitator: ______ (reach out proactively if you believe support during the session would be helpful)
- [x] Session Title: ______
- [ ] [Schedule](https://docs.google.com/spreadsheets/d/1QG6HFDRYc6USwp6FPPikUBR69i1SRI3obrzPJZdcOZQ/edit?usp=sharing)
- [ ] [Slides](https://github.com/swkWien/gdcr23) until Thursday, 2023-11-02
  - [ ] Opening
  - [ ] Topic
  - [ ] Kata
  - [ ] Session
- [ ] What is your first test case? Pls provide input on #116 

---

*Please amend issue to your needs.*

**Comment by caichinger** [comment]
Ich nehme in meiner Session kurz auf das Kata Bezug. Slides sind online, dieser Commit: https://github.com/swkWien/gdcr23/commit/17d7c4fd7e36a4ec0f7cfa37f492807e638ae32e.

**Comment by rolger** [comment]
Als Reminder und Ideen Sammlung für mich https://github.com/achakravarty/gdcr/blob/master/Constraints.md
