### ISSUE TITLE
Update https://swkwien.github.io/ to include meetup.com

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#122]

**Comment by ReaSu** [comment]
I tried to do this, but I don't have sufficient permissions.

Can someone please make me an owner of swkWien? Or are there any reasons speaking against this?

Pinging current owners @caichinger @codecop @dertseha

**Comment by caichinger** [comment]
> Can someone please make me an owner of swkWien? Or are there any reasons speaking against this?
> 
> Pinging current owners @caichinger @codecop @dertseha

Ich habe dich einfach mal Owner gemacht.

---

Es gibt Teams (https://github.com/orgs/swkWien/teams) und zusätzlich die Rollen in Members (https://github.com/orgs/swkWien/people), die Aufteilung ist mir nicht klar. Evtl mal tbd.

**Comment by ReaSu** [comment]
Danke! Ja, die diversen Rollen sind mir auch ein bisschen Schleierhaft. Könnte man sich mal anschauen, wenns uns fad ist. :stuck_out_tongue_winking_eye: 

https://swkwien.github.io/ ist upgedated, damit schließe ich das Issue.
