### ISSUE TITLE
GDCR23: Bitte drucken

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#123]
### Join us on Meetup

- [ ] Bitte ein paar Mal ausdrucken (und aufhängen; können wir dann ad hoc machen). Danke!

https://docs.google.com/document/d/1YrmL5kZ3DWh08C7Y2FelKCHfBVO2Wpw0qOYaOAKQ8yY/edit?usp=sharing

**Comment by maosmurf** [comment]
@rolger please print also [bottom.pdf](https://github.com/swkWien/sessions/files/13255177/bottom.pdf)
