### ISSUE TITLE
New member?

### ISSUE THREAD

**Issue by redseacomputing** [swkWien/sessions#133]
Hello @swkWien/organisers ,

probably there is a person who wants to become a member at our group.
I did not ask or talk him. It is just a gut feeling for now. 
First time I have seen him at GDCR2024 and he was extraordinary excited in general of SWKs vision.
Afterwards and nowadays, i see that he checks our activities on Meetup on a regular basis.
 
If he would join the next Dojos / CRs, I would like him to ask him if he would be interested to help.

**Comment by codecop** [comment]
Sure Go for it
