### ISSUE TITLE
Invitation to discuss the future of (global) Coderetreat

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#135]
Hallo Leute, es hat mich eine Einladung von Raimo Radczewski (he/him) (Orga des Global Day und Maintainer von Coderetreat.org) erreicht:

> Peter, wäre schön wenn du und deine Crew an der Open Door Session am 11. April teilnehmen könntet:
> Trainers & Facilitators! On April 11th, mplavcan and I will be hosting a special Open Door session: We want to discuss the future of coderetreat with you, how the format can adapt, what you local organizers need and where XP practices fit in a world where your copilot claims to write the tests for you :scream:
> https://www.meetup.com/coderetreat-training/events/299906141/

Ich weiß nicht worum es genau geht. Raimo hat mich aber direkt angeschrieben. Raimo und Mplavcan waren in der Vergangenheit immer sehr hilfsbereit. Damit ist es wichtig für mich. Leider bin ich an dem Tag verhindert. Wäre super wenn jemand von Euch, speziell Orga von unserem Global Day (@ReaSu @caichinger @gregorriegler oder @maosmurf ) daran teilnehmen könnten. Bitte wer macht das?

**Comment by maosmurf** [comment]
Danke!
Ich werde am 11. April teilnehmen und ggf. Findings mit Euch hier teilen.
Umgekehrt: falls ihr Input/Fragen habt, gerne vorab hier stellen.

**Comment by codecop** [comment]
Link to Event:
The Future Of Coderetreats And Teaching Software Development
https://www.meetup.com/de-DE/coderetreat-training/events/299906141/

**Comment by dertseha** [comment]
...was war nun das Ergebnis?
