### ISSUE TITLE
Announce GDCR24

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#139]
@rolger der Text von 2023 passt gut, nur 2 Änderungen
1. Thema ist Incremental Development
2. Zeit würde ich gerne bis 1730 machen, damit Zeit für eine Kaffeepause am Nachmittag ist.
Sonst bitte asap das Eventbrite Event anlegen. Danke

**Comment by codecop** [comment]
Nach dem Eventbrite haben wir folgende Kanäle zu befüllen
* Coderetreat.org PR - @gregorriegler 
* Meetup/SWK nur Email, kein Event - ?
* CIS FH - @ReaSu 
* Women who Code - @ReaSu 
* Crafters Slack - Peter
* SoCraTes Linz Mailing? - Peter
* allgemein Twitter/BlueSky/Mastodon/LinkedIn Posts zum sharen - ?

**Comment by rolger** [comment]
https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2024-tickets-1047932723987

**Comment by rolger** [comment]
Ich haeb jetzt 8:30 bis 17:30 angeben. Ich biete wieder Frühstück an

**Comment by codecop** [comment]
@rolger bitte noch fixen
>This year will focus on different TDD styles to facilitate test-first development.
-->
This year will focus on Incremental Development using TDD.

**Comment by rolger** [comment]
Ich habe noch die Fragen vom letzten Jahr hinzugefügt und die Bestätigungs-Email angepasst.

**Comment by rolger** [comment]
Morgen frage ich unser Marketing damit sie uns einen Flyer erstellen

**Comment by gregorriegler** [comment]
Wir sind auf [coderetreat.org](https://www.coderetreat.org/).
Weiters habe ich ein doodle ausgeschickt. Ich hoffe dass wir einen baldigen Termin finden.

**Comment by rolger** [comment]
Ich habe auch noch einen Post auf LinkedIn erstellt:

https://www.linkedin.com/posts/roland-germ-a996b186_global-day-of-coderetreat-vienna-2024-activity-7254519645116780544-MjXb

Außerdem hätte ich Flyer, weiß aber nicht wo ich die verteilen soll :-)

**Comment by codecop** [comment]
So habe jetzt auch SWK und Meetup Mail mit dem Register Link geschickt. Damit ist alles mal gemacht. Eventuell nächste Woche nochmal irgendwo platzieren, keine Ahnung wo?
