### ISSUE TITLE
Reorganize sessions folder

### ISSUE THREAD

**Issue by dertseha** [swkWien/sessions#38]
We've collected quite a lot of sessions over the years already. With the recent rebranding, I'd like to clean up here as well:
* Move sessions to year-specific folders. session folder name stays identical. e.g. ```repo-root/session20001122/*``` will become ```repo-root/2000/session20001122/*```
* All sessions that reference the reveal-js at the root will receive their local copy. (Git handles file duplications very well) Remove reveal-js at the root.

This can be done in one go, since each index.html needs to be touched for either operation.

I'm still running around with various lose ends with the rebranding here. I'll take this task afterwards - unless someone else already assigned themselves.

**Comment by mlem** [comment]
I see those sessions as documents. And in my opinion, we shouldn't change
the namin in there. Just put a "formerly known as CodingDojoVie" at the top
of the readme and it should be ok

Am 05.02.2018 19:38 schrieb "Christian Haas" <notifications@github.com>:

**Comment by dertseha** [comment]
I still want to collect the presentation slides in this repository. And I also don't want to change the name (titles) that the previous ones had, which is also why I want to localize the reveal.js.
This is essentially the archive of our progress and all I want now is to make it more presentable and self-contained while also prepared for future extension.

**Comment by codecop** [comment]
thank you @dertseha for investing the work here. #springcleaning ;-)
I am curious if we manage to get the missing sessions somehow.

**Comment by dertseha** [comment]
Stuff successfully moved around. repository looks way cleaner now :)
And I also missed the spot to reference this issue in the merge. oh well.

The only functionality that was "lost" is the self-serving capability, that probably no one knew about. I myself even forgot about this - it required node & grunt running on the local machine to start a web-server. Yet, simply opening the .html file in the browser worked equally fine all these years ;) So I deleted the respective files.

**Comment by codecop** [comment]
@dertseha I seem to have lost ability to add members to the orga team?

**Comment by dertseha** [comment]
This was not part of the reorganization, this was because GitHub changed how teams & access priviledges work. I don't follow their daily progress, so I don't know when this happened.
Role restored.

**Comment by codecop** [comment]
thx. I added Gregor running F# Coding Dojos but true to our spirit.
