### ISSUE TITLE
Coderetreat on November 17th (GDCR18) 

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#40]
The date for GDCR has been announced.

**Comment by codecop** [comment]
FYI @swkWien/organiser Techtalk has invited JB Rainsberger to run the GDCR18 in Vienna. Exciting times...

**Comment by dertseha** [comment]
Invited? Or also secured? ;)
Interesting feat. I take it it'll be combined with some talk(s) around that time with him as well.

**Comment by paulroho** [comment]
Secured (with a tiny theoretical gotcha).
And yes, you're right:
https://techtalk.at/trainings/agile-design-beyond-the-basics/
http://agiletourvienna.at/

**Comment by mlem** [comment]
That's awesome. Looking forward to it

Paul Rohorzka <notifications@github.com> schrieb am Sa., 9. Juni 2018,
16:44:

**Comment by dertseha** [comment]
GDCR in Vienna is run exclusively by TechTalk - Do we need this issue here open?

**Comment by codecop** [comment]
It is run by JB and me, hosted by TechTalk that is true. And yes, at the moment I do not see any work that needs that ticket. Still it is our Coderetreat.

**Comment by dertseha** [comment]
Right, sorry, I forgot about that constellation. Carry on :)

**Comment by codecop** [comment]
After questions during last coding dojo, I asked Paul about making seats available ... pending

**Comment by paulroho** [comment]
Expecting further information on Monday.

**Comment by dertseha** [comment]
..which Monday? ;)

**Comment by paulroho** [comment]
Sorry for the late reply. This is the current state:

We found an opportunity in the office building for a place with more space than in our meeting room. That would provide space for about 40 people, I guess. I'll keep you updated as soon as I know more. I expect this opportunity to work out, as we are out of additional meeting room space in our current office.

FYI, there are currently 4 people on the waiting list.

**Comment by codecop** [comment]
if we get a larger venue, we need to make more fuzz about the event - to use the larger venue

**Comment by paulroho** [comment]
Two tweets for retweeting:

- https://twitter.com/paulroho/status/1059786562542682112
- https://twitter.com/techtalks/status/1059789278685917184

**Comment by codecop** [comment]
thank you
