### ISSUE TITLE
Moar Coderetreats (Zero Overhead Coderetreats)

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#46]
As I said in the end of GDCR18 (#40) I would like to attend more Coderetreats. And who would not? ;-) Which means I have to make more of them. Here are my ideas for a format that is maybe more sustainable and which I would like to discuss with you to do so:

**Must be minimal to no overhead for us as organizers**
* small group, 6 to 10 ppl max, = 
    * 6 to 8 regular/repeating dojo or CR guests, + 
    * maybe 2 newcomers (we can deal with them on the fly)
    * I want to limit public access, still be available to newcomers...
    * from my memory I count at least 20 repeating guests that might be interested (including you)
* no big registration, no big fuzz, maybe a SWK event for registration. only trusted ppl, no money transfers
* we agree to go to lunch together, either Kantine or restaurant nearby

**No facilitator**
* we all know what needs to be done, many of us have run a CR themselves
* instead of intro 
    * inform us about the venue (fire exits etc)
    * see which languages we have around
    * we discuss the goal of the day and chose a topic, e.g. OO or FP
* after session we discuss in a circle again and choose next constraint for us and according chosen topic

**Open Questions**
* frequency: one such CR every 3 months? maybe even every month? sure not everybody will be free each time, still it is about creating opportunities to learn
* day - still Saturday? I am also available certain days in the week, as are some freelancers.
* venue - venue is always the problem, but a room for 10 = 5 pairs should be easier to get that 40...

Please let's discuss @dertseha @paulroho @mlem @duffleit @xbojch @Goerge

**Comment by paulroho** [comment]
Peter, I love your proposal.
It would be way easier for me to attend during the work week than on a Saturday, esp. if we plan ahead for a longer period.

**Comment by dertseha** [comment]
Thank you for your proposal.
I'm commenting here to mark that I have read it and will think about it - yet I don't have an immediate, streamlined answer.
Various thoughts that come up at the moment are conflicting and deal more with my own situation rather than your idea.

**Comment by mlem** [comment]
I'm not sure we would fill the slots if we do it every 3 months. I'm
suggesting to meet to discuss this issue. I will organize a coding dojo
next month. Either than or a seperate meeting? I understand that not
everybody has enough time to meet, but it's easier for me to communicate
directly in person with you all. Tell me what you think about this.

Cheers, Martin

Am Mo., 19. Nov. 2018, 18:56 hat Christian Haas <notifications@github.com>
geschrieben:

**Comment by xbojch** [comment]
I like the idea. A coding dojo is sometimes just enough to get started. Not sure how many I could attend in this or the following year. However I am sure that LRT would be glad to provide a room for up to 20 participants.

Von meinem iPhone gesendet

**Comment by dertseha** [comment]
Addendum: Having said all of that, this is more of a consumer-view. If, however, I already have some things that others would like to know about, then we'd have a provider-view - and I'm always happy to tell/teach others (willing to listen) about stuff.

**Comment by codecop** [comment]
@dertseha I guess you can always bring Go to the table, and C++ of course.

@goerge volunteered to run the first instance, in 4 weeks, last week before Xmas (17 to 25th Dec)
We still discuss the day of the week. During week is easier for some ppl. Rooms are easier to get on Saturday.

**Comment by mlem** [comment]
I was planing to do a dojo in December. Should I plan for 10th Dec? Or is
it ok if we focus on this coderetreat, and I'll do the dojo in January


Am Do., 22. Nov. 2018, 00:34 hat Peter Kofler <notifications@github.com>
geschrieben:

**Comment by codecop** [comment]
After discussing with @dertseha I decided for a schedule of every third Saturday every second month. So the days are known long time in advance. I stayed with Saturday because it is easier to get a room for us then. We might shorten the CR to 5 sessions if needed, we will see.

I created a session ticket, see #48 to manage them.

**Comment by codecop** [comment]
This seems to run for now. Closing
