### ISSUE TITLE
Coding Dojos 2019

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#47]
The Coding Dojo is a two hour practice session. It is run during the week in the evening after work. It is held on different days and announced one week in advance approx. every second month.

Month, Who @ Where (when) [- what]
Jan, Roland/Peter @ Nagarro (29.01.2019) - Dependency Breaking Techniques
Apr, Claus @ willhaben (15.04.2019)
June, Christian @ Zühlke (12.06.2019)
July, Bojan @ LinkResearchTools (25.07.2019)
Oct, Gregor @ Ebcont (16.10.2019) - Split Phase Refactoring
Dec, 

### done

#36 #19 #5 #4

**Comment by paulroho** [comment]
Happy New Coding Dojo Year to all of you!

January topic sounds great. @rolgerm, any news for the exact date?

**Comment by caichinger** [comment]
@paulroho https://www.softwerkskammer.org/activities/CodingDojoVie20190129 (there was a mail on 2018-12-15 in case you need it)

**Comment by codecop** [comment]
Hi @swkWien/organiser we have not scheduled a Coding Dojo for February yet. Who is going to run it?

**Comment by codecop** [comment]
Ping @caichinger @xbojch @mlem

**Comment by xbojch** [comment]
Sorry, can’t organize a dojo this month.

Von meinem iPhone gesendet

**Comment by caichinger** [comment]
Me neither, conference is keeping me busy atm. (I will however take March or April, updates to follow)

**Comment by caichinger** [comment]
I will facilitate the April dojo on Tuesday, 2019-04-16 if someone provides a venue.

**Comment by duffleit** [comment]
I wrote a couple of emails and also shared it on twitter:
https://twitter.com/duffleit/status/1100139478113501185 - should not be
choked off by a missing venue! :)

**Comment by mlem** [comment]
@caichinger
Hey Claus,

I will take care of the venue for you.
I will need the participant numbers to pick the right room for the coding
dojo.
Happy you are doing this.
Do you need help from @codecop in facilitating?


David Leitner <notifications@github.com> schrieb am Mo., 25. Feb. 2019,
22:05:

> I wrote a couple of emails and also shared it on twitter:
> https://twitter.com/duffleit/status/1100139478113501185 - should not be
> choked off by a missing venue! :)

**Comment by caichinger** [comment]
Thank you @mlem for providing a venue! Let's see if I need help, still have to make up my mind about the topic.

Just to make sure there are no misunderstandings, I will do the dojo in **April** - there have been no affirmative responses for February so far.

**Comment by caichinger** [comment]
I am currently in touch with @mlem for a dojo to take place on one of the following dates in April 

- Wedneyday, 3. (may almost count as a March dojo as well ;)
- Thursday, 4.
- Monday, 8.
- Monday, 15. 

if some you already know that one of these dates is a bad idea, please let me know.

**Comment by caichinger** [comment]
**Monday, 15.04.2019** is it. @mlem will host us at willhaben.at, thank you!

**Comment by codecop** [comment]
I created the SWK event, Doodle and sent email to all SWK members.

**Comment by dertseha** [comment]
I negotiated a Coding Dojo at Zühlke on the 12th of June, with me as facilitator.

**Comment by xbojch** [comment]
I'd like to run a Coding Dojo in July (week July 22nd-26th).
Any preference on the day of the week?

**Comment by dertseha** [comment]
I don't think that it is too close to the coderetreat - the two formats offer different options for interested people.
No preferences for a day from my side :) (although, I wouldn't be able to join on 24th)

**Comment by codecop** [comment]
@xbojch could you please announce the dojo in the Softwerkskammer platform already? People asked me if there will be a dojo in July...

**Comment by xbojch** [comment]
Yes, I have a date fixed already. Will prepare the announcement today.

Von meinem iPhone gesendet

**Comment by xbojch** [comment]
Prepared the announcements. Please make some noise.

https://www.softwerkskammer.org/activities/CodingDojoVie20190725
https://doodle.com/poll/5nbnpm6kbevezqcc

**Comment by dertseha** [comment]
Tweet is out: https://twitter.com/swkWien/status/1147437274268917760

**Comment by codecop** [comment]
Hi organisers. How about a coding dojo in October to shape up for GDCR ;-) Who is up to that? Maybe @mlem or @gregorriegler ? #theDojoMustLiveOn

**Comment by gregorriegler** [comment]
Sure @codecop ,
You want to co-host one with me at Oct, 30th 17:00-19:30

**Comment by codecop** [comment]
Possible for me. Why not earlier in Oct? Like 14th or 16th?

**Comment by gregorriegler** [comment]
16th is ok for me. 17:00-19:30 then. i will quickly book the room

**Comment by codecop** [comment]
Affirmative. Calender blocked

**Comment by gregorriegler** [comment]
The upcoming Coding Dojo for Oct, 16th is setup.
https://www.softwerkskammer.org/activities/CodingDojoVie20191016

**Comment by mlem** [comment]
Cool, thanks @Gregor Riegler and @codecop

**Comment by dertseha** [comment]
@gregorriegler which repo is going to be used? I am asking because I might find time to add a Go variant.

**Comment by gregorriegler** [comment]
@dertseha 
i would use the kata from our retreat https://github.com/emilybache/Theatrical-Players-Refactoring-Kata
i think its brilliant as you first have to solve the split looping.

**Comment by codecop** [comment]
@dertseha all solutions use Approval testing frameworks for test coverage. Is there an Approvals for Go?

**Comment by dertseha** [comment]
A quick search brought up this: https://github.com/iafan/agenda
Although I hardly see the benefit for adding a framework for one test, it seems this is what the repo wants.

**Comment by dertseha** [comment]
All right. Trying to make sense of all of this, I am already more confused.

According to the original page (https://approvaltests.com/), the idea is to compare "complex" objects, yet all it does, apparently, is to compare text from a file stored on disk, which follows the name of the test. After all, the kata compares the complete text output of the receipt.

The "agenda" library that I linked makes a little more sense, yet differs in the approach: It allows to run N tests, with N defined by input files. For each test, it reads one input file, that the test code then can (structurally) decode however it wants (-> input data). The test then processes the input data and provides an arbitrary byte array as the result (intent: structured, like input data). The test framework either stores the file or complains if content differs. If so, then you can run your own diff tool to compare.

I assume the intent was to have a data-driven test in the kata, because structure data per scenario (plays, performances), could be stored as input files. Adding a new test requires to provide a new input file and an expected output file. I'll add this then.
If that's not intended, then it's way easier to just read a file named after the test and do an assert.Equal() with the result string - because this is apparently what the (Java) test in this kata does.

**Comment by dertseha** [comment]
....oookey. As it turns out, the library is broken due to not updated dependencies.
I'll do the simple approach for now and perhaps have a look at upgrading the test framework.

**Comment by dertseha** [comment]
OK, coderetreat is done for November. 
Anyone up for a coding dojo in December?

**Comment by dertseha** [comment]
As I've now pitched an internal coding dojo at Z, it might be that I can arrange a co-operation.
If so, we would be able to run a public one on 16th of December. slight change from normal: would be from 5pm to 7pm .

**Comment by caichinger** [comment]
If @dertseha's effort does not work out, I could play facilitator given that someone provides a venue. Possible dates from my side: 16.12. and 18.12.

**Comment by codecop** [comment]
@dertseha how are things with the dojo? will you announce it soon?

**Comment by dertseha** [comment]
Since last Monday didn't work out at Z, I'm retrying next week on 11th. It seems, Monday is not a good day to hold a retreat.
I'd like to hold out for combining Vienna for the first time to get a better hold on internal people first.

**Comment by dertseha** [comment]
2019 is done. Thank you everyone for helping!
2020 is tracked in #53
