### ISSUE TITLE
Software Craftsmanship (Mini)Track at Linuxwochen Wien

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#49]
Beginning of May 2019, [Linuxwochen Wien](https://linuxwochen.at/) (LWW) will take place.
LWW is a free, community-organized conference and considers itself as an umbrella event for *anything* related to open source/tech/software in general. The atmosphere is very relaxed, the event takes place from Thursday (2019-05-02) to Saturday (2019-05-04).
In the past, I have collaborated with the organizers on various occations*.

If there is interest, it would undoubtedly be possible to set up a **Software Craftsmanship (Mini)Track**. Hence there would be a room as well as a time window dedicated to SWK-related topics.
In my experience, talks/events can be a good opportunity to focus on specific topics, work through some content and lay the groundwork for discussions.

@swkWien/organiser and @swkWien/friends what do you think?

---

*) Linuxwochen Wien have hosted the Austrian Python conference, [PyDays Vienna](https://www.pydays.at/), as an independent event within LWW in 2017, 2018 and will do so again in 2019. I am initiator/chairperson of PyDays Vienna.

Relates to #27 #39

**Comment by paulroho** [comment]
Claus, I really like that idea!
What would it take to get that going?

**Comment by caichinger** [comment]
> Claus, I really like that idea!

Glad to hear that!

> What would it take to get that going?

A commitment that *something* will take place in which case I would get in touch with LWW to tell them we are working on this *something* and ask for their support. 
- Minimum version: 3 talks submitted by us and we ask LWW to schedule them in a row.
- Maximum version: announcements about a dedicated Software Craftsmanship track at LWW; talks & workshops submitted by whoever feels interested.
- Real version: anything in between the two extremes.

We are indeed rather flexible; LWW provides time and space and is happy if there are contributions. There is no immediate time pressure but we should make up our mind until the end of January.

**Comment by codecop** [comment]
Hard choices then: Python Workshop or TDD/Clean Code Workshop ;-)

**Comment by caichinger** [comment]
*pinging* here as CfP closes on Monday. Just in case :-)

**Comment by paulroho** [comment]
@caichinger thanks for the head up. I have to confess, that currently I have no resources whatsoever for this.
