### ISSUE TITLE
Coderetreat on November 15th AND 16th (GDCR19) 

### ISSUE THREAD

**Issue by codecop** [swkWien/sessions#50]
This year GDCR is scheduled for two days because it is 10th anniversary. I plan to have CR on both days. I had discussion with potential guest facilitators and it looks promising that we could have different guests on Friday and Saturday. Which would be awesome.

I need hosting companies and someone helping with the event setup, registration, etc. Who is up to that? As we have two CRs, we can settle for smaller groups, at least on Friday. Further I need 300-500 travel cost for each guest from a sponsor please.

@swkWien/organiser @swkWien/friends please help!

**Comment by dertseha** [comment]
Two in a row, this will be fun to handle...
Right now I have some things to clarify, I will come back to this in a few days (weeks) on how much I can contribute.

**Comment by caichinger** [comment]
> I need [...] someone helping with the event setup, registration, etc. Who is up to that? 

If I can contribute, you can count me in.

**Comment by mlem** [comment]
I've asked at my company.
There are some things I need to clarify.

- how many people will participate per day?
- Who is the audience for this retreat? People from Vienna?
- How many guest-facilitators will be needed?

**Comment by codecop** [comment]
@mlem 

* number of people are limited by host. max would be 40, last years we had around 30something. Friday I would expect less people, let's say 20.
* Audience is people from Vienna. There are guests from time to time (from Graz or Bratislava) but usually Vienna.
* There will be a different guest facilitator for each day. Different days - different hosts. Paul/Techtalk are maybe hosting, also Christian could make his company hosting.

If we have more sponsors than two, we can split the sponsoring of room/food and guest facilitator.

Sponsor can talk 5 minutes in beginning and can distribute job offers during the day/walls etc. Will also be listed on registration and all PR activities.

**Comment by caichinger** [comment]
I just want to reiterate that you can reach out to me if there is anything (apart from organizing a venue) I can help you with (small, big, abstract, specific, yet unknown - whatever). Please do not hesitate.

In any case thank you for getting this rolling!

**Comment by goerge** [comment]
Klaus Unger just proposed HTL Spengergasse as a venue for Saturday. @codecop interested?

**Comment by codecop** [comment]
@goerge I am concerned if htl is a good venue for global day. I propose a regular cr instead to try first, e.g. the September one to be there. Also I can run one on any Friday for the school if that helps.

**Comment by dertseha** [comment]
How sure are the hosting candidates so far (Willhaben, TechTalk)? Shall I ask at Zühlke as well?

**Comment by paulroho** [comment]
TechTalk has confirmed to be very happy hosting one day this year again.

**Comment by dertseha** [comment]
OK, is it now a race of who does the second day, or is this already finalized? @mlem  ?

**Comment by dertseha** [comment]
Also "has confirmed to be very happy hosting" does not imply "has confirmed to BE hosting" - just to be sure :)

**Comment by paulroho** [comment]
We would probably not be hosting in case there are be concurrent offers in Vienna. So we *offer* to host again. But we won't compete in case some else in Vienna does the event on the same day. The pool of potential participants is not endless.

**Comment by dertseha** [comment]
OK, thank you for clarifying. I'll then ask whether a company new to coderetreats wants to.

**Comment by codecop** [comment]
Thank you @paulroho . I assume hosting also means sponsoring the invited facilitator like the previous years? Also because the venue is good, I would propose TechTalk getting the probably larger Saturday event.
@dertseha thank you your employer. Willhaben has not confirmed yet. We also need around 500 EUR travel cost for invited facilitator (different person for each day - 2 facilitators already agreed to come).

**Comment by paulroho** [comment]
Yes, our commitment goes as in the previous years.
BTW, pinging @raoulholzer and @danielthecoder as co-organizer at TechTalk to join the conversation.

**Comment by dertseha** [comment]
Is the host fixed already for Saturday, @paulroho ? Because today I received word that Z is "preferring" to host on Saturday. Whether they would be open to change I couldn't read from the mail, so I assume they want to host on Saturday.

**Comment by codecop** [comment]
Techtalk onis fixed. Organisation and facilitator mails etc already started.

Thank you for supporting/ trying to get it going

**Comment by dertseha** [comment]
All right, today I received confirmation that Z wants to host on Friday 15th.
They'll also cover lunch. Whether it is catering or delivery will be decided based on registrations.

**Comment by dertseha** [comment]
As for facilitators: Do we have some numbers what they would cost?
I am considering to help out on that - to a certain limit.

**Comment by codecop** [comment]
@dertseha awesome thank you. I would expect 300 to 500 EUR for flight and one night in hotel. First let's see if @mlem can help? Else we can collect and split the cost.

**Comment by mlem** [comment]
Does that mean no hosting for willhaben, but a mention as sponsor?
I can see about that

Peter Kofler <notifications@github.com> schrieb am Di., 6. Aug. 2019, 09:36:

**Comment by mlem** [comment]
But you have to wait a bit, I'm on holidays

mlem <beo.xtc@gmail.com> schrieb am Do., 8. Aug. 2019, 20:51:

**Comment by dertseha** [comment]
Events are registered and published:
SWK:
day 1: https://www.softwerkskammer.org/activities/gdcr19-vienna-1
day 2: https://www.softwerkskammer.org/activities/gdcr19-vienna-2
(including their Eventbrite events)

Twitter: https://twitter.com/swkWien/status/1174202804262621189

**Comment by codecop** [comment]
Now we need participants. @swkWien/organiser @swkWien/friends how could we promote the event? I like the energy of large crowd plus we have two events to fill up ;-)

**Comment by caichinger** [comment]
For my part, I can easily promote the event in the larger Python community as well as in some diversity in tech groups.

I will happily do so but before sending out the notifications - does everybody *within* SWK already have a ticket?

I suggest we define a deadline and then make the announcements in a coordinated fashion.
Next Monday morning, i.e. 2019-10-01 08:00 onwards sounds good to me.

How about that?

**Comment by rolger** [comment]
I started already promoting it in my company and on Twitter.

It's a shame but I can't attend because I'm on vacation on this weekend.

Roland

caichinger <notifications@github.com> schrieb am Do., 26. Sep. 2019, 09:37:

**Comment by caichinger** [comment]
I have just reached out to a number of different communities, a few other announcements will follow in the coming days.

Let's see.

**Comment by codecop** [comment]
@caichinger thank you. do you have contact with Jackie et al communities? I reached out to two of them but I do not know them good enough I guess...

**Comment by caichinger** [comment]
Yes, I have written Jackie as well as others and suggested they also forward the invitation in their respective groups.

On 16 October 2019 22:30:27 CEST, Peter Kofler <notifications@github.com> wrote:
>@caichinger thank you. do you have contact with Jackie et al
>communities? I reached out to two of them but I do not know them good
>enough I guess...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/swkWien/sessions/issues/50#issuecomment-542878521

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dertseha** [comment]
Thank you all for making it happen!
