### ISSUE TITLE
Coding Dojos 2020

### ISSUE THREAD

**Issue by dertseha** [swkWien/sessions#53]
The Coding Dojo is a two hour practice session. It is run during the week in the evening after work. It is held on different days and announced one week in advance approx. every second month.

Month, Who @ Where (when) [- what]
Jan, @dertseha @ Zühlke (2020-01-22) - Bank OCR
Feb, @dertseha @ Frequentis (2020-02-19) - legacy (trivia)
Mar, @dertseha @ Zühlke (2020-03-04) - TDD basics (string calc)
~~Mar, @xbojch @ LRT (2020-03-16) - tbd~~ (cancelled due to Covid)
~~May, @dertseha @ Zühlke online (2020-05-21) - TDD basics~~ (cancelled due to lack of participation)
June, @dertseha @ Zühlke online (2020-06-29) - TDD basics
July, @dertseha @ Zühlke online (2020-07-13) - TDD basics
Aug
Sep
Oct
Nov
Dec

**Comment by dertseha** [comment]
I didn't manage to run last December, so, hopes are up for me to get something for January going.

**Comment by dertseha** [comment]
And we have a date: http://www.softwerkskammer.org/activities/CodingDojoVie20200122

**Comment by dertseha** [comment]
I've secured (well, I was asked) to run a Dojo at Frequentis in February. I'll create the entry beginning of February, as I am toying with the idea to add yet another at Zühlke...

**Comment by dertseha** [comment]
Next dojo set up:
* https://www.softwerkskammer.org/activities/CodingDojoVie20200219
* https://twitter.com/swkWien/status/1226970084972822541

**Comment by dertseha** [comment]
Next dojo set up:
* https://www.softwerkskammer.org/activities/CodingDojoVie20200304
* https://twitter.com/swkWien/status/1231990628759867392

@xbojch I see you are planning something on the 16th of March - perfect. I am pushing towards two-week intervals (implicitly, since I am going for two-week dojo intervals at Z, and whenever there's room, I'll make it a public one)

**Comment by xbojch** [comment]
Sounds good @dertseha. I'll wait with the announcement until 2020-03-04 to not mix the two dates.

**Comment by xbojch** [comment]
Our company is in preventive self isolation - working from home. Organizing a coding dojo at this time would defeat this purpose. Since there was a coding dojo already in March, I'll skip organizing the one planned for March 16th.

**Comment by dertseha** [comment]
All good, thank you, @xbojch

**Comment by codecop** [comment]
@xbojch how about organising a remote coding dojo in April?

**Comment by paulroho** [comment]
I played around with property-based testing in Javascript (https://github.com/paulroho/DrawingThePyramid). As we already used the example for an internal Dojo (branch DojoStart), I could offer to facilitate a similar public Dojo ([basic instructions](https://github.com/paulroho/DrawingThePyramid#Using-in-a-Coding-Dojo)).
I am pretty excited about the topic!

![image](https://user-images.githubusercontent.com/721933/79386851-07f5d100-7f6b-11ea-8d25-5eadb4294c1d.png)

**Comment by codecop** [comment]
Welcome back Paul. Yes go ahead please

**Comment by paulroho** [comment]
What about April 29th?

**Comment by xbojch** [comment]
Maybe I can organize one dojo online in May or June. Can’t really make it at my current flat. But we’re moving in May.

Von meinem iPhone gesendet

**Comment by dertseha** [comment]
Is anyone able to log in to softwerkskammer.org using GitHub as the provider? For me it fails with 500 error.
I'd like to register a new dojo.

**Comment by dertseha** [comment]
Thank you, @codecop  - the event for June is registered:
SWK: https://www.softwerkskammer.org/activities/CodingDojoVie20200629
Twitter: https://twitter.com/swkWien/status/1275295072733597696

**Comment by dertseha** [comment]
And the first one for July:
SWK: https://www.softwerkskammer.org/activities/CodingDojoVie20200713
Twitter: https://twitter.com/swkWien/status/1281095806565724168
