### ISSUE TITLE
Mob-Programming on Open Source Software Meetup

### ISSUE THREAD

**Issue by haraldreingruber** [swkWien/sessions#54]
Hi,

I am thinking about starting a Mob-Programming Meetup in the next couple of weeks and I would like to share the idea with you and ask if some of you would be interested in organizing it as a team?
Probably we will also need people who could imagine facilitating a mob during the meetups => if you are not sure if you want to join the orga team but could imagine taking over the facilitator role every once in a while it would be really helpful as well.

One of my ideas is next to practicing mob-programming (which is the main goal), we could work on Open Source Software. Maybe in the end we are able to submit a PR, if not we had a good time practicing Mob-Programming.

Looking forward to hearing your ideas!

P.S. I guess we have to start it as a Remote Meetup, but once we are able to do it on-site again I would prefer that (or alternate).

**Comment by codecop** [comment]
Closing this. The Meetup exists and Mobretreat is happening. See https://www.meetup.com/de-DE/Mob-Programming-on-Open-Source-Software/events/271306806/
