### ISSUE TITLE
GDCR20: Program, Facilitators

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#57]
The program is still being discussed and depends on the format of the retreat.
In particular it depends on the participants, with more newcomers requiring a more prepared program.

#55 listed the following ideas and considerations.

Current options include:
- Ad hoc code retreat, we develop the program on the fly (works well for small groups, works well for more experienced participants; may not be feasible otherwise)
- Planned sessions where each session was prepared by a facilitator (requires more preparation but works for larger groups and newcomers as well as experienced participants alike)

---

## Scenario: ad hoc

*not much to discuss here*

## Scenario: planned

There is a facilitator per session, these prepare the goal/objective of the session and eventually provide guidance to the participants.

Docs:
- [Schedule](https://docs.google.com/spreadsheets/d/10u99JprRmugilQP6mtnzM61LW1kIRay6YEcx7I8ertU/edit?usp=sharing)
- [Slides](https://docs.google.com/presentation/d/1a5g_I00qTFCQvblCVSl1-EdFVB1SKoRX4eKWuB9Go0I/edit?usp=sharing)

### Schedule

![image](https://user-images.githubusercontent.com/16005912/97534615-963b1d00-19ba-11eb-8bcd-e93fc423061d.png)
![image](https://user-images.githubusercontent.com/16005912/98025840-83857580-1e0a-11eb-8e7b-280d56fa155a.png)

### Program

*moved to this [doc](https://docs.google.com/document/d/1y0uqy26ZkWwlfJ-RtLB680mvzL_yGFbk59ab6WDvqWU/edit?usp=sharing)*

**Comment by caichinger** [comment]
@swkWien/organiser you want to facilitate one of the sessions? Maybe @dertseha or @gregorriegler? Assuming there are newcomers, there should be at most two different problems we work on (ideally only 1); each session focusing on a different aspect.

**Comment by caichinger** [comment]
@haraldreingruber you want to facilitate a final mob/team programming session to conclude the day?

**Comment by gregorriegler** [comment]
Thank you @caichinger for the proactive coordination and inclusion. Let's see if more people register for the event to make a proper facilitation necessary. Of course i'd be happy to help. And i'd also love one or two mob sessions with haralds setup.

**Comment by haraldreingruber** [comment]
Yeah, it would be great to offer 2 rounds of mobbing, so we could compare 2 different mob-programming styles.
Using the cloud desktop setup might be better, as this way the hand over is faster. But if there are more than 2 mobs, I think using Cyberdojo would be better.

**Comment by gregorriegler** [comment]
As it seems like more people are registering i would like to offer to facilitate one or two sessions. Thinking of a Strong Style Pairing session, and maybe one more for Tell dont Ask.

@haraldreingruber about your mob session: how many people would you consider for a mob ~6 and split up? or would you make just one big mob?

**Comment by haraldreingruber** [comment]
@gregorriegler Yeah, I think 6 would be already max. I would suggest a 3 minutes mob-timer, and it would be great if everybody will be able to drive at least twice, plus some additional time as often the timer won't be re-started immediately. Each session would be 45min? 2x6x3min is 36min, then we would have ~10min for intro and some time buffer.

If you facilitate Strong Style pairing, it would have a nice side-effect of not being completely new when starting with strong-style mob-programming. We could have a collaboration pattern focus in the afternoon :)

**Comment by caichinger** [comment]
The issue description is now updated, please take a look.

We need a kata (or two) for the day (otherwise participants spend too much time understanding the problem). If you have no other suggestions, we will use **Game of Life**.
It would be nice to have an overall topic, like a story arc, but that is not mandatory.

For each session we need a
- Name
- Topic/Objective
- Facilitator

@haraldreingruber, @gregorriegler (and @dertseha and @codecop if you want/can): Please amend the issue description to include your suggestions. I suggest to have the more programmer-behavior oriented topics (like pairing style and pen and paper (but not team/mob)) at the beginning.  

Likely, not everyone will participate in the team/mob programming (nor are the participants required to), hence we need a topic/objective for the last two sessions as well.

I have included a shared slide deck as well, it is still empty though.

**Comment by haraldreingruber** [comment]
Unfortunately, I can't amend the description. Can you add me to the team?

**Comment by caichinger** [comment]
> Unfortunately, I can't amend the description. Can you add me to the team @caichinger?

Sorry, don't have the privileges.

I moved the section to this [doc](https://docs.google.com/document/d/1y0uqy26ZkWwlfJ-RtLB680mvzL_yGFbk59ab6WDvqWU/edit?usp=sharing). You can make your amendments there.

**Comment by caichinger** [comment]
We have agreed on a program. The details are outlined [here](https://docs.google.com/document/d/1y0uqy26ZkWwlfJ-RtLB680mvzL_yGFbk59ab6WDvqWU/edit?usp=sharing).
@dertseha and @codecop please comment.

- Kata: Game of Life
- Session 1-2: Focus on tests and collaboration
- Session 3-4: Focus on design/dev aspects (tell don't ask; *always working solution*-constraint)
- Session 5-6: Team programming as primary option; those who do not want to participate, pair on their own, we provide ideas

**Comment by codecop** [comment]
Do you need material for the intro? Material to introduce Game of Life?

**Comment by caichinger** [comment]
> Do you need material for the intro? Material to introduce Game of Life?

Yes please, whatever you have. (Thank you for asking before I do ;)

**Comment by codecop** [comment]
https://de2.slideshare.net/pkofler/global-day-of-code-retreat-2013
https://de2.slideshare.net/pkofler/gdcr15-in-las-palmas-gran-canaria
https://de2.slideshare.net/pkofler/code-retreat-venice-2016
with evolution 2013-2016 ;-)

**Comment by codecop** [comment]
Plan in doc looks good to me. good to go

**Comment by caichinger** [comment]
Update schedule to account for longer intro

![image](https://user-images.githubusercontent.com/16005912/98025816-7bc5d100-1e0a-11eb-91b5-f1a07670b715.png)

For more details see below

[WIP: Slides including intro](https://docs.google.com/presentation/d/1a5g_I00qTFCQvblCVSl1-EdFVB1SKoRX4eKWuB9Go0I/edit?usp=sharing)

[WIP: Working doc including program](https://docs.google.com/document/d/1Vy79tH-ZhY4EZSaiOoAScReCWtLBJX2fnywf6Odhvc4/edit?usp=sharing)

Final discussion on Thursday. We do not need this issue any longer.
