### ISSUE TITLE
GDCR20: Event Announcements

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#58]
@swkWien/friends  @swkWien/organiser 

Help us spread the word of this years global day of coderetreat GDCR Vienna 2020!

Important facts:
- Date and time: 2020-11-07 09:00-17:00 (arrival 08:45)
- Event page: https://www.softwerkskammer.org/activities/gdcr20-vienna
- Registration: http://tiny.cc/GDCRVienna (required for setup)

To simplify matters, below is a short text you can use to invite your friends and colleagues.

Thank you!

---

### English

Dear all,

The global day of coderetreat is approaching and I want to invite you to this year’s event.

A coderetreat is all about software craftsmanship. It is a day of deliberate learning and practice (and having fun).

Here is everything you need to know:
    • When? 2020-11-07 09:00-17:00 (Ankunft 08:45)
    • Where? Online
    • How and what?  All details and registrations: https://www.softwerkskammer.org/activities/gdcr20-vienna
    • How much? It's free

Looking forward to seeing you there!

Cheers,
\<NAME\>

### German

Liebe Leute!

Der Global Day of Code Retreat steht vor der Tür und ich möchte euch hiermit sehr herzlich zum diesjährigen Event einladen.

Bei einem Coderetreat geht es um Software Craftsmanship. Das ist ein Tag, an dem wir uns bewusst Zeit nehmen zu Lernen und zu Üben (und Spaß zu haben).

Hier ist, was du wissen musst:
    • Wann? 2020-11-07 09:00-17:00
    • Wo? Online
    • Was und wie? Alle Infos und Anmeldung hier: https://www.softwerkskammer.org/activities/gdcr20-vienna
    • Wieviel? Kostenlos

Würde mich freuen, dich dort zu sehen!

Liebe Grüße,
\<NAME\>

**Comment by caichinger** [comment]
Update:
- At the moment 9 people are enlisted (not yet including all fellow organizers ;)
- **If you have not yet advertised the event at work or invited your friends/colleagues, please do so asap to help us plan. Thank you.**
- I guess we can expect more people to register in the run up of the event. Not sure about no shows though.

**Comment by codecop** [comment]
Should I send a reminder mail from SWK mailing service? Not sure how many mails have been sent

**Comment by caichinger** [comment]
> Should I send a reminder mail from SWK mailing service? Not sure how many mails have been sent

If you usually send out a reminder, yes, please do that. Thank you.

I have not sent a mail.

The only mail I plan to send is the one to the participants (according to our poll) which goes out on Thursday.

**Comment by codecop** [comment]
done

**Comment by caichinger** [comment]
No further announcements planned.

How to document sent out to participants yesterday. Participants who signed up later will be informed during the day individually.

How to: https://docs.google.com/document/d/1vPSi6bB5lc3aPTSSXjl48vmXNKN9QPZbPTzi18Az3T4/edit?usp=sharing

As of now, 23 people registered, 6 of whom are newcomer.

**Comment by gregorriegler** [comment]
kann ich irgendwo die anmeldungen sehen?

**Comment by codecop** [comment]
habs dir freigegeben. nichts löschen!

**Comment by caichinger** [comment]
FIY Bernhard cancelled, I removed his response from the poll; just in case you are wondering.
