### ISSUE TITLE
Future of softwerkskammer.org

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#60]
Dear @all,

I guess most of you have received the mail "Nachricht von der Softwerkskammer" (see copy below). I open this issue so we can discuss if/how we, as swkWien, want to react to the therein outlined problems - and maybe more importantly the implications for our activities.

---

For completeness, the abovementioned mail from the softwerkskammer-maintainers:

> Liebe Softwerkskammer-Leute!

> Heute schreiben wir Euch leider eine Mail, die uns wirklich sehr, sehr schwerfällt.

> Nach 10 Jahren Softwerkskammer schauen wir zurück und müssen feststellen, dass das Konzept, was wir uns ursprünglich mal erträumt hatten - alle Interessierten unter einem gemeinsamen Dach zusammenzuführen, wo wir einen gemeinsamen privaten Raum für uns alle haben und uns gegenseitig sehen können, zum Beispiel im gemeinsamen Kalender aller Gruppen, und diesen Raum mit allen gemeinsam zu bauen und mit Leben zu füllen - dass dieser Traum nicht aufgegangen ist.

> Dafür gibt es sicher viele Gründe. Ein gewichtiger externer Grund ist sicherlich die Omnipräsenz von Meetup zumindest in den Großstädten. Viele Gruppen sind schon zu Meetup gewechselt oder fahren hier zweigleisig, um eine bessere Sichtbarkeit zu erzielen, und Meetup lässt sich trotz aller Versuche und Ideen leider nicht sauber in die Softwerkskammer-Plattform integrieren.

> Auch die zunehmenden Schwierigkeiten beim Mailversand an die Mitglieder sind sehr aufreibend. Immer wieder bekommen wir Rückläufer, die von irgendwelchen Spamfiltern etc. zurückgewiesen wurden. Natürlich kann man versuchen, die Softwerkskammer-Domain whitelisten zu lassen, aber es ist eine Sisyphus-Arbeit.

> Außerdem verstößt es inzwischen eigentlich auch gegen die Hausregeln unseres Hosters Uberspace, Mails an viele Personen gleichzeitig zu verschicken, und in jüngster Zeit wurde auch die Mailinglisten-Verwaltungssoftware, die wir lange genutzt haben, von den Servern entfernt.

> All diese Probleme lassen sich vielleicht irgendwie lösen, aber damit kommen wir zum gewichtigsten aller Gründe: Aktuell schreiben wir die Software für die Softwerkskammer-Plattform selbst. Und das unentgeltlich, in unserer Freizeit, neben der täglichen Arbeit und was noch alles zum Leben gehört. Seit 10 Jahren. Wir, das sind übrigens im Wesentlichen zwei Personen: Andreas Leidig und ich. 

> Und zumindest ich, Nicole, für meinen Teil muss sagen, dass ich keinerlei Motivation mehr verspüre, mich mit dieser Software weiter zu beschäftigen. Als wir damit anfingen, dachten wir, dass es doch nicht so schwer sein kann, in einer Gruppe wie der Softwerkskammer ausreichend Interessierte zu finden, mit denen sich ein solches Projekt stemmen lässt. Wir haben uns ja schließlich alle das Erstellen qualitativ hochwertiger Software auf die Fahnen geschrieben. Aber es hat im Wesentlichen nicht funktioniert. Damit möchte ich keineswegs das Engagement und die Beteiligung derjenigen kleinreden, die uns unterstützt haben, sei es durch Coding, Design, Bugreports oder einfach gute Ideen. Ich habe mächtig viel gelernt in dieser ganzen Zeit, und ich möchte sie nicht missen. Vielen Dank an Euch alle, die Ihr dabei wart!

> Leider müssen wir uns aber auch eingestehen, dass wir es nicht geschafft haben, eine solche Gruppe dauerhaft zu etablieren - sicher haben wir viele Fehler gemacht, waren nicht einladend genug, nicht freundlich genug, nicht unterstützend genug. Und Ihr habt ja auch alle genug um die Ohren. Das ist schon ok. Aber heute ist der Tag gekommen, an denen wir diesen Realitäten entgegentreten müssen. 

> Dazu haben wir zwei verschiedene Sichtweisen: In meinen, Nicoles, Augen hat die Softwerkskammer mit ihrer Standalone-Plattform keine Zukunft mehr in der Form wie sie ursprünglich angedacht war: Als selbstgestaltete Alternative und damit als Gegenentwurf zu kommerziellen Plattformen, als geschützter Rückzugsraum. Ich glaube, dass der Zeitgeist einfach ein anderer geworden ist und solche Modelle nicht mehr gebraucht werden. Von daher möchte ich meine Arbeit am Projekt niederlegen, da mir die Perspektive und mittlerweile auch die Kraft fehlt.

> Andreas sieht das nicht so kritisch und hat grundsätzlich kein Problem damit, die Softwarepflege weiter zu übernehmen. Neue Features wird er allerdings keine mehr im Alleingang entwickeln. Darüber hinaus ist er nicht gewillt, sich um den Betrieb der Software, den bisher hauptsächlich ich übernommen habe, zu kümmern.

> Wir beide sehen jetzt also folgende Zukunftsperspektiven:

> 1. Es findet sich unter Euch jemand, der oder die meinen Part übernimmt. Das bedeutet zunächst mal das Finden eines anderen Hosters, bei dem der Massenmailversand hoffentlich weniger Probleme bereitet, und das Betreiben der Software dort. Andreas unterstützt weiterhin softwareseitig durch Aktualisierungen und Bugfixes. Melde Dich umgehend, wenn Du Interesse hast, bei mir oder bei Andreas. Deadline: 12. April. Sollte bis dahin niemand Interesse anmelden, ziehen wir Alternative 2.

> 2. Es findet sich niemand. Dann reduziert Nicole die bestehende Webpräsenz auf ein statisches Minimum. Die Landingpage mit der Karte bleibt erhalten und jede Regionalgruppe, die dies möchte, kann auf dieser Karte mit einem Link ihrer Wahl vertreten sein. Dieser Link kann zu Eurer Regionalpräsenz weiterleiten - sei dies Eure Meetup-Gruppe, Eure eigene Gruppen-Webseite oder auch nur eine Mailadresse. Damit gibt es weiterhin einen zentralen Softwerkskammer-Einstiegspunkt, von dem aus man alle Gruppen finden kann. Wir hoffen, dass auf diese Weise der ursprüngliche Softwerkskammer-Gedanke noch weiterleben kann. Die Umstellung würde zum 30.6.2021 erfolgen.

> Sobald wir wissen, welche Alternative realisiert wird, informieren wir nochmals.

> Viele Grüße,
> Nicole und Andreas

**Comment by dertseha** [comment]
I received that mail a few days ago as well.
So far I'm optimistically reserved about the situation. For one, because perhaps someone might step up to maintain the site, and second, we are not *that much* relying on it.
If indeed the site no longer allows setting up events with registrations, then I'd think about an alternative. I did have a brief look at meetup, yet I'm very (very!) reluctant to use that money sink. I'd go for a cheaper alternative (possibly one made-in-austria).

**Comment by caichinger** [comment]
Let's see what they write in their update which is announced for 12th of April.

---

> I'd go for a cheaper alternative (possibly one made-in-austria).

@dertseha do you already have something in mind? Just asking out of curiosity.

**Comment by dertseha** [comment]
> > I'd go for a cheaper alternative (possibly one made-in-austria).
> 
> @dertseha do you already have something in mind? Just asking out of curiosity.

No. I made a quick cursory search and found a few posts comparing other platforms, which I haven't looked at. It's something I'd do when it's needed. I do not know of an Austrian resource, yet would be happy to boost their usage.

**Comment by caichinger** [comment]
Softwerkskammer is still up and running with no updates from the organizers so far. I will close this issue and reopen in case of need.
