### ISSUE TITLE
Coderetreat 2021-05-15

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#61]
We have a scheduled Coderetreat (#59) for coming Saturday and there is not yet an event at https://www.softwerkskammer.org/activities/upcoming.

I am happy to create an event but I do not want to interfere if somebody else is already doing that. To be honest, I do not know if there is an "official" procedure.

Unfortunately, I cannot recollect the last CR. Hence if there were any decisions that influence the upcoming one, please let me know.

TODO:
1. [ ] Agree on end time (I believe we discussed the CR could be shorter?)
1. [ ] Copy old trello board (?) and insert link into event description (?) (I have a board called Coderetreat Vienna 2021-01-16)
1. [ ] Create event (see below)

---

*Eventbeschreibung Softwerkskammer.org*

# Small Coderetreat Vienna (online)

2021-05-15 (09:00-??:00)

Zero Overhead Coderetreat: remote, small group, no facilitator, no sponsor, BYOT (Bring your own Topic).

For participation, please register via Softwerkskammer. Entry button is at the bottom of this page. Yes, you need a Softwerkskammer login for this. This is necessary in order to receive a contact via which to tell you the link to join.

If you want to bring your own topic already now, go to **\<LINK-TO-TRELLO-BOARD\>**.

This meeting is online, using https://gather.town/. The contact information will be sent to you about 30 minutes prior the start.

Gathering time is 08:45-09:00.
We start at 09:00.

Twitter: @swkWien
Hosting: Gather.Town
Facilitator: You
Meta: https://swkwien.github.io/

**Comment by caichinger** [comment]
@gregorriegler @codecop pinging you about the upcoming CR, please see the description of the issue. Thx!

**Comment by codecop** [comment]
@caichinger I did not plan anything because I am not available this weekend and also @gregorriegler did not talk about it. So I let it be and accepted the date to slip by. If you want to go ahead please do. imho it is a bit late to announce it

**Comment by gregorriegler** [comment]
@caichinger @codecop 
I had planned to use the longer weekend for break, and more time for family. That's why I didn't do anything about it this time. But I'm thinking about doing a public zero overhead retreat on Friday in two weeks. 9:00-15:00 sorta.
Is a friday a day where you would be happy or able to join?

**Comment by codecop** [comment]
Friday 28th of may 9-15 sounds good

**Comment by caichinger** [comment]
Thank you for your responses.

We can of course reschedule. Personally, I do not want to drop the CR entirely because I see value in the "rhythm" (better not set a precedent :D).

Not sure about Friday vs. Saturday, i.e. workday vs. weekend, though.

For me Friday (28th) would be fine as well.

@dertseha how about you? I see you added a label, hence I believe you are part of this discussion as well. :)

**Comment by maosmurf** [comment]
@caichinger thank you for the proposal! FWIW, this saturday is too short of a notice for me, too. 28th is great though.
Personally, fridays would be my favorite too, but I’m happy with either day. Code you soon!

**Comment by dertseha** [comment]
I'm with codecop on this one -- apparently schedule didn't match up. I as well didn't realize it's planned state as the Google calendar entry wasn't present.
I also understand the avoidance of a precedent, so a proposed alternative is great. For me it's possible that I could join on a Friday, though I need to double-check with any work meetings.

**Comment by caichinger** [comment]
Seems we have found a good way to keep the May edition - thank you for the quick responses.

Save the date: **Friday, 28.05.2021**

Looking forward to it!

@gregorriegler if you need something, let me know, I am closing this one.

**Comment by gregorriegler** [comment]
I created the Event and a Trello:
https://www.softwerkskammer.org/activities/Coderetreat20210528
Please register for the event
https://trello.com/invite/b/zoDxdxXd/86330c9dc8c6083d6861432d6af0ad16/coderetreat-vienna-2021-05-28
You can already start adding topics

**Comment by dertseha** [comment]
Thank you, Gregor.

I also realized that the 28th is the third day of GopherConEU, so, I won't attend the Coderetreat.
