### ISSUE TITLE
GDCR21: Which day which way?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#63]
@swkWien/organiser der GDCR 2021 steht vor der Türe.

Freitag oder Samstag, online oder doch physisches Treffen?

Bitte um eure Meinung via https://doodle.com/poll/ypwv5pu25eg4xq8b. Die Umfrage gerne an alle Interessierten außerhalb unserer Gruppe weiterleiten, danke.

**Comment by dertseha** [comment]
Servus Claus!
Danke Dir für die Initiative!

**Comment by maosmurf** [comment]
Wie steht ihr zu physichem Treffen mit 1G als Voraussetzung? Am GDCR sitzen doch alle ganztags beisammen.

**Comment by caichinger** [comment]
> Servus Claus!
> Danke Dir für die Initiative!

Gerne! Haben wir aber beim letzten CR gemeinsam besprochen, insofern nicht meine Initiative.

**Comment by caichinger** [comment]
Dank @rolger können wir am Samstag, den 13.11., ein physisches Event bei Nagarro (#64) abhalten. Details folgen.

**Comment by caichinger** [comment]
Weitere Aktivitäten zum GDCR21 in den Issues https://github.com/swkWien/sessions/issues
