### ISSUE TITLE
GDCR21: Mögliche Locations?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#64]
Der aktuelle Stand der [Umfrage](https://doodle.com/poll/ypwv5pu25eg4xq8b) weißt darauf hin, dass es durchaus Interesse an einem physischen Event gibt.

Unabhängig davon ob wir das wirklich machen:

Wer von euch @swkWien/organiser hat Zugang zu einem geeigneten Ort?

Bitte Erkundigen einholen und hier Infos teilen, danke.

Besonders relevante Infos:
- Welche Tage sind möglich? Freitag und/oder Samstag?
- Wieviele Personen erlaubt?

**Comment by rolger** [comment]
Ich habe bei uns in der Firma angefragt, ob wir als Host zur Verfügung stehen. Ich gebe Bescheid wenn ich mehr weiß. 

Ein Thema ist auf jeden Fall, welche Covid Regeln wir festlegen? Unser Büro ist zwar groß, trotzdem könnte es u.a. eine Einschränkung bzgl. der Anzahl der Teilnehmer geben. Ein anderer Gedanke ist, wenn wir es vor Ort durchführen, dann könnte die Auflage sein es am Samstag durchführen zu müssen.

**Comment by rolger** [comment]
Ich habe von unsere GF ein Go bekommen, Nagarro wird den Event hosten. Rahmenbedingung muss ich noch klären.

**Comment by rolger** [comment]
Nagarro würde das Büro für Samstag 13.11. zur Verfügung stellen (Freitag geht nicht). Ah ja, wir sind im 12. Bezirk zu Hause und zwar im EURO Plaza Bürokomplex. Öffentlich ist das Büro mit der S-Bahn und der U6 sehr gut erreichbar. Samstag findet man auch Parkplätze und es sind keine Kurzparkgebühren zu bezahlen.

Es gibt eine Teilnehmerbeschränkung auf maximal 50 Teilnehmer. Das ist zur Zeit auch die Anzahl der Personen, die bei uns ins Büro dürfen. Die Teilnehmer müssen sich vorab registrieren. 3-G wird bei der Ankunft kontrolliert. Die Teilnehmer erhalten dann einen Badge mit dem sie sich in einem Teil unseres Büro frei bewegen dürfen. Falls wir wollen, könnten wir strengere Covid Auflagen definieren.

Wir haben einen großen Raum, wo wir früher Veranstalltungen mit mehr als 100 Personen abgehalten haben. Dieser Raum hat eine Video-Leinwand, falls wir uns mit anderen Veranstaltungen verbinden wollen. Gleich neben diesem Raum stellen wir einige Meetingräume und die Bereiche mit den Desksharing Arbeitsplätzen zur Verfügung. Diese Arbeitsplätze sind in offenen abgetrennten Gruppen mit bis zu 6 Tischen aufgeteilt.

Nagarro wird sich als Host um Verpflegung kümmern. Wir können u.a. die Küche für Kaffee und Tee nützen. 

Ich hoffe, ich habe nichts vergessen. Ich würde mich offiziell um das Hosting kümmern. Was haltet ihr davon? Welche Fragen habt ihr noch im Kopf?

**Comment by codecop** [comment]
@caichinger @gregorriegler @rolger wir sollten so ca. vor dem 11.10 mal online treffen und alles planen wegen Anmeldung usw.

**Comment by caichinger** [comment]
Ja, ein Abstimmungstermin ist bestimmt hilfreich. Kann am Wochenende ausschicken für Abstimmung.

Ich würde damit auch die Entscheidung treffen, dass am Samstag, den 13.11., der GDCR wie oben beschrieben stattfinden wird.
Details TBA aber Save the Date damit fix.

Alle einverstanden?

**Comment by rolger** [comment]
Ja, das klingt gut. Sollen wir einen Doodle Link für einen Termin anlegen? Gibt es präferenzen? Ich bin nächste Woche sehr flexible :-)

**Comment by caichinger** [comment]
Bitte hier um Doodle eure Verfügbarkeiten angeben:

https://doodle.com/poll/xfdyr6hym52ac3gq?utm_source=poll&utm_medium=link

Wenn wir noch mehr Möglichkeiten brauchen, gebt Bescheid.

@dertseha @maosmurf referenziere euch, da ihr euch im anderen Issue auch zu Wort gemeldet habt.

**Comment by caichinger** [comment]
Danke für's Ausfüllen.

Wir machen den Call **heute um 17:00 in Gather Town**.

https://gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo

Wenn jemand von euch @rolger @gregorriegler @codecop heute doch nicht kann, verschieben wir auf 11.10. 18:00.

Ihr bekommt noch ein Mail.
