### ISSUE TITLE
GDCR21: Event Announcements

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#65]
Help us spread the word of this year's global day of coderetreat event in Vienna!

Important facts:
- Date and time: 2021-11-13 09:00-17:00 (arrival 08:45)
- Event page: https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2021-tickets-189806314797

To simplify matters, below is a short text you can use to invite your friends and colleagues.

Thank you!

---

Announcements:
- [X] Create SWK event @codecop ... https://www.softwerkskammer.org/activities/gdcr21-vienna
- [X] Create SWK Mail Gruppe Wien
- [X] Create https://www.coderetreat.org/ event @codecop ... event submitted
- [X] notify Austria channel in Crafters slack
- [X] placed with management at 2 of my clients @codecop 
- [x] SWK Twitter @dertseha ... https://twitter.com/swkWien/status/1450336799004499969 & https://twitter.com/swkWien/status/1457651716762001408
- [x] Python user group @caichinger 
- [x] FH Technikum Wien @ReaSu 

---

### English

Dear all,

The global day of coderetreat is approaching and I want to invite you to this year’s event.

A coderetreat is all about crafting software. Join our community event to practice professional software development, spend a day on deliberate learning and practice (and having fun).

* **Who can join?** Everyone interested in software development
* **What?** This time we focus on ***incremental development***
* **When?** November 13th 2021 9:00 - 17:00
* **Where?** Nagarro GmbH (https://www.nagarro.at), Am Europlatz 2, 1120 Wien (Building: EURO PLAZA 4)
* **How can I join?** Register here https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2021-tickets-189806314797

This is an on-site event with a limited number of participants. 
A **2G+PCR** certificate is required to join. Thus, only vaccinated and recovered persons with a valid PCR test are allowed to participate.
The ticket fee of 10€ will be refunded upon check in at the event.

Looking forward to seeing you there!

Cheers,
\<NAME\>

**Comment by gregorriegler** [comment]
Achtungb, der Link zeigt auf 2020

**Comment by dertseha** [comment]
Eine Verteilung über Twitter @swkWien kann ich dann übernehmen, noch leichter mit Textvorlage.

**Comment by codecop** [comment]
Sobald die Registrierung auf Eventbrite da ist, werde ich auf Global Seite und allen Kanälen bewerben, inklusive SWK und Twitter.

**Comment by caichinger** [comment]
Die Issue Beschreibung beinhaltet jetzt auch einen allgemeinen Text für Aussendungen die ihr gerne verwenden könnt.

**Comment by dertseha** [comment]
Tweet sent out: https://twitter.com/swkWien/status/1450336799004499969

**Comment by rolger** [comment]
Nagarro hostet den GDCR heuer in mehreren Ländern weltweit. Unser Marketing hat deswegen heute eine Mail an alle Mitarbeiter verschickt. Am Freitag wird es dann Social Media Postings geben. Ich verteile dann den Link bzw. den Banner auf Twitter und LinkedIn

**Comment by rolger** [comment]
Wir halten dzt. bei 15 Anmeldungen, da seid ihr und ich miteingerechnet. Ich habe gestern beim Kunden Reklame gemacht. Einer von ihnen unterrichtet auf der FHTW SW Architektur, er wird seine Studenten explizit auffordern

**Comment by codecop** [comment]
Bisschen Twitter wäre nicht schlecht. @dertseha machst Du nochmal ein Tweet bitte?

**Comment by caichinger** [comment]
Glaube ihr seid eh alle am Ball aber falls ihr überlegt, Montag Früh und noch einmal Donnerstag Früh wären gut für Aussendungen.

**Comment by rolger** [comment]
Ich habe es heute auf LinkIn, Twitter und Facebook ausgesendet. Auf LinkedIn und Facebook gab es auch Nachrichten von Nagarro.

**Comment by rolger** [comment]
Es ist interessant, ich habe gestern im Büro festgestellt, dass sich die Jungen bei uns nicht trauen. Sie glauben, dass der GDCR nur für Experten geeignet ist. Zwei habe ich auf jeden Fall überzeugt. Wir sind jetzt bei 19 Anmeldungen

**Comment by ReaSu** [comment]
Ich hab gestern den Text vom Technikum zur Durchsicht erhalten. Darin wird auch betont, dass es nicht nur für Profis ist. Ich hoff, es melden sich noch mehr!
50 Leute ist das Maximum, oder?

**Comment by dertseha** [comment]
Ich habe innerhalb FRQ Werbung gemacht und plane am Montag nochmal auf Twitter mit swkWien was zu verschicken.

**Comment by caichinger** [comment]
> Es ist interessant, ich habe gestern im Büro festgestellt, dass sich die Jungen bei uns nicht trauen. Sie glauben, dass der GDCR nur für Experten geeignet ist. Zwei habe ich auf jeden Fall überzeugt. Wir sind jetzt bei 19 Anmeldungen

Super! Es gibt dann bestimmt auch Leute die nicht kommen, weil sie meinen der CR ist was für Beginner. ;)


> Ich hab gestern den Text vom Technikum zur Durchsicht erhalten. Darin wird auch betont, dass es nicht nur für Profis ist. Ich hoff, es melden sich noch mehr! 50 Leute ist das Maximum, oder?

Das klingt gut. Ja, 50 Personen ist Maximum (den Räumen entsprechend, es gibt keine Überbuchung).

**Comment by dertseha** [comment]
Zweite Nachricht auf Twitter ist raus: https://twitter.com/swkWien/status/1457651716762001408

**Comment by caichinger** [comment]
Falls sich im Rahmen euer Aktivitäten die Frage stellt, wir verlangen **2G+PCR**, d.h. geimpft/genesen UND ein PCR Test. Das ist eine Änderung zum bisherigen Modus. Die bisher Angemeldeten sind informiert.
