### ISSUE TITLE
GDCR21: Program, Facilitators

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#66]
# Issue zur Diskussion

Aktueller Stand siehe Verlauf.

---

Diskussion: https://docs.google.com/document/d/1ya50ifaiG8a2b6_J-oypsIHfTrMrDF20lu4ekC_TPZI/

Zeitplan: https://docs.google.com/spreadsheets/d/12qqm25-_Dz9DeiSJGxCyufPgDYerd2N8iCEoeZhlXrU/

Cf last year #57

**Comment by haraldreingruber** [comment]
Hey @caichinger, wär gerne dabei und fände eine mob Session als letzte Runde toll...
Bin aber leider dieses Wochenende nicht in Wien.

@gregorriegler hat denke ich sehr viel mob-programming experience, vermutlich sogar mehr als ich durch unsere meetups... Vielleicht hat er Interesse?

**Comment by caichinger** [comment]
> Hey @caichinger, wär gerne dabei und fände eine mob Session als letzte Runde toll... Bin aber leider dieses Wochenende nicht in Wien.
> 
> @gregorriegler hat denke ich sehr viel mob-programming experience, vermutlich sogar mehr als ich durch unsere meetups... Vielleicht hat er Interesse?

@haraldreingruber danke für deine schnelle Rückmeldung. @gregorriegler wird nicht am Retreat teilnehmen und fällt damit als Moderator aus.

**Comment by rolger** [comment]
Ich kann einen Mob oder ein Orchester am Ende auch abhalten 😊

**Comment by caichinger** [comment]
Auf Basis der bisherigen Rückmeldungen machen wir den **Call am Freitag 16:00-17:00** via Gather.

@ReaSu magst/kannst du dazu kommen?

Gedanken gerne schon in https://docs.google.com/document/d/1ya50ifaiG8a2b6_J-oypsIHfTrMrDF20lu4ekC_TPZI/edit#heading=h.a9hoaj9nwd2h ablegen.

**Comment by caichinger** [comment]
Habe einen provisorischen Zeitplan angelegt damit wir morgen eine Diskussionsgrundlage haben:
https://docs.google.com/spreadsheets/d/12qqm25-_Dz9DeiSJGxCyufPgDYerd2N8iCEoeZhlXrU/edit?usp=sharing

**Comment by rolger** [comment]
Ich bezweifle ob sich bei mir morgen 16 Uhr ausgeht. Ich halte einen Workshop beim Kunden und müsste ich ins Büro fliegen

**Comment by maosmurf** [comment]
> Hier ein kleines Update für diejenigen die mitlesen.
> 
>     * Sessions:
>       
>       1. Claus: Pen & Paper (inkl. Rotation nach10-15 Minuten; ankommen und kennenlernen)
>       2. Peter: TDD Ping Pong ("versucht kleine Schritte zu machen") - Pair Programming
>       3. Paul: TDD Baby Steps (evtl. mit Timer)
>       4. Rea: Minimalist Coder (small units)
>       5. Adam: TCR

Können wir das im Programm-Sheet so eintragen?

**Comment by caichinger** [comment]
> Können wir das im Programm-Sheet so eintragen?

Wenn du damit die Tabelle meinst: Jep, habe gerade aktualisiert.

Falls nicht: was ist das "Programm-Sheet"?

---

Änderungen im [Zeitplan](https://docs.google.com/spreadsheets/d/12qqm25-_Dz9DeiSJGxCyufPgDYerd2N8iCEoeZhlXrU/edit?usp=sharing):
* Ich habe deine @maosmurf Session um 10 Minuten verlängert, weil TCR erfahrungsgemäß etwas Zeit für's Setup braucht.
* Die Pen and Paper Session ist jetzt mit in Summe 35 Minuten drinnen, damit wir sich ein Wechsel ausgeht. Evtl. braucht das 5 Minuten länger.

---

Gerne Rückmeldungen zum Zeitplan.

**Comment by caichinger** [comment]
@maosmurf wenn du für deine Session Unterstüzung brauchst, bspw. wegen Tooling Optionen oder vor Ort eine zweite Person die Betreuung übernimmt, damit alle das Setup hinbekommen, gibt Bescheid.

**Comment by rolger** [comment]
Ich habe meinen Namen bestätigt. Außerdem bekomme ich in der Früh Unterstützung von unserer GF

**Comment by caichinger** [comment]
Habe euch zu einem Repo eingeladen. Sobald ihr mir zugesagt habt, mache ich euch Admins.

Wenn die Slides fertig sind, schiebe ich rüber auf https://github.com/swkWien/GDCR2021 damit wir eine schöne URL haben.

**Comment by caichinger** [comment]
> Habe euch zu einem Repo eingeladen. Sobald ihr mir zugesagt habt, mache ich euch Admins.
> 
> Wenn die Slides fertig sind, schiebe ich rüber auf https://github.com/swkWien/GDCR2021 damit wir eine schöne URL haben.

Hatte jetzt noch kurz Zeit gleich das richtige Repo einzurichten, d.h. wir machen den Umstieg sofort. Soweit ich gesehen habe gab es im anderen eh noch keine Commits.

Änderungen bitte direkt in https://github.com/swkWien/GDCR2021 einfügen. Ihr habt alle Admin-Rechte.

**Comment by caichinger** [comment]
Ich schließe hier. Finale Abstimmung heute im Call oder via #74.
