### ISSUE TITLE
GDCR21: Tickets & Registration via Eventbrite

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#67]
Erstellen via https://www.eventbrite.com.

Dort auch noch einmal alle Infos hinterlegen. Textforlage: https://www.softwerkskammer.org/activities/gdcr20-vienna.
Bitte nicht nach Anrede fragen.

Inbesondere:

Ticket:
- Preis: 5€
- Anzahl der Tickets auf 50 (?) beschränken.
- TBD: Pro Person kann nur ein Ticket gekauft werden?

Umfrage:
- I am aware that I need a 2G proof to participate in the event. Yes
- What programming languages do you use? Free form
- Have you participated in a coding dojo or code retreat before? Yes/No

**Comment by rolger** [comment]
Ja das ist okay. Ich probiere gerade einen 1. Anlauf auf EventBrite

**Comment by dertseha** [comment]
> Wenn ich ein Paid Ticket anlegen, dann muss ich auch eine Gebühr zahlen. Ich habe nicht rausgefunden, wie das mit dem Refund funktioniert. Kennt sich da jemand aus?

Ich hatte das so gemacht:
* Gebühr zahlt Veranstaltung - also in dem Fall Du; Wenn Ticket 15 EUR kostet, bekommst Du zB 14,5 EUR (Hausnummer) überwiesen
* Wer dann vor Ort kam hatte bei mir unterschreiben müssen (könnte sich aktuell auch wegen Tracing gut anbieten) und dann hatte ich das betroffene Ticket zurückerstattet. Das ist eine etwas mühsame Klickerei, jedoch machbar. Person erhält 15 EUR zurück, und die fehlenden 50c zahlst somit Du drauf. Bei einer Ausfallrate von mindestens einer Person ist das jedoch locker drinnen.
* Zur Sicherheit hab ein paar Beträge bar dabei. Ich bilde mir ein, bei einer speziellen, seltene Bezahlart geht (ging) keine Rückerstattung.

Auf die Art wirkt es dann im System, als hattest Du nur 1-2 Leute die zum Event kamen (jene, die promt nicht erschienen waren ;) ) - ist jedoch egal, Du willst ja keine Buchhaltung/Ergebnisanalyse von den ca 10 Leuten in Summe über dieses System fahren.

Und ja, auch von mir ein Danke schon mal, dass Ihr das alles in die Hand nehmt :)

**Comment by rolger** [comment]
Was hält ihr von diesem Antwortschreiben:

Thank you for registering for the Global Day of Code Retreat. Upon your arrival, the organizer will take your registration and check the 2G proof. After that, your registration fee of 10€ will be refunded. If you do not attend, we will keep the fee.

**Comment by caichinger** [comment]
@rolger und ich werden die Anmeldeseite heute Nachmittag finalisieren, dann wir das Issue geschlossen

Wer noch rückmeldne möchte, bitte in diesem [Dokument Änderungen Vorschlagen](https://docs.google.com/document/d/1ya50ifaiG8a2b6_J-oypsIHfTrMrDF20lu4ekC_TPZI/edit#heading=h.acg5emqvf53t).

**Comment by caichinger** [comment]
Abgeschlossen, bei dringenden Änderungswünschen bitte direkt Roland kontaktieren.
