### ISSUE TITLE
GDCR21: Require PCR Test in Addition to 2G?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#68]
Ich überlege ob wir zusätzlich zu 2G einen gültigen PCR Test verlangen sollen.
Nachdem die meisten Personen aus Wien kommen, ist das mit "Alles gurgelt" kein Problem.
Umland weiß ich nicht.

Was meint ihr @rolger @codecop?

---

Links:
- https://event.univie.ac.at/services/covid-19-regeln-zur-durchfuehrung-von-veranstaltungen/ (übersichtliche Übersicht)
- https://www.sozialministerium.at/Informationen-zum-Coronavirus/Coronavirus---Aktuelle-Ma%C3%9Fnahmen.html (offizieller Stand) (Da wir maximal 50 Personen sind, brauchen wir keine:n COVID-19-Beauftragte:n)

**Comment by rolger** [comment]
Ich sehe die Möglichkeit sich zu testen als optional. Ich habe mich auch diese Woche getestet obwohl ich geimpft bin. 2G ist finde ansonsten ausreichend

**Comment by gregorriegler** [comment]
Ich möchte auf jeden Fall empfehlen spätestens nach dem Event, auch ohne Symptome, einen PCR Test zu machen. Man hört von Halloween parties, bei denen alle geimpft waren und trotzdem eine symptomlose Person fast alle anderen angesteckt hat. So könnt ihr das Risiko Angehörige anzustecken, minimieren.

**Comment by caichinger** [comment]
Test danach bestimmt sinnvoll.

Ihr kennt auch meine Meinung zu Test davor.

Wenn danach eine Person positiv testet, sind wir alle K1 und das hieße Quarantäne und Freitesten ab dem fünften Tag.

Melde mich später nochmal dazu.

[ORF: Coronavirus - Was bei einem positiven Test zu tun ist](https://orf.at/corona/stories/3209309/)

**Comment by maosmurf** [comment]
Ich plädiere für eine Regel wie in der Nachtgastro: 2G (voll geimpft ODER genesen) UND aktueller PCR-Test (dh auch die geimpften müssen am Vortag gegurgelt haben).
Begründung: Wir sitzen zu 25+ Personen einen ganzen Tag in einem gemeinsamen Raum ohne Maske, während der Hochzit einer Pandemie.

**Comment by maosmurf** [comment]
Also, should we register GDCR with Gesundheitsdienst (MA 15) ?

@caichinger @rolger 

https://coronavirus.wien.gv.at/hilfe-bei-anmeldung-von-veranstaltungen/
https://stp.wien.gv.at/online-assistent/frontend/de/237/Wiener-Veranstaltungs-Checker-ab-01102021

**Comment by ReaSu** [comment]
Ich finde, die aktuellen Zahlen rechtfertigen auf jeden Fall einen vorherigen Test. Test danach ist auch eine gute Idee.

**Comment by caichinger** [comment]
> Also, should we register GDCR with Gesundheitsdienst (MA 15) ?
> 
> @caichinger @rolger
> 
> https://coronavirus.wien.gv.at/hilfe-bei-anmeldung-von-veranstaltungen/ https://stp.wien.gv.at/online-assistent/frontend/de/237/Wiener-Veranstaltungs-Checker-ab-01102021
> 
> Online "Veranstaltungschecker" is not updated yet. I suggest to email [veranstaltung@ma15.wien.gv.at](mailto:veranstaltung@ma15.wien.gv.at)

Danke für den Hinweis. Meinem Verständnis nach müssen wir die Veranstaltung auf Grund der geringen Anzahl Teilnehmender nicht anmelden.

https://coronavirus.wien.gv.at/oeffentliches-leben/#VeranstaltungenundFreizeit_q3

Bzw. im Veranstaltungscheck https://stp.wien.gv.at/online-assistent/frontend/de/237/Wiener-Veranstaltungs-Checker-ab-01102021

`Start / sonstige Zusammenkünfte, die nicht im privaten Wohnbereich stattfinden / höchstens 100 Personen`

**Comment by caichinger** [comment]
Wie gestern mit Roland besprochen, machen wir **2G+PCR**, also geimpft/genesen UND PCR-Test.

Die bisher Angemeldeten sind informiert.

Die Anmeldeseite ist aktualisiert.

Ich schließe das Issue.
