### ISSUE TITLE
GDCR21: Check In and On Site Preparation?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#69]
Fragen:
- Wie gestalten wir den Check in vor Ort?
- Braucht es Hilfe bei der Vorbereitung vor Ort?

# Check In

Der Check In umfasst:
- Prüfung 2G Nachweis
- Prüfung Ticket und Refundierung
- Ausgabe der Zutrittskarte
- Ausgabe Merchandise, Name Tags
- DSGVO konforme Erfassung der Kontaktdaten für Contact Tracing
- *Bitte ergänzen*

Für mich klingt es so, als würde es Sinn machen, wenn mehr als eine Person, nämlich @rolger, den Check In (Trennung in Corona und Event) mitbertreut damit wir möglichst pünktlich anfangen können. 

Wenn wenige Leute kommen spielt das sicher keine Rolle, wenn kurz vor 9 Uhr 10 Leute kommen sehr wohl.

# Vorbereitung vor Ort

Ich habe verstanden, dass wir uns um nichts kümmern müssen. Bitte hier noch einmal um kurze Bestätigung.
Wir werden vermutlich ein paar Zettel aufhängen aber das schaffen wir sicher auch ad hoc.

Vorbereitung vor Ort umfasst:
- Check In Desk
- Anordnung der Tische
- Zettel mit WIFI Code
- Zettel/Poster für Kata
- Code of Conduct
- Corona Regelung
- Falls Fotos gemacht werden, Aufkleber für diejenigen, die nicht drauf sein wollen
- Optional: Zettel mit Twitter Hashtags?

Links:
- https://event.univie.ac.at/services/covid-19-regeln-zur-durchfuehrung-von-veranstaltungen/

---

Was meint ihr @rolger @codecop?

**Comment by caichinger** [comment]
Habe Check In noch um "DSGVO-konforme Erfassung der Kontaktdaten für Contact Tracing" ergänzt.

**Comment by rolger** [comment]
Was braucht ihr bzgl. "Zettel/Poster für Kata" und "Code of Conduct"?
Reicht ein Flipchart oder sollen wir Zettel ausdrucken?

**Comment by codecop** [comment]
[Kata - Snake (Print).pdf](https://github.com/swkWien/sessions/files/7518802/Kata.-.Snake.Print.pdf)
Das habe ich von der Kata
