### ISSUE TITLE
GDCR21: Dinner

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#70]
Abendessen
- Lokal: Meidlinger Schutzhaus
- Adresse: Schutzhausweg 136, 1120 Wien
- Telefon: +43 (0)1 813 5108
- Reservierung auf: Claus Aichinger

---

Bei den bisherigen GDCR gab es im Anschluss noch ein Abendessen. Ich fand das schön und würde das wieder so machen.

Das heißt wir brauchen:
- [x] Lokal (das auch vegetarische Kost führt)
- [x] Möglichkeit die Anzahl der Personen zu erfragen, die mitmachen wollen.
   - Option 1: Via Umfrage bei Ticketkauf
   - Option 2: Via Umfrage bei letzter Aussendung
   - Option 3: Via Umfrage vor Ort (bissl gar Last Minute, da sollten wir davor schon eine Teilreservierung haben)
- [x] Reservierung
- [ ] Aktualisierung der Reservierung am Tag des Events --> via #75 

---

Was meint ihr: @ReaSu @dertseha

Kannst du @rolger darum kümmern? Können auch wieder einen kurzen gemeinsamen Termin machen.
Ich würde jetzt mal die Umfrage ergänzen und ein Lokal kontaktieren, kann mir vorstellen, dass du die Gegend kennst - aber nur Spekulation. :)

Alle die mitlesen und Lokalvorschläge haben, nur her damit.

Lokalvorschläge:
- https://www.schutzhaus-meidling.wien/
- http://deewan-shani.at/ (Meidlinger Deewan)

**Comment by ReaSu** [comment]
Die Lokale in der direkten Umgebung (Zobels, Lafafi, Gasthaus Krapf) sind alle am Samstag geschlossen. 

Lokale etwas weiter weg (andere Seite des Bahnhofs) und samstags geoeffnet (ich kenn keines davon):

- Zipfereck https://zipfereck.hpage.com/
- Weinhaus Pfandler Zu den seligen Affen http://weinhaus-pfandler.at/
- Tozi Korean Kitchen https://www.tozikoreankitchen.at/
- Eat Bio (indisch, keine Website) https://www.tripadvisor.com/Restaurant_Review-g190454-d7311968-Reviews-Eat_Bio_at-Vienna.html

Ich kenn aber Lokale noch ein Stueck weiter weg, und wuerd in jedes davon wieder gehen: 

- Meidlinger Deewan (pakistanisch, limitierte Auswahl)  https://www.meidlingerdeewan.at/
- Zsam Zsam (multikulti, arabisch/syrisch) https://www.facebook.com/zsamzsamvienna/
- Pizzeria Motelli (keine Website) https://www.motellipizzeria-wien.at

Das sind dann aber schon 1,5 bis 2km zu gehen.

**Comment by rolger** [comment]
Ich hätte das Schutzhaus vorgeschlagen
https://www.schutzhaus-meidling.wien/

Das sehr nahe, hat am Samstag offen, hat einen großen Saal und wurde innen neu renoviert.

**Comment by rolger** [comment]
Allerdings wird es im Schutzhaus vermutlich schwierig sein veganes Essen zu bestellen

**Comment by ReaSu** [comment]
Von den vegetarischen Speisen koennten die Spaghetti (ohne Grana) und der Veggie Burger evtl. vegan sein - da muesste man nachfragen.

**Comment by caichinger** [comment]
Melde mich später nochmal, hier derweil zur Info:

Vegan haben sie (wie von euch schon angemerkt) an sich nicht, würden sie probieren/machen. Bspw. das vegetarische Burgerlaberl ohne Ei und das dann mit Salat oder so.

Am Telefon sehr freundlich und lösungsorientiert aber unsicher, ob vegan was mit Mehl zu tun hat. :)

**Comment by caichinger** [comment]
Hat länger gedauert, pardon.

Ich würde Rolands Vorschlag folgen und das Schutzhaus nehmen, weil nah (damit unkompliziert) und offenbar nett.

Im Rahmen der Reservierung geben wir ihnen Bescheid, dass es wahrscheinlich auch Bestellungen zu veganen Speisen geben wird und sie sich dazu bitte was überlegen.

Zu Mittag nehmen wir den Deewan (cf. #71).


Was sagt ihr dazu?

**Comment by ReaSu** [comment]
Find ich gut.

**Comment by caichinger** [comment]
Passt. Habe gerade für 12 Personen reserviert. Issue Beschreibung mit den wesentlichen Infos aktualisiert.

Am Samstag erfragen wir noch einmal zu Beginn des CR wer tatsächlich mitkommen möchte und wir informieren das Schutzhaus.

**Comment by caichinger** [comment]
Reservierungsbestätigung erfragt, sie wissen auf wegen vegan Bescheid (und, dass wir uns am Samstag nochmal melden).

**Comment by caichinger** [comment]
Folgende vegane Gerichte werden sie anbieten:

* Gemüselaibchen auf Tomatenragout mit Couscous
* Pilzragout mit Petersilkartoffel
* Gegrilltes Gemüse auf Blattsalat mit knusprigen Kartoffel-Würfel

Bitte die Info ggfs am Tisch teilen. :)

**Comment by caichinger** [comment]
Ich schließe hier. Der Anruf ist in #75 dokumentiert.
