### ISSUE TITLE
GDCR21: Catering

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#71]
Du hast es glaube ich eh am Radar aber nachdem mich ein Teilnehmer kontaktiert hat:

Bitte beim Essen vor Ort nach Möglichkeit auch darauf achten, dass es vegane Optionen gibt.

Wir hatten bei den Python Konferenzen 1/3 mit Fleisch, 1/3 vegetarisch und 1/3 vegan - sind damit gut gefahren.

Issue gerne wieder schließen wenn für dich erledigt.

Danke!

(Wenn man's genau wissen will, kann das das auch in die Umfrage packen, mMn nicht notwendig).

**Comment by rolger** [comment]
Was würde euch da serviert auf der python Konferenz?

**Comment by caichinger** [comment]
> Was würde euch da serviert auf der python Konferenz?

Kann man nicht ganz vergleichen, weil mehr wenige hundert Personen und ein nicht-kommerzielles Community Event. Wir hatten nur kalte Speise.

---

Habe gestern mit dem Deewan telefoniert, die machen Catering und sind recht flexibel. Das wären Pakistanische Speisen (Curries). 12€ pro Person, vegan/vegetarisch/mit Fleisch. Wenn was über bleibt, packen wir das einfach ein, ist am nächsten Tag auch noch gut.

Was sagst du dazu?

**Comment by rolger** [comment]
Ich habe das okay für Deewan bekommen :-)

**Comment by caichinger** [comment]
> Ich habe das okay für Deewan bekommen :-)

Sehr fein. Dann leite ich das heute/morgen in die Wege, damit sie schon Bescheid wissen und den Termin einplanen können.

Rest dann direkt per Mail.

**Comment by caichinger** [comment]
Habe Angebotsblatt mit Speisenübersicht bekommen. Reservierung ist informell ergangen.

Hier was zur Auswahl steht (meine Vorschläge markiert):
- Gemüse Curries (alle vegan):
  -  :+1:  Gelbe Linsen (Dhaal)
  - Braune Linsen (Dhaal Masoor)
  - Melanzani-Kartoffel (Alu Bangan)
  - Okraschoten (Ladyfingers)
  -  :+1:  Schwarze Augenbohnen (Black Eyed Peas)
  - Kichererbsen Mix (Dhaal Chana)
  -  :+1:  Kürbis (Pumkin Masala)
  - Kichererbsen (Cholay)
  - Brokkoli (Broccoli Masala)
  -  :+1:  Kartoffel Mix
  - Gemüse Mix (Alu Mix)
  - Gemischte Linsen (Dhaal Mix)
- Fleischcurry
  -  :+1: Huhn 
  -  :+1: Lamm
  - Rind

Optional:
-  :+1:  Gemischter Salat
-  :+1:  Nanbrot
- Süßspeise
- Teller, Besteck, Servietten

Alles Details im [L+M Catering Angebot Muster.pdf](https://github.com/swkWien/sessions/files/7506540/L%2BM.Catering.Angebot.Muster.pdf).

---

Wir treffen jetzt eine grundsätzliche Auswahl und können uns dann noch eher kurzfristig bei ihnen zur Finalisierung melden.

Für Mittagspause um 12:30, kommen sie um 12:00 und bauen alles auf.

---

@rolger, gibt es:
- [ ] Steckdosen?
- [ ] Können wir Geschirr von Nagarro verwenden? Dann würden wir weniger Müll machen.
- [ ] Zur Sicherheit: Getränke kommen von Nagarro?

Bitte hierzu um Rückmeldung. Morgen schicke ich die Anfrage raus, dann bekommst du ein Angebot und der Rest geht dann über dich.

---

Alle die schon hungrig sind und sich zum Essen äußern wollen, bitte darum.

**Comment by ReaSu** [comment]
Ich mag alle von den Curries, speziell aber Kartoffel-Melanzani (Alu Bangan). Und das Brot von denen ist auch ur super.

**Comment by rolger** [comment]
Ad Steckdosen: 
Zum Wärmen vom Essen oder? 

Ad Getränke: 
Tee, Kaffee, Wasser und Mineralwasser ist vorhanden. Was wollen wir zusätzlich an Getränken anbieten?

**Comment by caichinger** [comment]
> Ich mag alle von den Curries, speziell aber Kartoffel-Melanzani (Alu Bangan). Und das Brot von denen ist auch ur super.

Geht klar, habe Kartofel-Mix gegen Kartoffel-Melanzani getauscht :D

**Comment by caichinger** [comment]
> Ad Steckdosen: Zum Wärmen vom Essen oder?

Ja. Kabel bringen sie mit. Er hat gemeint bei so wenig Personen muss man wahrscheinlich nicht warm halten aber zur Sicherheit vielleicht ganz gut.


> Ad Getränke: Tee, Kaffee, Wasser und Mineralwasser ist vorhanden. Was wollen wir zusätzlich an Getränken anbieten?

Für mich passt das. Bin da aber auch eher ein Purist. 
Ich will nur nichts Alkohol.
Von der Optik schauen ein paar Säfte oä sicher nett aus aber wenn das nicht geplant ist, kein Problem.

**Comment by rolger** [comment]
Ich bin was Trinken betrifft auch einfach gestrickt. Ich werde ein paar Säfte organisieren.

**Comment by caichinger** [comment]
Gerade telefoniert, Bestellung passt aber sie hatten noch keine Zeit zu antworten. Er wird in circa einer Stunde ein aktualisiertes Angebot an uns schicken. Bitte gib dann du, @rolger, dein Okay oder ggfs. Änderung.

Falls was sein sollte, ich bin am Nachmittag nicht so gut erreichbar aber werde probieren.

**Comment by rolger** [comment]
> 
> 
> Gerade telefoniert, Bestellung passt aber sie hatten noch keine Zeit zu antworten. Er wird in circa einer Stunde ein aktualisiertes Angebot an uns schicken. Bitte gib dann du, @rolger, dein Okay oder ggfs. Änderung.
> 
> Falls was sein sollte, ich bin am Nachmittag nicht so gut erreichbar aber werde probieren.

Alles gut, ich kümmere mich darum

**Comment by rolger** [comment]
Catering ist bestellt :-)
