### ISSUE TITLE
GDCR21: Slides

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#74]
Hier Ideen mit Bitte um Rückmeldung.

Überlegungen zu Slides:
- Gemeinsamer Look and Feel
- Praktisch, wenn die Teilnehmenden auch während der Sessions darauf zugreifen können

Idee zur Umsetzung (nebst anderen):
- GitHub Pages für Publishing (wäre dann im swkWien Namespace)
- GitHub Actions für Building (würde eine Markdown-basierte Lösung nehmen)

Konkreter:
- Slides per *name your favorite solution* (bspw. https://marp.app/)
- Slides per [hugo-reveal](https://github.com/dzello/reveal-hugo/)

@maosmurf @paulroho @ReaSu @codecop 

Was sagt ihr dazu, wärt ihr dabei?

Wenn wir das so machen, mag/kann sich jemand von euch Zeit nehmen das mit mir vorzubereiten?

Folien selber gehen dann erfahrungsgemäß schnell - Markdown eben.

Wenn euch das zu aufwändig/restriktiv ist, nehmen wir GSlide und ich mache uns eine Vorlage.

**Comment by ReaSu** [comment]
Bin gern dabei, hab aber keine Erfahrung mit hugo-reveal oder marp.

**Comment by caichinger** [comment]
@ReaSu (danke) und ich haben heute die zwei oben genannten Varianten ausprobiert. Wenn eurerseits also kein expliziter Einwand mehr kommt, machen wir Markdown Slides.

Stelle morgen noch mehr Infos zu Verfügung, das geht sich jetzt bei mir nicht aus.

**Comment by codecop** [comment]
Wenn ich es am Freitag Mittag weis, kann ich einen PR oder Change machen mit meiner 1 Slide. Ich unterstütze alles.

**Comment by caichinger** [comment]
Slides per hugo-reveal in https://github.com/swkWien/GDCR2021.

Danke Rea für das gemeinsame Aufsetzen.

**Comment by codecop** [comment]
Habe meine Slide erstellt. Sehe ich irgendwo das Endresultat im Web?

**Comment by caichinger** [comment]
> Habe meine Slide erstellt. Sehe ich irgendwo das Endresultat im Web?

https://swkwien.github.io/GDCR2021/

**Comment by caichinger** [comment]
Update nach dem Call vorhin:

* Wir machen zu Beginn eine kurze, kleine Vorstellungsrunde in der alle Facilitators ein paar Sätze zu sich sagen. Bitte bedenken.
* Retro + Pause in Summe 15 Minuten

**Comment by caichinger** [comment]
@maosmurf in den Slides fehlt für uns wie man TCR technisch umsetzt. Vielleicht machst du das eh noch aber da bräuchten wir bitte Links oder Anleitungen. Die Präsentation ist eh online, d.h. die Teilnehmenden haben einfachen Zugriff auf die Links.

Ggfs. haben wir auch morgen noch Zeit das herzurichten aber je früher um so besser. :)

**Comment by caichinger** [comment]
Nicht wundern, meine Slides mache ich später noch fertig.
