### ISSUE TITLE
GDCD21: Finale Abstimmung und Review

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#76]
@rolger @ReaSu @codecop @maosmurf @paulroho ich schlage hiermit noch einen letzten Abstimmungstermin vor.

Meinerseits gehen
* Donnerstag ab 16:00
* Freitag ab 17:30

Wer mag, nimmt teil und gibt Bescheid wann ihr könnt.

Meinerseits zu besprechen
- [ ] Zeitablauf
- [ ] Check In
- [ ] Allgemeine TODOs vor Ort
- [ ] Slides (wenn nicht vorher schon erfolgt)
- [ ] Allfälliges
- [ ] Bitte ergänzen

Bitte um eure Rückmeldung.

@rolger kannst du dabei sein?

**Comment by maosmurf** [comment]
Do ab 16h gerne, Freitag nach Möglichkeit bis 17h oder ab 19h

**Comment by ReaSu** [comment]
Für mich passen Do und Fr Nachmittag/Abend

**Comment by rolger** [comment]
Donnerstag ab 16h und Freitag ab 17:30h kann ich nicht, bis 17h schon

**Comment by caichinger** [comment]
Ich kann Donnerstag leider doch erst ab 18:00, sorry.

Nachdem wir auch nicht wissen, wie es bei den anderen aussieht, schlage ich zwei Termine vor:
- Donnerstag, 18:00
- Freitag, 19:00 (optional falls nach Donnerstag noch Bedar ist)

Wieder in https://gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo (deliberate).

Bis dann!

**Comment by rolger** [comment]
Donnerstag ab 16h und Freitag ab 17:30h kann ich nicht, bis 17h schon

**Comment by paulroho** [comment]
Kann mobil leider nicht in gather einsteigen...

**Comment by caichinger** [comment]
Kleines Zwischenupdate bzgl. der Dinge die Roland betreffen:
- Roland braucht von unserer Seite nichts mehr, d.h. auch keine Unterstützung beim Check In o.ä.
- Er kann uns ggfs. während der Sessions unterstützen
- Er wird versuchen morgen ab 8 Uhr (ct;) vor Ort zu sein

Zu den Anmeldungen:
- Inkl. Facilitators sind wir bei circa 25 Personen
- Wir haben sowohl Personen mit als auch ohne Coding Dojo/Code Retreat Erfahrung (gut gemischt)
- Zumindest für uns gestern waren auch einige uns unbekannte Personen dabei

**Comment by codecop** [comment]
Schaut alles gut aus von meiner Seite
