### ISSUE TITLE
GDCR21: Follow Up Mail to Participants

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#77]
Ein Mail mit folgenden Infos:
* Schön, dass du da warst - danke für den besonderen Tag.
* Feedback: https://forms.gle/pJfDZfMzhneREHt7A
* To join future events, register at https://www.softwerkskammer.org/
* Slides: https://swkwien.github.io/GDCR2021/
* Irgendwas von Nagarro?
* Signatur mit Host und Namen der Facilitators (cf slides)

**Comment by caichinger** [comment]
@rolger kannst du das machen?

Kann ggfs auch den Text vorschreiben.

**Comment by codecop** [comment]
Vielleicht auf den Artikel verweisen: http://blog.code-cop.org/2016/11/followup-global-day-of-coderetreat-2016.html
speziell "A box of things to take from the Coderetreat" - oder den Text einkopieren. Früher hatte ich das als Karte zum Abschied jedem in die Hand gegeben

**Comment by caichinger** [comment]
Können das auch gerne ergänzen. Die Infos sollten mMn jedenfalls drinnen sein. Und mir ist wichtig, dass wir bald ausschicken,

**Comment by rolger** [comment]
Ich schreibe heute etwas zusammen, bin gerade dabei. Danke für deinen Link @codecop und den Vorschlag @caichinger

**Comment by caichinger** [comment]
> Ich schreibe heute etwas zusammen, bin gerade dabei. Danke für deinen Link @codecop und den Vorschlag @caichinger

Gerade gesehen, super, danke dir!

**Comment by rolger** [comment]
@maosmurf kannst du mir bitte deine EMail Adresse schicken

**Comment by maosmurf** [comment]
> @maosmurf kannst du mir bitte deine EMail Adresse schicken

Für public gerne adam.gdcr21@maosmurf.com

**Comment by rolger** [comment]
Bekommst ein Email in bcc
