### ISSUE TITLE
GDCR21: Final Internal Retro

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#78]
* Wie ist es uns gegangen?
* Was lief gut?
* Was würden wir anders machen?
* Lessons learned?
* ...

[Notizen/Protokoll](https://docs.google.com/document/d/1ya50ifaiG8a2b6_J-oypsIHfTrMrDF20lu4ekC_TPZI/edit#heading=h.3qk0kjwbfyhr)

---

Update für diejenigen die noch mitgelesen haben, also Gregor und Christian.

**Comment by caichinger** [comment]
@maosmurf @ReaSu @paulroho @rolger (@goerge @codecop) Zeit für eine interne Retro an einem der folgenden Termine

* Donnerstag, 18.11. ab 18:00
* Freitag, 19.11. ab 18:00
* Dienstag, 23.11. ab 17:00

?

**Comment by paulroho** [comment]
18.11. geht nicht
19./23.11. passen

**Comment by maosmurf** [comment]
Do 18./Fr 19. ok
Di 23. leider nein

**Comment by ReaSu** [comment]
18.11. geht für mich auch nicht, 19. oder 23. passt.

**Comment by goerge** [comment]
18.11. ☑️
19.11. ☑️
23.11. vielleicht

**Comment by caichinger** [comment]
@codecop @rolger der Übersichtlichkeit wegen bitte die Tabelle in meinem Kommentar ausfüllen, danke.

Im Moment scheint Donnerstag okay zu sein.

**Comment by caichinger** [comment]
Ich meinte Freitag, pardon.

**Comment by codecop** [comment]
Macht's nur ohne mich. Ich lese mit

**Comment by caichinger** [comment]
Termin an dem wir alle Zeit haben ist schwierig.

**Machen wir die Facilitator-Retro morgen, Freitag, um 18:00 im https://gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo (deliberate).**

Wir werden dokumentieren und reden wir, Roland/*, uns noch zusammen.

**Comment by rolger** [comment]
Ich habe mir die Notizen durchgelesen. Eine kleine Änderung war, dass wir 5 statt 3 Teilnehmer nach Hause geschickt haben (2 sind gar nicht mehr ins Büro gekommen und haben draußen gewartet).

**Comment by rolger** [comment]
@caichinger - wie war der Rücklauf von den Feedback Bögen?

**Comment by caichinger** [comment]
Wenn sich noch jemand austauschen mag, gerne melden.

Die Notizen zum Nachlesen sind im verlinkten Google Doc.

Ich bedanke mich bei allen die mitgemacht haben und freue mich, dass es uns gelungen ist diese Veranstaltung auf die Beine zu stellen. Insbesondere Danke an @rolger für's Hosting!
