### ISSUE TITLE
Flexible way to find the most suitable weekday for sessions

### ISSUE THREAD

**Issue by redseacomputing** [swkWien/sessions#79]
Some of the volunteers don't get time off from their bosses on Fridays to be able to participate in our sessions 2022 -> #72 
Is there an easy way to make it doable for everyone? Do you have a suggestion?
@caichinger @dertseha

**Comment by dertseha** [comment]
Thank you for picking this up.

I believe it is not possible to find a day that is suitable for _everyone_. Already from the base question "workday vs. weekend" you have two separate groups.
And perhaps this is also the compromise: Don't find "a single" day to use for the CRs, but alternate. And this can be perfectly driven by the host/facilitator what fits best for them, and the people will follow where possible.

Besides, while it would be OK for me to shift a little from my work-time from my bosses view, for me it's the workload that is currently not allowing such side-adventures - so it's not always the bosses fault :) .

**Comment by gregorriegler** [comment]
In my Opinion Friday is already the best choice.
Saturday is Weekend, any many of us have families they want to spend their time with.
On many workplaces, fridays tend to be more relaxed.

There are several ways I managed to free my time for these Events so far.
- Took the day off as Vacation.
- Asked my boss to allow me to join it and accept it as training time.
- Adapted my week to get those workhours done at a different time or day.

In my opinion it's a matter of priority. The question is how important these events are to you.
If you have lots of work and no more energy left, that's a valid choice but up to you.
If there are more important things for you right now, that's a valid choice but up to you.
I assume there are rare cases, where some of us might have other important meetings (work or private) overlapping with our events, and I am happy to adapt to that if arranged in time (months before).

**Comment by redseacomputing** [comment]
Is anyone stopping us from introducing an optional Saturday if necessary? 
I think that would be the most flexible way, but as a consequence would it possibly lead to some empty registrations at the events?

**Comment by caichinger** [comment]
Bin hier bei @dertseha.

Abgesehen vom schon Gesagten ist der Freitag in meinen Augen (ein Problem für all jene, die das Format noch nicht kennen (und damit nicht priorisieren können (war eine Rückmeldung beim GDCR)) - oder nicht in der Position sind, ausreichend frei zu verfügen.

Gleichzeitig weiß ich, dass der Freitag für einige gut klappt und das ist sehr schön und wichtig so.

Spricht irgendwas dagegen einen Doodle an die Liste zu schicken?

**Comment by codecop** [comment]
Wir könnten jedes 2. an einem Samstag machen, also Fr - Sa - Fr - Sa wechseln.

**Comment by ReaSu** [comment]
Ich stimme an sich @dertseha auch zu. Seh auch @gregorriegler s Punkt. Das Gleiche kann man natürlich auch zum Wochenende sagen - alles eine Frage der Priorität. :·)

Vielleicht schieben wir mal einen Samstag ein, und schauen, ob dann tatsächlich andere/mehr Leute kommen?

@redseacomputing , kennst du konkrete Leute, oder war das nur so eine Überlegung?

**Comment by caichinger** [comment]
Ich habe eine kleine Umfrage (https://forms.gle/iruEvmUHQQWStXaFA) ausgeschickt. Werde am Wochenende die Rückmeldungen posten.

Wenn Bedarf nach beiden Tagen ist, können wir alternieren.

**Comment by redseacomputing** [comment]
@ReaSu Es war jemand dabei der das auch bereits eine Weile macht. So kam der generelle Gedanke.

**Comment by ReaSu** [comment]
Danke @caichinger fürs machen statt reden :·)

**Comment by redseacomputing** [comment]
@caichinger 
Postest du das Ergebnis hier in dieses Issue oder kann es mittlerweile geschlossen werden?

**Comment by caichinger** [comment]
Hier das Ergebnis der Umfrage. Wir haben insgesamt **12 Rückmeldungen** bekommen, davon haben
* 5 ausschließlich Freitag (3 davon mit Kommentar, dass Termine am Samstag als Kompromiss denkbar sind),
* 5 ausschließlich Samstag und
* 3 beide Tage angeben.

Nachdem das Szenario "abwechselnd Freitag und Samstag" hier schon diskutiert wurde, schlage ich vor wir probieren das und schauen, was passiert. Wird der Samstag-Termin nicht angenommen, wechseln wir wieder ganz-/mehrheitlich zurück auf Freitag.

Ich hoffe das ist für alle Beteiligten so okay.

Habe die Termine in #72 entsprechend angepasst.

Ich schließe das Issue, wenn hier noch jemand etwas ergänzen möchte, bitte gerne wieder aufmachen.

Danke allen für das Engangement!
