### ISSUE TITLE
Additional notes to coderetreat on Jan 21.1.2022

### ISSUE THREAD

**Issue by rolger** [swkWien/sessions#80]
#72 

You asked me about the complexity metrics plugin, which I'm using in IntelliJ. This is the link: https://plugins.jetbrains.com/plugin/12159-codemetrics

I added a short notice also to the google docs.

**Comment by rolger** [comment]
I'm thinking about how to continue the kata from the coderetreat. We have refactored it, and the resut was a hexagonal architecture. Still the business logic (= domain) is part of the application. I'd like to extract the domain and applying a DDD design (aggregates, entities, value objects, or what ever is useful). 

Who is interested to join or in the results?

**Comment by rolger** [comment]
After our CQRS discussion I'm now able to formulate my intention and ideas better then during the last dojo. 

- There is a difference between CQRS and CQS (https://www.martinfowler.com/bliki/CommandQuerySeparation.html) 
- I was not aware that Commands do not return a value
- I'm looking for patterns for the split-phase refactoring. One pattern is to splitt into a query and the calculation (like in the liftpass kata). I mixed it up with CQS because a calculation is not a Command.

**Comment by paulroho** [comment]
@rolger I would definitely be interested in joining in here!

**Comment by gregorriegler** [comment]
@rolger count me in!!!

**Comment by goerge** [comment]
@rolger I’m very interested in the discussion of the Hexagonal Architecture refactorings and how to separate the domain logic from the app. Maybe I can contribute some insights from a recent project where we aimed for that.

**Comment by caichinger** [comment]
Same here! Where do I sign up for this? ;)

**Comment by dertseha** [comment]
This sounds more and more something like a meetup-presentation rather than a Dojo-Kata - curious :)

**Comment by redseacomputing** [comment]
@rolger 
Enjoyed the topic on that exercise again afterwards and am curious about the domain part here, too.
