### ISSUE TITLE
Is it possible to move the CR on Saturday, 12.3.2022, to another date?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#81]
I would very much like to join again but I am not available neither on Friday, 11.3. nor on Saturday 12.3.

Is it possible to move the retreat to another day, e.g. Saturday, 19.3.?

**Comment by caichinger** [comment]
And: Whom would you usually to ask such a question? swkWien/organiser?

**Comment by codecop** [comment]
Yes, please get in touch with @redseacomputing as he is doing the events/invites etc. and update all referances/dates.

**Comment by redseacomputing** [comment]
Hello @caichinger ,
the next coderetreat will be planned for 19.3.22 on website of SWK.

**Comment by redseacomputing** [comment]
I am sorry. If this would be okay for everyone, of course.

**Comment by caichinger** [comment]
@gregorriegler @ReaSu @rolger @goerge @maosmurf @dertseha pinging a few of the regular participants (not already included here):

Is it okay for your if we move the date of our next CR to Saturday, 19.3.?

Maybe some of you have already planned to attend on the 12th and cannot join on the 19th...

**Comment by dertseha** [comment]
As it stands now, the 19th would be a possibility for me, yes.
