### ISSUE TITLE
AnyDesk User Experience

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#82]
https://anydesk.com/ user experience from last CR.

- Claus
  - Platform: Ubuntu 21.10
  - Experience:
    - AnyDesk installer failed to install all dependencies.
    - X2Go worked like a charm, not a single issue.
  - Conclusion:
    - Very useful, thank you!
    - If Kata/setup were known beforehand, we could save even more time.
    - Consider pushing code in a repo to save it for later.

**Comment by caichinger** [comment]
@gregorriegler hier meine Erfahrung mit AnyDesk. Hat mit X2Go wunderbar geklappt. Habe eine Issue gemacht, falls du das Thema weiter verfolgen möchtest. Ansonsten einfach schließen.

**Comment by gregorriegler** [comment]
Danke. Das ist der source code: https://github.com/gregorriegler/remdev-azure
Ich habe ein paar issues, wie etwa alt+f7 und ctrl+shift+left/right schon gefixt. Und ich weiß schon wie man den timer über allen anderen Fenstern fixieren kann.
Ich weiß leider noch nicht wie ich das Problem mit den anydesk Connection losses beheben kann.

**Comment by caichinger** [comment]
Super Sache, danke.

Weiß nicht ob der AnyDesk Client bei Problemen vielleicht in ein Log schreibt und die anderen daher etwas dazu sagen können.

**Comment by maosmurf** [comment]
Das AnyDesk setup hat bei mir grs. sehr gut funktioniert.
MacOS + AnyDesk App
Die meiste zeit hatte ich das Problem, nur einen Ausschnitt des Screens zu sehen (das Problem hatte auch @dertseha afaik) - ganz zum Schluss hatte ich alles gesehen.
Shortcuts haben teiweise funktioniert, manche wohl anders zu meinen aus MacOS bekannten (zB CTRL+T vs. CMD+T / Fetch / Refactor)
Shift und FN-tasten wurden erkannt.
Danke!

**Comment by gregorriegler** [comment]
> Shortcuts haben teiweise funktioniert, manche wohl anders zu meinen aus MacOS bekannten (zB CTRL+T vs. CMD+T / Fetch / Refactor)
Shift und FN-tasten wurden erkannt.

Good to know

**Comment by codecop** [comment]
Gibt's hier noch Updates? Sonst close ...

**Comment by caichinger** [comment]
Denke man kann schließen und im Zweifelsfall mit einem konkreten TODO wieder aufmachen.
