### ISSUE TITLE
Hosting Coderetreat Friday 20.5.

### ISSUE THREAD

**Issue by redseacomputing** [swkWien/sessions#83]
Frage an die Runde:
Möchte jemand den nächsten Code Retreat on site hosten? Natürlich unter vorgegebenen COVID Bestimmungen.
Da der nächste Termin laut #72 am **20.5.2022** statt finden soll, frage ich nach bevor wir ihn als "remote" publizieren.

Was haltet Ihr davon?
@dertseha @codecop @caichinger @gregorriegler 
@maosmurf @ReaSu @goerge @paulroho @rolger

**Comment by dertseha** [comment]
Danke für die Nachfrage.
FRQ ist sehr konservativ bezüglich Bestimmungen - oft konservativer als es Stadt Wien ist. Also so schnell erwarte ich da nicht, was hosten zu können :/

**Comment by caichinger** [comment]
Wer kann sich denn ein physisches Treffen zum genannten Termin vorstellen (:laughing:) und wer wäre nicht dabei (:confused:), bitte kurze Emoji-Reaktion-Rückmeldung?


Ich könnte womöglich einen Raum organisieren und zwar [hier](https://goo.gl/maps/7tgHkkL3wkJfkLeg8) (Nähe U6 Dresdner Straße  bzw. S-Bahn Traisengasse).

Ich fände es auch schön wieder einmal zusammen zu kommen, gleichzeitig ist mir aber wichtiger, dass sich alle wohl fühlen und wir eine Gruppe zusammen bekommen.

**Comment by maosmurf** [comment]
Ab Mai neuer Job, daher vorerst kein Freitags-CR. Mittelfristig dafür eine gute Location (Samstags)

**Comment by redseacomputing** [comment]
@ReaSu 
Sachsenpl. 4-6, 1200 Wien

**Comment by redseacomputing** [comment]
Wäre es für @gregorriegler unpassend da on-site, oder wegen dem 20.5. als Termin?

@caichinger , was sagst du zu den Rückmeldungen?

Wir würden den Termin gerne in den nächsten Tagen auf der SWK-Seite publizieren.

**Comment by gregorriegler** [comment]
20.5. als remote CR halt ich mir gerne frei.
On-site kann ich nicht versprechen.

**Comment by caichinger** [comment]
@redseacomputing 

Basierend auf den Rückmeldungen schlage ich vor, dass wir wieder remote machen.

Dann wäre Gregor dabei und für dich pass remote glaube ich auch (?).
Die anderen können aus Termingründen nicht oder haben sich nicht geäußert.

Danke für's Kümmern.

**Comment by redseacomputing** [comment]
@gregorriegler @caichinger 
Bin da ganz bei Euch!
