### ISSUE TITLE
GDCR22: Dump for Topics (and Ideas and Considerations)

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#85]
There will be a GDCR and in case an idea comes to your mind, feel free to add it here.

Personally, I like to find an overall theme for the day. Hence the suggestions. However, that's only my personal approach and we can of course do something different.

**Comment by caichinger** [comment]
**Mission Impossible!?**

Sessions with progressively more difficult constraints.

---

From a facilitation point of view the challenge lies in communicating the purpose of the constraints, i.e. "constraints for the constraints-sake (or the challenge itself - can also be rewarding of course)" or "constraints for the purpose of learning something about ...".

**Comment by caichinger** [comment]
**Shifting Paradigms** / **Paradigm Shift**

Sessions with alternating OO and FP constraints.

---

For me contrasting different approaches is oftentimes interesting. Maybe this could be a topic that also allows for fruitful discussions.

**Comment by ReaSu** [comment]
There's also this here: https://www.linkedin.com/feed/update/urn:li:activity:6954124398240968704/ - they are planning on having a continuous session for 48 hours.
I think it's an interesting idea and it might be fun to join them for a session or two and pair with complete strangers. BUT I wouldn't want to see that replace our own GDCR.

**Comment by ReaSu** [comment]
> Sessions with alternating OO and FP constraints.

I like this idea a lot!

**Comment by caichinger** [comment]
> There's also this here: https://www.linkedin.com/feed/update/urn:li:activity:6954124398240968704/ - they are planning on having a continuous session for 48 hours. I think it's an interesting idea and it might be fun to join them for a session or two and pair with complete strangers. BUT I wouldn't want to see that replace our own GDCR.

Let's call it the "48 hours constraint" :D (Just joking)

That's indeed interesting.
Maybe we could/should include a reference to this (or similar?) events in the announcement of our code retreat. It would nicely the emphasize "global day" idea and would be a way to warm up to the occasion.

**Comment by gregorriegler** [comment]
I like Bobs Idea with the globally spanning event, and I want to help him make it happen.
We're currently searching for facilitators in the Australia / NZ / Japan Timezones, in case you know any.

I also believe it should not replace our own GDCR, which I suppose aims to be an offline Event again.
If say, you'd like to have our Event on a Friday this time, it would not overlap with Bobs event and there would be room for integration. But I think this is secondary.

**Comment by gregorriegler** [comment]
So, GDCR 2022 is coming closer.
Do we, and when do we plan to have our Event?
I am asking because GDCCR will take place between 2022-11-04T15:00+02 and 2022-11-06T14:00+02 (Vienna Time), and we're searching for facilitators.

**Comment by codecop** [comment]
I am available Friday and Saturday to facilitate some sessions, but I do not want to run a whole event on my own. Should we try an onsite event again? Who would sponsor the room? I guess small room is enough

**Comment by caichinger** [comment]
My personal view.

**Local (Vienna)**
* Yes, let's organize a single day on-site event.
* I can offer to again help with organization/facilitation.
* Based on last year's experience, having different facilitators was nice and I would just repeat that.
* @rolger mentioned that Nagarro could host us again. Roland, about one year later, what do you think? :)
  If Nagarro can host us again, I guess our event will take place on Saturday and the decision is made.
  I created this issue #87 to call out to others as well.
* It would be interesting to relate to the global event.
  * I am not sure how (apart from communication)
  * I would prioritize the local community (building)

**Global (world)**
* I very much like the idea!
* @gregorriegler "we're searching for facilitators", can you elaborate on that or maybe share a few details (I read Rea's link but it is rather general)? If you believe there may be something I can do, let me know.

---

This issue is now a very broad mix of topics. I think that's okay for now but let's consider outsourcing some threads into other issues when we feel the time is right.

**Comment by ReaSu** [comment]
I agree with Claus that building the local community should be our priority. At the same time I like the idea of being part of something bigger.

I'm free on any two out of Fri-Sun, and happy to help with organising/facilitating at the local level.
At the global level I'd rather take part as a participant.

**Comment by gregorriegler** [comment]
To elaborate on "we're searching for facilitators":
If somebody is interrested in facilitating a 4 hour block remotely on this global event somewhere within the given timerange, let me know. That's all. I don't want to hijack this thread further. Lets continue discussing our local event here.

**Comment by caichinger** [comment]
@rolger responded in #87 and **Nagarro will host GDCR22**. Hence we have a venue, a sponsor and a date **Saturday, 2022-11-05**.

**Comment by codecop** [comment]
Regarding constraints - we could try an overall topic and then focus all sessions on aspects of it. This might be a bit harder for the facilitators, because each of them has to work under the umbrella topic. Possible "umbrella" I have seen in the past are Object Orientation, TDD of course, Refactoring, Connecting with people, and so on. We could even press our luck and try something more special like Hexagon. If we have some options I can set up a poll if and which overall topic it should be.

**Comment by codecop** [comment]
Also choice of kata is possible. It does not have to be Game of Life and it also could be progressive, so building on top of previous code - at least looking like that.

**Comment by paulroho** [comment]
Hexagon as un Hexagonal Architecture?

Would love that!

**Comment by gregorriegler** [comment]
I like the idea of an overall topic.
Another idea I like is to react on what the majority is doing.
So they are not writing tests? Have a Ping Pong session.
They are using mostly primitives? Forbid them.
etc. etc.
Not sure what constraints would fit Hexagonal.
Also: Do they have to know the overall topic?
I assume not if we can push them towards it by setting the proper constraints.

**Comment by codecop** [comment]
Overall topic could be announced during invite. Might get some ppl to come who would not otherwise

**Comment by caichinger** [comment]
We have scheduled a **call after the next code retreat (Friday, 2022-09-16 15:00 in Gather) to discuss the program**. Would be nice to see some of you there to hear your opinions. Ideally, we agree on a rough program so we can start to prepare the sessions and the announcements. Feel free to join even if you do not intend to be on-site or be a facilitator.

My personal preference/opinion:
* Yes to an overall topic (like last year) to shape the day and make it easier to relate to the event. We announce the topic beforehand.
  * Progression is interesting but for me depends on the topic, it is not a primary objective for me. If the topic and the constraints we choose are suitable, then yes.
  * I would first agree on a topic, then discuss possible constraints and in course identify a suitable kata.
  * I am open for experiments. The entire day is about trying something new, so can we. ;)
* Yes to a different kata, i.e. not game of life, if it helps us to tell our story and set our priorities.
* While it is important to adjust to the participants, I prefer to not react topic- or constraint-wise but instead formulate constraints in a way that the participants are able to follow regardless of their experience.

As of now, with regards to overall topic/theme/focus, we have:
* Mission Impossible
  * We work with progression
  * We can take inspiration from @codecop's *brutal* CR with Sportradar
* Shifting Paradigms / Paradigm Shift
  * We work with contrasts
  * An obvious choice would be OO vs FP
* Hexagon
  * We focus on hexagonal architecture

**Comment by caichinger** [comment]
If you want to share an idea with the group, even if it is only a keyword, please go ahead. On Friday we will try to come up with a program or at least specific suggestions to work on and every inspiration is greatly appreciated (at least from my side but I guess I am not alone in that regard).

**Comment by dertseha** [comment]
I have one idea, coming out of a concern: As much fun as it would be for some to have exercises for a hexagonal/universal architecture, consider having a simpler alternative for those that have never worked with it.
Something like two complexity levels. People can still choose for themselves & their pair, and with this you avoid the scenario of a pair suddenly having no idea what to do and the facilitator then spends 5+ minutes with them, explaining with flipcharts and stuff.

I suspect handling two topics in one session would be doable by one facilitator for a session, and perfectly fine also to have two. 

Plus: Thank you all for organizing this!

**Comment by caichinger** [comment]
Today's discussion resulted in
* Overall topic: Software design (starting with pen and paper and a final session on ports and adapters)
* Kata: TBD, maybe snake
* Target audience: mixed, we intend to develop sessions that are suitable for beginners but leave enough room for experienced participants (e.g. through optional constraints)

More details cf referenced commit.
