### ISSUE TITLE
GDCR22: Hosts?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#87]
In case we decide to again organize an on-site event, we need a venue and ideally a sponsor for food. I mention a few of you (rather randomly) to get your opinion.

- [x] @rolger Nagarro
- [ ] @mlem Willhaben
- [ ] @maosmurf Anyline
- [ ] @dertseha Frequentis

---

If you believe other's could as well help organizing a host, please feel free do modify this issue!

**Comment by caichinger** [comment]
Since mentioning did not work as expected, I repost the issue here.

- [ ] @rolger Nagarro
- [ ] @mlem Willhaben
- [ ] @maosmurf Anyline
- [ ] @dertseha Frequentis

**Comment by rolger** [comment]
Nagarro is willing to host the GDCR22 again. I asked already for sponsoring the event again, and they agreed.

**Comment by caichinger** [comment]
> Nagarro is willing to host the GDCR22 again. I asked already for sponsoring the event again, and they agreed.

Awesome! :partying_face: 

Thank you for the quick response. Closing here.

**Comment by codecop** [comment]
@rolger is Nagarro willing for pay travel cost for invited facilitator?
