### ISSUE TITLE
GDCR22: Call for Facilitators

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#88]
GDCR22 takes place on Saturday 2022-11-05 at Nagarro. As briefly discussed in #85 we could jointly facilitate the event. If you want to be involved in the process or facilitate a session, please add your name here or leave a comment.

Contributors:
- ~~Rea~~
- Adam
- Peter
- Roland
- Katrin
- Claus?

Also facilitating in pairs is good and less stressful. So more facilitators would be nice

**Comment by maosmurf** [comment]
I'm happy to assist!

* Rea
* Adam
* ...

**Comment by caichinger** [comment]
FYI siehe #89 für Programm-Call.

**Comment by caichinger** [comment]
If someone still wants to join to facilitate a session, post a comment here.

A rough description of what we intend to do can be found here: https://github.com/swkWien/sessions/blob/master/2022/gdcr/README.md

**Comment by ReaSu** [comment]
Unfortunately I have to revoke my offer to facilitate a session - I won't be in Vienna that day.
I'm still up for doing whatever needs doing to prep the event!

**Comment by caichinger** [comment]
@heidererkatrin are you in?

**Comment by dertseha** [comment]
I know I'm essentially not in any of the organization (I have my head elsewhere these days currently, and I'm very happy and grateful to all of you), I'm happy to be a co-facilitator to assist anyone and give a boost.

**Comment by caichinger** [comment]
> I know I'm essentially not in any of the organization (I have my head elsewhere these days currently, and I'm very happy and grateful to all of you), I'm happy to be a co-facilitator to assist anyone and give a boost.

That's good to know, thank you for your offer. :) Let's see how things evolve - we may come back to you.

**Comment by caichinger** [comment]
> Was ist mit @webpapaya? Wollte auch mitmachen

If you want to join, see our notes in https://github.com/swkWien/sessions/tree/master/2022/gdcr as well as the current discussion in #22 revolving around the program (kata and objectives/constraints for each session).

**Comment by heidererkatrin** [comment]
@caichinger Yes i will help facilitating!

**Comment by caichinger** [comment]
> @caichinger Yes i will help facilitating!

That's good to hear :)
If you have not done so already, please take a look at the current discussion in #22 and share your thoughts. Thank you.

**Comment by caichinger** [comment]
Cross posting here: Also as a facilitator, please buy a ticket to help us keep track of the total number of attendees (cf #91)

https://www.eventbrite.com/e/global-day-of-coderetreat-vienna-2022-tickets-433464663477

**Comment by rolger** [comment]
Partick Scheibert a colleague at Nagarro would also like to support. I asked him if he is already memeber of the Softwerkskammer Wien.

**Comment by codecop** [comment]
Patrick is regular on small Code retreats. Yes I can add him to the SWK organizer group here.

**Comment by codecop** [comment]
@swkWien/organiser I am running a free Coderetreat facilitation training next Monday 17th Oct at 8pm CEST (Vienna time) https://meetup.com/de-DE/coderetreat-training/events/288886095/ as part of global Coderetreat preparation. Please join if you want to learn more about facilitation or the format. Maybe esp interesting for @heidererkatrin @CareForCode @redseacomputing

**Comment by heidererkatrin** [comment]
@codecop Thank you very much for the tip, I will definitely join the session!

**Comment by caichinger** [comment]
@CareForCode If you want to join, see our notes in https://github.com/swkWien/sessions/tree/master/2022/gdcr as well as the current discussion in https://github.com/swkWien/sessions/pull/22 revolving around the program (kata and objectives/constraints for each session).

**Comment by CareForCode** [comment]
> @CareForCode If you want to join, see our notes in https://github.com/swkWien/sessions/tree/master/2022/gdcr as well as the current discussion in #22 revolving around the program (kata and objectives/constraints for each session).

Hey Guys, sorry I just came back yesterday evening from a trip. 
In general I am available to help with the facilitation of the GDCR. 
Currently my schedule is pretty packed, but if you need something from me, I will try to squeeze it in.
I just registered on Eventbrite and will fill out the appointment organization form for the final alignment of the facilitators. 
Additionally I read through the #93 section, although I don't know, what I should find inside your mentioned #22  
For now I only co-facilitated some coding dojos together with Gregor, but did not do a lot of preparatory work besides aligning how the session should be structured. 
As I have not yet done a lot of preparatory work beforehand, I withheld myself with the organization of the GDCR. If you need more from me, please tell me so.

**Comment by ReaSu** [comment]
> Hey Guys
please remember that there are not only guys in this discussion.

**Comment by CareForCode** [comment]
> > Hey Guys
> 
> please remember that there are not only guys in this discussion.

Thanks for pointing it out. I am going to use "Hey folks" next time ;)

**Comment by caichinger** [comment]
Closing this issue.

Follow up via #93.

If we need further assistance, we may reach out to you individually.
