### ISSUE TITLE
GDCR22: Neigungsgruppe Website

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#90]
As discussed in our inital orga meeting (#89 cf baa7add574101ceee63e25b11869bee9db3afe59), we intend to use a website as primary (and single) entry point to our event.

We use this issue to coordinate our activities.

Last year's page(s):
- https://github.com/swkWien/GDCR2021 (the one we used based on hugo)
- https://github.com/swkWien/gdcr21hugo
- https://github.com/swkWien/gdcr21marp

Something we could try is https://quarto.org/, see https://quarto.org/docs/presentations/revealjs/ for a demo. It allows for greatly flexibility when it comes to designing and is till easy to use.

**Comment by caichinger** [comment]
@ReaSu Are you in? :)

**Comment by ReaSu** [comment]
Of course! :·)

**Comment by caichinger** [comment]
I set up a repo to experiment with Quarto
- https://github.com/caichinger/slides-using-quarto/ 
- https://caichinger.github.io/slides-using-quarto/

**Comment by caichinger** [comment]
Stand der Dinge
- https://github.com/swkWien/gdcr22
- https://swkwien.github.io/gdcr22/

Website steht (mit Quarto). Schließe hier. Danke @ReaSu!
