### ISSUE TITLE
GDCR22: Eventbrite

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#91]
Platzhalter Issue, damit wir im Anschluss die Webseite #90 aktualisieren können.

@rolger gib Bescheid, wenn du den Link hast.

Gerne noch Austausch zur Beschreibung des Themas bzw der Tagline.

**Comment by caichinger** [comment]
Ideas for title/tagline:
- Composing systems
- Crossing boundaries
- Designing systems
- Architecture and design
- Cohesion and coupling
- ...

*To be continued; everyone feel free to add your thoughts.*

(Or a combination)

**Comment by codecop** [comment]
Decoupled Design are the main two buzzwords we go for in every session

**Comment by caichinger** [comment]
@rolger wir haben im Anschluss an die Besprechung der Inhalte auch den Zeitplan disktuiert. Der Aktuelle Entwurf ist im [README](https://github.com/swkWien/sessions/blob/master/2022/gdcr/README.md) verlinkt. Bitte schau dir das an und kommentiere ggfs.
Im README möchte ich gerne alle wichtigen Infos zum Event sammeln und alles andere leitet von dort ab, damit alle Perosen die involviert sind, unabhängig von Ausmaß, sich immer schnell einen Überblick verschaffen können. Hoffe das passt für dich. Falls nicht, bitte melden.

**Comment by caichinger** [comment]
@rolger wie geht's der Anmeldeseite?

Unsere die Landing Page ist ab jetzt online: [swkwien.github.io/gdcr22/](https://swkwien.github.io/gdcr22/), dort ist nur mehr der Anmeldelink zu ergänzen.
Danke @ReaSu für die Unterstützung.

Sobald die Eventseite steht, können wir mit den Aussendungen #92 starten.

**Comment by caichinger** [comment]
PS: In einem Monat ist es soweit, ich denke es wäre gut, wenn wir Ende der Woche die Aussendungen machen können.

**Comment by codecop** [comment]
Ja auf der Global Seite melden schon viele Events an

**Comment by rolger** [comment]
Mir ist noch eingefallen, dass voriges Jahr alle überrascht waren über das Frühstück und die Verpflegung. Das sollten wir irgendwo hinzufügen.

**Comment by caichinger** [comment]
Danke.

Hier meine Kommentare bzw Vorschläge

**Zeitplan**

Der Text passt im Moment nicht mit dem Zeitplan https://docs.google.com/spreadsheets/d/1LZTn6zvJuXAMqxj3W5W8Th6H8htvVfU4Z-XXorQW65w/edit?usp=sharing
 zusammen.
Wenn wir ein Frühstück anbieten, würde ich das prominenter ausschreiben.


**Zeitangaben**

Bitte nur an einem Ort. Im Moment bei "When?" und bei "Host".


**What? When? ...**

Nachdem Zeit und Ort in Evenbrite direkt angezeigt werden, könnten wir die Struktur ändern und den zweiten Block vereinfachen zu:

> This year we focus on **decoupled design** and cordially invite everyone interested in software development, beginners and seniors alike, to participate in this year's global day of coderetreat.


**Alternaiv: Wording bei "Who can join?"**

```diff
- **Who can join?** Everyone interested in software development
+ **Who can join?** Everyone interested in software development - beginners and seniors alike
```

**Fragen in der Umfrage**
- Have you participated in a coding dojo or code retreat before?
- Optional: Which programming languages are you familiar with? 
- Do you joint for breakfast?
- Do you join for dinner?
- Bzw: die selben wie letztes Jahr ;)

**Comment by caichinger** [comment]
> Ich habe die Eventbrite Seite angelegt. Ich kann die Seite allerdings nicht teilen, ich muss sie gleich freigeben. Ich werde meinen Text irgendwo hier speichern und dann könnt ihr ihn reviewen

Hast du schon den prospektiven Link? Dann könnte ich den schon auf der Webseite hinterlegen.

**Comment by rolger** [comment]
Danke für die Hinweise. Dann schlage ich vor wir lassen die Liste komplet weg und schreiben nur den Text:

> `This year we focus on decoupled design and cordially invite everyone interested in software development, beginners and seniors alike, to participate in this year's global day of coderetreat.`

und beim Kapitel Host:

Host
The retreat is hosted by Nagarro GmbH (https://www.nagarro.com/).

Arrival time is from 08:15 until 09:00. We'll prepare breakfast and beverages like coffee and tea. The sessions start at 09:00. 

You will receive an email with additional information in the run up to the event.

**Comment by caichinger** [comment]
Bitte den Link zur Website nicht vergessen. Hatte mein Kommentar noch aktualisiert, vielleicht ist das unter gegangen. https://github.com/swkWien/sessions/issues/91#issuecomment-1270207061

**Comment by codecop** [comment]
Refund Policy ist 2x zu sehen

**Comment by rolger** [comment]
> > Ich habe die Eventbrite Seite angelegt. Ich kann die Seite allerdings nicht teilen, ich muss sie gleich freigeben. Ich werde meinen Text irgendwo hier speichern und dann könnt ihr ihn reviewen
> 
> Hast du schon den prospektiven Link? Dann könnte ich den schon auf der Webseite hinterlegen.

https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2022-tickets-433464663477

**Comment by rolger** [comment]
Den Gesamtpreis konnte ich auf 10€ korrigieren (ist eine Option, das ich die Eventbrite Kosten trage).

Das mit dem Refund ist leider komisch. Die 1. Überschrift ist nicht von mir. Ich finde es komisch mit dem Refund anfangen zu müssen. Dann wäre es nur 1 mal im Text.

TODO: Facilitated by SWK Wien werde ich noch hinzufügen

@caichinger wegen zur Link auf die Web-Site, meinst du auf beiden Seiten einen Link hinzufügen?

**Comment by rolger** [comment]
Wenn es keine Änderungswünsche gibt, dann schalte ich den Link einmal frei :-)

**Comment by caichinger** [comment]
Danke für die Updates, hübsch :)

**Ad Freischalten**
Ja bitte! Danke! =)

**Ad Refund Policy**
Wenn es die Seite nicht anders zulässt, dann ist es halt so.

**Ad Event Seite vs SWK Wien Seite**
- https://swkwien.github.io/gdcr22/ ist die Event Seite die uns durch den Tag führen wird
- https://swkwien.github.io/ ist die Seite der SWK Wien

Ich bin dafür beide zu listen.

Vorschlag:

```diff
-The whole day and especially the coding sessions will be facilitated by coaches from the 
-[Softwerkskammer Wien](https://swkwien.github.io/gdcr22/).
+The whole day and especially the coding sessions will be facilitated by coaches from the 
+[Softwerkskammer Wien](https://swkwien.github.io/).
+Bookmark our [event page](https://swkwien.github.io/gdcr22/) and stay tuned!
```

---

**Ad https://swkwien.github.io/gdcr22/**
Ist mit Link auf Eventbrite aktualisiert, d.h. wir haben jetzt *einen Link für alles*.

---

Ich mache die Vorschläge, damit sie konkret sind, weil ich glaube, dass man damit einfacher arbeiten kann, nicht weil ich diese Details vorgeben möchte.

**Comment by caichinger** [comment]
@rolger bitte Issue schließen, wenn du durch bist. Danke.

**Comment by caichinger** [comment]
Letzte Frage noch an dich, @rolger, möchtest du, dass wir (=Facilitator/Orga) uns - zwecks Übersichtlichkeit (für Planung und etwaiger Auflagen) - ebenfalls ein Ticket kaufen?

**Comment by codecop** [comment]
Ja wir sollten uns alle im Eventbrite anmelden. Dann ist klar wer kommt und es gibt nur 1 Liste

**Comment by rolger** [comment]
Ja ich werde mich selbst auch anmelden. Der Event ist ist jetzt öffentlich
