### ISSUE TITLE
GDCR22: Announcements

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#92]
Help us spread the word of this year's global day of coderetreat event in Vienna!

Important facts: https://github.com/swkWien/sessions/blob/master/2022/gdcr/README.md

To simplify matters, below is a short text you can use to invite your friends and colleagues.

Thank you!

## Mail Template

https://github.com/swkWien/sessions/tree/master/2022/gdcr#announcement

## Announcements

- [x] Create SWK event
- ~~ [ ] Create SWK Mail Gruppe Wien ~~ (not possible for technical reasons)
- [x] Create https://www.coderetreat.org/ event
- [x] notify Austria channel in Crafters slack
- [x] SWK Twitter
- @caichinger
  - [x] Python user group
  - [x] Django Vienna
  - [x] Everyone codes
  - [x] Clients
- @ReaSu 
  - [x] FH Technikum Wien 
- @rolger
  - [x] Facebook craftmanship group
- @codecop 
  - [x] Clients

*Please amend and update.*

## Registrations

| date | number |
| ------|------------|
| 20/10/2022 | 17 |
| 25/10/2022 | 20 |
| 02/11/2022 | 27 |

**Comment by caichinger** [comment]
@redseacomputing could you please take care of creating an https://www.softwerkskammer.org/ event for our GDCR coderetreat?

Texts and details are in the linked README, see also the eventbrite page.

This was last year: https://www.softwerkskammer.org/activities/gdcr21-vienna.
We need people to register via eventbrite.

**Comment by redseacomputing** [comment]
@caichinger 
Yes, Done

**Comment by caichinger** [comment]
> @caichinger Yes, Done

Danke für's Kümmern.

Ich habe keine Notification bekommen. Kannst du ein Email ausschicken oder geht da nix mehr?

Mir ist aufgefallen, dass die Beschreibungen
* https://www.softwerkskammer.org/activities/GDCoderetreat20221105
* https://www.eventbrite.at/e/global-day-of-coderetreat-vienna-2022-tickets-433464663477

nicht ganz zusammen passen. Wenn es dir möglich ist, schau dir das bitte noch an, sonst gib mir Bescheid, danke.

**Comment by caichinger** [comment]
@dertseha @maosmurf @mlem @goerge @gregorriegler ihr habt es vielleicht eh schon gemacht aber falls nicht, bitte unsere Eventankündigung (siehe README in Issue Beschreibung) in eurem Arbeitskontext oder wo auch immer es für euch Sinn macht teilen. Danke!

Bitte um Reaktion hier, damit wir sehen, was wir schon gemacht haben.

**Comment by caichinger** [comment]
@ReaSu bitte unsere Ankündigung (siehe README in Issue Beschreibung) in deinem Netzwerk teilen, danke.

**Comment by caichinger** [comment]
Who manages https://twitter.com/swkWien?
Let's make an announcement there as well an pin the tweet.
And retweet facilitator announcements.

**Comment by caichinger** [comment]
@paulroho bitte unsere Ankündigung (siehe README in Issue Beschreibung) in deinem Netzwerk teilen, danke.

**Comment by caichinger** [comment]
@rolger bitte teile bei Gelegenheit den Stand der Anmeldungen mit uns, damit wir sehen, wo wir stehen. Habe in der Issue-Beschreibung einen Platzhalter angelegt. Danke.

**Comment by maosmurf** [comment]
> @dertseha @maosmurf @mlem @goerge @gregorriegler ihr habt es vielleicht eh schon gemacht aber falls nicht, bitte unsere Eventankündigung (siehe README in Issue Beschreibung) in eurem Arbeitskontext oder wo auch immer es für euch Sinn macht teilen. Danke!
> 
> 
> 
> Bitte um Reaktion hier, damit wir sehen, was wir schon gemacht haben.

Yes! Ich habe bereits vor einigen Tagen angekündigt in der Firma und es sind bereits einige angemeldet :)

**Comment by ReaSu** [comment]
Habs gesehen und gelesen, werd erst morgen dazu kommen.

**Comment by rolger** [comment]
Linkedin : https://www.linkedin.com/feed/update/urn:li:activity:6990581009146605568?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6990581009146605568%2C6990582507935043584%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%286990582507935043584%2Curn%3Ali%3Aactivity%3A6990581009146605568%29

**Comment by dertseha** [comment]
> Who manages https://twitter.com/swkWien? Let's make an announcement there as well an pin the tweet. And retweet facilitator announcements.

Mindestens ich hab Zugang.
Welcher Text soll es werden?
Und: Wer möchte Tweet-Authorization für swkWien erhalten? (Ich brauche dafür Twitter Namen)

**Comment by caichinger** [comment]
@redseacomputing ich habe das [SWK Event](https://www.softwerkskammer.org/activities/GDCoderetreat20221105) aktualisiert und im Wesentlichen auf Eventbrite verwiesen, damit keine widersprüchlichen Infos im Raum stehen.

---

Ich wollte zur Sicherheit auch noch eine Einladung senden, das geht leider nicht:

![image](https://user-images.githubusercontent.com/16005912/198956094-e3365407-b852-42a8-adb3-91392cb4272b.png)

(Wie zu erwarten geht auch kein direktes Mail an die Gruppe.)

D.h. uns fehlt möglicherweise Reichweite.

**Comment by caichinger** [comment]
> > Who manages https://twitter.com/swkWien? Let's make an announcement there as well an pin the tweet. And retweet facilitator announcements.
> 
> Mindestens ich hab Zugang. Welcher Text soll es werden? Und: Wer möchte Tweet-Authorization für swkWien erhalten? (Ich brauche dafür Twitter Namen)

Ich bin leider schlecht mit Social Media, hier ein Vorschlag: https://github.com/swkWien/sessions/blob/master/2022/gdcr/README.md?plain=1#L110 

Kannst du, @dertseha, den bitte tweeten und pinnen?

**Comment by codecop** [comment]
Hab Andreas Leidig kontaktiert. Er betreut Swk vielleicht noch...

**Comment by codecop** [comment]
Nein Fehler ist bekannt. Das wird nichts

**Comment by caichinger** [comment]
> Nein Fehler ist bekannt. Das wird nichts

Schade, danke für's Probieren. Cf. #99

**Comment by dertseha** [comment]
> Kannst du, @dertseha, den bitte tweeten und pinnen?

Tweet ist raus und gepinnt:
https://twitter.com/swkWien/status/1587119154792124416
