### ISSUE TITLE
GDCR22: Sessions

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#93]
*Placeholder issue to facilitate program discussion*

There is now a separate [document to outline the sessions](https://github.com/swkWien/sessions/blob/master/2022/gdcr/sessions.md). Feel free to make adjustments to the structure and amendments to the content. We will then translate the description into slides.

Last year, objective/goals/"what is it that participants should do and why" where not entirely clear in all sessions, therefore I suggest we write that down explicitly this time.
Also, contrary to last year where the constraints focused a lot on the development process with quite independent sessions, this year's focus on *decoupled design* requires in my opinion a more coordinated approach to create a cohesive experience.

---

# Kata candidates

A collection of exercises that popped up either repeatedly over time or in the context of this year's focus.

## Automata

* [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)
* [Langton's ant](https://en.wikipedia.org/wiki/Langton%27s_ant)

## Game

* [Snake](https://en.wikipedia.org/wiki/Snake_(video_game_genre))
* https://github.com/ardalis/kata-catalog/blob/main/katas/RPG%20Combat.md

## Systems

*System for lack of better wording*

* [Refactoring-Kata-Lift-Pass-Pricing](https://github.com/martinsson/Refactoring-Kata-Lift-Pass-Pricing)
* [vending-machine-kata](https://github.com/guyroyse/vending-machine-kata)
* [ports-and-adapters](https://github.com/swkBerlin/ports-and-adapters)
* https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata

**Comment by caichinger** [comment]
@ReaSu @codecop @maosmurf @rolger @heidererkatrin I reach out to you so we can continue to prepare the program for the upcoming retreat. Please read the issue description and think about the following:
* Which kata is in your opinion a good choice for **decoupled design**?
* Which session would you like to facilitate?
* How would you [design the sessions we discussed last time](https://github.com/swkWien/sessions/blob/master/2022/gdcr/sessions.md) (this document is only a skeleton based on my notes, it is not final).

Feel free to share your opinion in this issue.
I suggest we have another short online meeting to discuss and finalize the program. I will send out a survey to identify a date soon.

---

Note that Rea will not facilitate a session but she is nevertheless interested in shaping the retreat.
Personally, I am more interested in facilitating the general introduction but I can do a session as well.

**Comment by caichinger** [comment]
My two cents to help foster the discussion.

Auf Deutsch, weil ich schon müde bin.
Sehe das Folgende weniger als konkreten Vorschlag und mehr als Kristallisationskeim, damit mal was da ist.

### Wiederholung
- Unser Fokus ist **Decoupled Design**.
- Unsere Zielgruppe ist divers, wir sind **Beginner Friendly**.

### Grundsätzlich
- **Pro System** Ich bin für ein Kata, bei dem es leicht ist, sich verschiedene Komponenten
in einem Gesamtsystem vorzustellen und einem das Szenario vielleicht sogar vertraut vor kommt, weil man
beispielsweise mit externen Resourcen/Schnittstellen zu tun hat.
- **Pro Starter Code** Ich stelle mir auch vor, dass es praktisch sein könnte, wenn es schon Code gibt.
Irgendwas wird entkoppelt, dieses irgendwas muss wo herkommen. Wenn man auf der grünen Wiese beginnt, kommt man vielleicht gar nicht so weit.
In dem Fall würde sich ein Refactoring Kata anbieten.
Oder wir müssen was zur Verfügung stellen - poteniell aufwändig.

### Katas
In diesem Sinne folgende Gedanken zu den oben gelisteten Katas:
- https://github.com/swkBerlin/ports-and-adapters von der Essenz her passend aber zu klein
- https://github.com/martinsson/Refactoring-Kata-Lift-Pass-Pricing kenne ich nicht, klingt schön und interessant, Setup mit
  echter Datenbank in der Form keine Option; "
- https://github.com/guyroyse/vending-machine-kata
  - Nicht-trivial und hat interessante Aspekte
  - Kata Beschreibung in der Form nicht passend
  - Einfach vorstellbar, dass bspw. Preiskatalog, Lagerbestand über verschiedene Systeme abgewickelt 
    werden (wenn diese Vending Machine größer gedacht wird)
  - Man beginnt bei Null, d.h. potentiell schwieriger, in einer Session bspw. zwei System anzubinden
- https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata
  - Ist ein Refactoring Kata (mit Tests)
  - Die Preise könnten von verschiedenen Systemen kommen
  - Der Kassabon könnten über verschiedene Systeme dargestellt/gedruckt werden

### Fazit
Diese Argumentation für zu https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata mit von uns vorgegebenen Schwerpunkten & Constraints je Session.
Ich bin für viele Ideen offen. Das ist, wie oben beschrieben, nur ein Gedankengang.

---

### Was mir unklar ist
- Wie stellen wir sicher, dass sich die Aufgaben entwickeln, wir also eine Progression Richtung
  "Ports and Adapters" haben die interessant ist?
- Wie variieren wir die Sessions "Dependecy Injection" vs "Dependency Inversion" vs "Ports and Adapters"?
- Wie wahrscheinlich ist es, dass man die Aufgaben gleich via "Ports and Adapters" löst?
- Macht es Sinn, unsere Vorgaben durch Änderungen in den Anforderungen zu motivieren?

**Comment by maosmurf** [comment]
I'm afraid, a "full refactoring Kata" needs too much intro-time for new-joiners.
Therefore I'd suggest at least sessions 1-3 to base on GOL/Snake.

Alternatively, we could also utilize the [RPG-Kata](https://github.com/ardalis/kata-catalog/blob/main/katas/RPG%20Combat.md) - still TDD but with Focus on " Decoupled Design" (assuming this is our overarching topic)

For Sessions 2/3/4 I suggest (optional) constrains, e.g. 
* No if statements / No loops (via [Facilitation Guide](https://www.coderetreat.org/facilitators/facilitation/l))
* Small Methods (<5 lines, 1-line?)
* No language primitives
* No mouse
* ? "Evil TDD"

**Comment by caichinger** [comment]
Appreciating @maosmurf for reacting so quickly! :)

A few remarks/clarifications from my side:
* Unless we agree otherwise "Decoupled Design" **is** our overarching topic
* In our discussion, we agreed to try to fine one Kata for the entire day (to avoid overhead and help build momentum) and I would only change that if we fail to do so
  * I added the RPG-kata to our list
* Using a refactoring Kata as starting code does for me not imply that we do all required refactorings 
* We want to invite beginners but we can expect a mixed audience and I personally expect more experienced participants than beginners. Maybe I am overly optimistic but as long as the pairings work out (and we can influence that), I think we can go quite far

**Comment by codecop** [comment]
Vending machine hat mehr Möglichkeiten für Ports weil mehr teile in system. Wäre ein guter Kandidat. Selbst wenn man nicht an decouple denkt. Ich würde nur 1 Kata nehmen wegen Einarbeitung

**Comment by caichinger** [comment]
Umfrage zur Terminfindung für finale Abstimmung:

**https://pads.c3w.at/form/#/2/form/view/wZqFYTof68apRHNL0p-j-fmQzOMflfyxda6yapjmdrw/**

Bitte bis **Dienstag, 2022-10-18 20:00** ausfüllen, danke.

**Comment by caichinger** [comment]
Ich bin mit der Diskussion hier unglücklich und fände es schön, wenn sich mehr Personen einbringen.

Wir stellen sicher ein Programm auf die Beine, daran habe ich keine Zweifel.

Die Frage ist wie wir dort hin kommen:

* Wir haben entschieden, dass wir Facilitator sein wollen, dann brauchen wir ein Kata und Sessions.
* Wir haben entschieden, dass wir das gemeinsam machen, dann braucht es den Input von allen.
* Wir haben entschieden, dass wir die Sessions aufteilen, dann braucht es die Abstimmung untereinander.
* Wir haben entschieden, dass das Programm auch für Beginner ansprechend sein soll, dann braucht es mehr Vorbereitung.

Es ist voll okay zu sagen "Puh, weiß nicht genau..." oder "Macht mal, ich komme später dazu." - mit der Info können wir dann auch weiter arbeiten.

Wenn nichts kommt ist es für mich schwierig den Prozess zu unterstützen.

**Comment by codecop** [comment]
Du meinst mehr als wie beide. Aber wir können einen Plan mal auf die Beine stellen und sehen wie es ankommt. Schliesslich war ich es der den Hype für Hexagon begonnen hat ;-) Bin leider ab Donnerstag und ganze nächste Woche weg, Wir könnten mittendrin mal telefonieren?

**Comment by heidererkatrin** [comment]
Entschuldige, ich hab mich etwas rausgehalten weil es mein erstes Mal Vorbereitung für ein Code Retreat ist.
Meine 2 cents: Ich wäre auch eher für einen Code zum Refactoren, als ihn komplett selber zu schreiben und auf die Architektur zu achten. 
Ich denke mit den 45 min Sessions wirds sehr knapp, wenn man die Business logic auch noch umsetzen muss und sich vl auch mit dem Konzept von Decouples Architecture mal anfreunden muss. 
Außerdem kann das Aufsetzen von einem Projekt, egal wie lange man schon programmiert, doch immer etwas länger dauern ;)
da wäre es dann natürlich auch von Vorteil, wenn die Pairs zumindest eine ähnliche Programmiersprache können um sich hier zu helfen.
Für mich ist auch noch die Frage, ob es zu all den Themen (Hex. Architecture, Dependency Inj. Inv. etc.) eine kurze Erklärung für die Teilnehmer gibt, oder wird das vorausgesetzt?

**Comment by caichinger** [comment]
> Du meinst mehr als wie beide. Aber wir können einen Plan mal auf die Beine stellen und sehen wie es ankommt. Schliesslich war ich es der den Hype für Hexagon begonnen hat ;-) Bin leider ab Donnerstag und ganze nächste Woche weg, Wir könnten mittendrin mal telefonieren?

Okay, machen wir das. Melde mich an anderer Stelle.

**Comment by caichinger** [comment]
> Entschuldige, ich hab mich etwas rausgehalten weil es mein erstes Mal Vorbereitung für ein Code Retreat ist.

Danke dir, das gibt mir Orientierung.

> Meine 2 cents: Ich wäre auch eher für einen Code zum Refactoren, als ihn komplett selber zu schreiben und auf die Architektur zu achten. 

Okay.

> Ich denke mit den 45 min Sessions wirds sehr knapp, wenn man die Business logic auch noch umsetzen muss und sich vl auch mit dem Konzept von Decouples Architecture mal anfreunden muss. Außerdem kann das Aufsetzen von einem Projekt, egal wie lange man schon programmiert, doch immer etwas länger dauern ;) da wäre es dann natürlich auch von Vorteil, wenn die Pairs zumindest eine ähnliche Programmiersprache können um sich hier zu helfen.

Ein funktionierendes Setup ist "Voraussetzung" aber ich bin bei dir, ist immer ein gewisses Risiko.
Auf der grünen Wiese ergeben sich dafür andere Möglichkeiten.
Ist eine Abwägungsfrage, deswegen ist diese Diskussion wichtig.

Vorerfahrung und Programmiersprache können in's Pairing eingehen. D.h. wir können bspw. darauf achten, dass die Paare in einer Art und Weise zusammen finden, dass sie sich sinnvoll ergänzen.

> Für mich ist auch noch die Frage, ob es zu all den Themen (Hex. Architecture, Dependency Inj. Inv. etc.) eine kurze Erklärung für die Teilnehmer gibt, oder wird das vorausgesetzt?

Ebenso eine Frage die wir klären müssen. Grundbegriffe können wir glaube ich voraus setzen und dann liegt es an uns die Vorgaben entsprechend zu verständlich formulieren.

Wir würden also "Dependency Injection" nicht alleine stehen, sondern von "Dependency Injection, i.e. pass dependencies in constructor/init" sprechen. So circa. "Constructor/init" setzen wir voraus. Was Dependencies sind, haben wir uns zu dem Zeitpunkt schon erarbeitet. <-- Natürlich nur ein Beispiel.

Vgl letztes Jahr https://swkwien.github.io/GDCR2021/ (sofern vergleichbar, Fokus sehr entwicklungsprozesslastig)

**Comment by ReaSu** [comment]
Ich habe mich auch rar gemacht, Entschuldigung.

Für die Terminumfrage braucht man einen Cryptpad account. Haben das alle? Bei der letzten Umfrage war die Abstimmung auch ohne Anmeldung möglich.

Ich kenn nicht alle der vorgeschlagenen Katas, möchte aber eine Stimme für das RPG Combat Kata abgeben. Die schrittweisen Anforderungen machen es Anfänger_innen recht leicht zu beginnen, gleichzeitig ist es komplex genug, dass man sich früh über Design Gedanken machen kann.

**Comment by caichinger** [comment]
> Für die Terminumfrage braucht man einen Cryptpad account. Haben das alle? Bei der letzten Umfrage war die Abstimmung auch ohne Anmeldung möglich.

Mein Fehler, pardon. Geht jetzt.

**Comment by gregorriegler** [comment]
FYI Das Rpg Combat Kata mache ich gerade mit meinen Teams. Es braucht zumindest mehrere Stunden damit man mehrere Iterationen des Kata schafft, damit es zu den entsprechenden "Pointen" - den interessanten Design Herausforderungen kommt. In einer Stunde bleibt es ein seichter Teaser. Hat auch kein IO, daher per se also kein hexagonal möglich, außer man ändert das Kata ab. Abgeändert hat es sicher viel Potential, auch für euren Bedarf.

**Comment by caichinger** [comment]
@gregorriegler danke für deinen Input. Sehe das ähnlich.

Peter und ich haben heute kurz telefoniert. Wir schreiben was zusammen und ich melde mich dann nochmal.

**Comment by rolger** [comment]
Ich bin diese Woche vollkommen verplant und bin ab nächster Woche vor allem tagsüber für Vorbereitungen verfügbar.

Ein Vorschlag zum Thema Hexagonalen Architektur: wir sollten einen Fokus legen - wirklich Ports und Adapter oder nur eine Art "functional core" bzw. Trennung von Domain (business logic) und Application services. Bei Ports und Adapter hat man noch eine 3. Schicht zu berücksichtigen. Bei den anderen beiden sind es nur 2 Schichten. "functional core" bedeutet keine Seiteneffekte in der Domain. Das wäre halt eine zusätzliche Steigerung. Main Vorschlag wäre nur auf die Trennung von Domain (business logic) und Application Services zu achten. 

Für die Kata bedeutet es trotzdem, dass wir eine Art externe Komponente benötigen. Die darf nur in den Application Services über ein IF designed und aufgerufen werden und nicht in der Domain

**Comment by codecop** [comment]
Danke, SoC ist ja auch eine Abstufung. Vielleicht finde ich eine Kette von Anstufungen und dann teilen wir es in die 3 Sessions ein.

**Comment by caichinger** [comment]
**Termin für Abstimmung: Montag, 24.10. im Zeitraum 18:00 bis 20:00**

Es gibt leider keinen wirklich guten Termin, am ehesten:

- Adam, Katrin und ich können da.
- Rea kann nur um 18:00 und Roland nur um 19:00 - kann jemand von euch ein wenig schieben?
- Patrick, du hast keine Angabe gemacht; was heißt das für diesen Termin?
- Peter ist leider die ganze Woche weg, das ist für uns schade.

Ich kann mir vorstellen, dass wir in der Woche vom Retreat einen Termin fänden, an dem alle Zeit haben aber es wird dann womöglich knapp - zumal ich im Moment nicht glaube, dass wir nur über die Diskussion hier zu einem Programm kommen.

Ich schlage daher den oben genannten Termin vor. In dem wird es uns denke ich gelingen das Programm weiter zu konkretisieren und im Bedarfsfall gibt es noch eine finale Abstimmungs- bzw. Reviewrunde (dann gleich mit den Slides).

Bitte um Bestätigung via Reaction bzw. Rückmeldung wegen der genauen Uhrzeit.

**Comment by CareForCode** [comment]
Also bei mir war's noch unsicher...hab mir am Montag jetzt was für 18:30 ausgemacht gehabt, was ich hoffentlich auf 19:30 verschieben kann, dann würde denke ich 18-19 Uhr bei mir (Patrick) gehen

**Comment by heidererkatrin** [comment]
Bei mir passt der Termin nach wie vor!

**Comment by ReaSu** [comment]
Ich kann auch später, wenn nötig, aber längstens bis 19:45.


------- Original Message -------

**Comment by caichinger** [comment]
# Programmvorschlag

Peter und ich haben einen Programmvorschlag gemacht:
https://github.com/swkWien/sessions/blob/master/2022/gdcr/sessions_draft.md

Wir hätten damit:
- Konkretes Thema "Decoupled Design" (aber nicht bis hexagonal, da passt das Kata nicht)
- Konkretes Kata (SupermarketReceipt)
- Konkrete Vorschläge für Sessions (sind noch ein paar Entscheidungen zu treffen)

Bitte schaut euch den Vorschlag zwecks Diskussion am Montag an und überlegt euch, ob ihr mit an Bord seid und die genannten Ideen weiter ausgestalten, konkretisieren und auch moderieren wollt.

Was man am Montag besprechen soll und nicht unbedingt hier im Issue stehen muss, bitte in den Meeting Minutes eintragen:
https://pads.c3w.at/code/#/2/code/edit/0PpvNOymWOugkl1ZfCtgMpsg/
Der Verlauf hier wird mir zu unübersichtlich.

(Es wird Sinn machen, die fertigen Sessions vorab durchzuspielen, wer das machen möchte, bitte Reaktion mit :rocket: )

Schönes Wochenende! :)

**Comment by CareForCode** [comment]
Wann starten wir die morgige Session?

**Comment by caichinger** [comment]
> Wann starten wir die morgige Session?

Ich entscheide hiermit, dass unser Call morgen **um 18:00 startet**.

Weiß nicht, ob das für alle Beteiligten geht, bspw. für @rolger laut Umfrage nicht. D.h. ich bzw. alle anderen die länger Zeit haben, bitte ich ggfs. länger dabei zu sein, damit wir uns in einer möglichst großen Teilmenge abstimmen können.

Wer nicht weiß, wie man in [Gather](https://gather.town/app/kNtWdLSSLSYIoR5R/CodingDojo) kommt, schreibt mir bitte ein Mail an claus.aichinger@gmail.com.

**Comment by rolger** [comment]
Ich kann leider nicht verschieben. Ich habe von 17:30 bis 18:30 einen externen Termin, bin aber ziemlich flott wieder zu Hause. Ich werde mich beeilen, um so schnell wie möglich anzuschließen

**Comment by caichinger** [comment]
Hier das Ergebnis der heutigen Besprechung.

Sessions and Facilitators:
1. Session: "Pen & Paper" by Peter
2. Session: "Facing Reality" by Katrin & Patrick
3. Session: "Untangling the Knot" by Adam
4. Session: "SOLID" by Claus
5. Session: "TBD" by Roland (mit Peter)

Alles Weitere separat bei Bedarf separat.

Danke euch!
