### ISSUE TITLE
GDCR22: TODOs

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#95]
*Collection of TODOs/ideas/considerations (not yet) worthy an issue on their own; feel free to amend; also non-essential*

- [x] Set up feedback form; reuse from last year, eventually use CryptPad --> https://pads.c3w.at/form/#/2/form/view/tM+9tLh82H6yKGbg0kTiCjkU+6zRcJLTXZ-IWbUH99Y/
- [x] QR codes for
  - [x] Feedback form: ![feedback_form_qr_code](https://user-images.githubusercontent.com/16005912/200069932-e000c2c3-c09a-44ce-b978-4464844237f2.svg)
  - [ ] softwerkskammer.org --> skipped, site currently not working and therefore not advocating use
- [ ] Consider feedback/guestbook flipchart at venue? --> skipped, too late
- [x] Facilitator retro --> #99

**Comment by heidererkatrin** [comment]
Question: Do we want people to make branches for their team for pair programming? Because Roland had to give me permissions so I could push my changes to the code, we would have to consider that too...

**Comment by maosmurf** [comment]
Hello!
Local branches: peoples decision.
But I see no need for everyone to push any code (to the swk repo)

**Comment by caichinger** [comment]
I am with @maosmurf. Since we decided that every session starts again anew, there is no need to push to a common repo.
(In the event that participants want to share their code, the will find a way to do that.)
