### ISSUE TITLE
GDCR22: Mandatory PCR Tests?

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#96]
Coronalampel in Wien auf rot: https://corona-ampel.gv.at/

Wollen wir verpflichtende PCR Tests?

**Comment by rolger** [comment]
Ich weiß es ehrlich gesagt nicht. Ich befürchte das gleiche Chaos wie voriges Jahr, wenn es wieder vergessen wird oder die Ergebnisse nicht rechtzeitig geliefert werden

**Comment by codecop** [comment]
Ja vermutlich wird es vorgeschrieben sein. Eine Woche vor Event muss sowieso ein Reminder Email rausgehen, da steht es dann gross dabei. Schreib es schon mal auf die Enventbrite Seite. Wie streng man dann prüft ist eine andere Sache. Aber COVID Konzept ist vermutlich ein Muss.

**Comment by caichinger** [comment]
Wenn wir PCR-Tests fordern und ich denke das macht Sinn:

Ich würde die Tests auch vor Ort kontrollieren, weil die Ankündigung für manche ein Grund sein kann, dass sie dabei sind.

Ich würde zusätzlich drei Tage vor dem Event einen ausschließlichen PCR-Test-Reminder ausschicken.

Denke das ist zumutbar.

---

**PCR-Test-Reminder**

Betreff: Don't forget your PCR-Test

Body: 
Dear participant,

Please don't forget to bring a valid PCR-test to join our retreat on Saturday.

Looking forward to seeing you soon,
Cheers

**Comment by dertseha** [comment]
Aktuell Wien wieder gelb laut Karte.

Vorschlag zum Text: Positiv formulieren "Bring your PCR-test" und "Please bring a valid, negative PCR-test..."
(sowie: einheitliches casing von PCR-test :) )

Verstehe ich auch richtig, Test egal ob geimpft oder nicht?

**Comment by caichinger** [comment]
Danke für das Updaten und den Vorschlag (und den Lacher via "(sowie: einheitliches casing von PCR-test :) )" :).

@rolger hat gemeint er überlegt sich was und wird in seiner Rolle als Host eine Entscheidung treffen.

**Comment by rolger** [comment]
@dertseha  - ja auf jeden Fall einen negativen Test egal ob geimpft oder nicht

**Comment by caichinger** [comment]
Danke @rolger für die Klarstellung:

> Dear participant,
> 
> Please don't forget to bring a valid, negative PCR-test to join our retreat on Saturday. Even though the infection numbers are currently decreasing, we want to proactively take care all of us and possible risk groups.
> 
> Looking forward to seeing you soon,
> Cheers

Ich schließe das Issue.
