### ISSUE TITLE
GDCR22: Facilitation Guide

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#97]
https://github.com/swkWien/sessions/blob/master/2022/gdcr/facilitation_guide.md

**Comment by caichinger** [comment]
@ReaSu was meinst du, fehlt dir was?

**Comment by ReaSu** [comment]
Danke für die Erwähnung von inclusive language!
Mir fällt gerade nichts ein was fehlt, ich meld mich sonst (bzw. ergänze).

**Comment by caichinger** [comment]
Fein, danke dir!
Ja, bitte gerne direkt ergänzen.
Hab versucht eine Auswahl zu treffen mit Themen die mMn wichtig sind und manchmal übersehen werden.
