### ISSUE TITLE
GDCR22: Check setup

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#98]
We provide a less ambiguous version of the original Kata to avoid confusion:

https://github.com/swkWien/SupermarketReceipt-Refactoring-Kata

Please
1. Install requirements
1. Run tests
1. Fix eventual issues

| Language | Person | Check? |
|----------|--------|--------|
| c | Rea |  Check |
| cpp | Rea | Check |
| csharp-ms | Katrin | __ |
| csharp | Katrin | Check |
| go | Christian | Check |
| java | Patrick | Check |
| kotlin | Patrick | Check |
| php | Adam | Works with PHP 8.0 (but not PHP 8.1) |
| python | Claus | Check |
| ruby | Peter | __ |
| swift | Adam | Check |
| typescript | Adam | Check |

**Comment by maosmurf** [comment]
* php  
☺️  works with PHP 8.0, but **not** with PHP 8.1 (for mac users: `sudo port install php80-iconv php80-mbstring` )

* typescript
:smiling_face_with_three_hearts: Works

**Comment by caichinger** [comment]
@ReaSu @heidererkatrin @CareForCode @codecop referencing you here

@dertseha since you are familiar with Go, can you please check if the setup is working? See issue description. We use a branch with tests and this setup requires a few dependencies.

**Comment by heidererkatrin** [comment]
C# mussten wir noch eine Kleinigkeit ändern, damit das neue Approval Testing Framework "Verify" funktioniert, jetzt sollte es aber klappen

**Comment by codecop** [comment]
@heidererkatrin kannst du das Original repo zu dir klonen und den fix wiederholen und dann einen pr an Emily schicken bitte? (Ohne unseren branch Änderungen...)

**Comment by rolger** [comment]
Ich habe mir zur Vorbereitung die Java Implementierung angeschaut. Dabei ist mir aufgefallen, dass der "with_tests" Branch nur eine geringe Code Coverage hat. Der Branch ist so keine gute Basis, um Refactorings durchzuführen. @CareForCode willst du zusätzliche Tests implementieren, sonst kann ich es auch machen. Es ist auf jeden Fall eine gute Vorbereitung. Es gilt das selbe wie für @heidererkatrin Änderungen, wir sollten die an Emiley kommunizieren

**Comment by CareForCode** [comment]
@rolger ich werds mir mal anschauen

**Comment by rolger** [comment]
_> Ich habe mir zur Vorbereitung die Java Implementierung angeschaut. Dabei ist mir aufgefallen, dass der "with_tests" Branch nur eine geringe Code Coverage hat. Der Branch ist so keine gute Basis, um Refactorings durchzuführen. @CareForCode willst du zusätzliche Tests implementieren, sonst kann ich es auch machen. Es ist auf jeden Fall eine gute Vorbereitung. Es gilt das selbe wie für @heidererkatrin Änderungen, wir sollten die an Emiley kommunizieren_

Sorry, alles gut ich habe das package übersehen!

**Comment by dertseha** [comment]
Go ist nichtmehr aktuell für die neueste Go version, braucht ein paar Korrekturen.

Mit "fix issues", wie soll das gemacht werden:
* cloned personally, then PR to here
* modify directly here
* cloned personally, then PR to emily, wait until upstream acceptance, then pull here
* ...
?

**Comment by codecop** [comment]
Fix here. Additionally fix in personal clone and pr to Emily without time pressure

**Comment by dertseha** [comment]
Go funktioniert nun.

**Comment by maosmurf** [comment]
Ruby:
* geschafft mit Ruby 2.7 (via rvm) in IntelliJ auf MacOS
* `rake test` in Konsole wirft `gems/mutant-minitest-0.11.16/lib/mutant/minitest/coverage.rb:23:in `cover': uninitialized constant Mutant::Minitest::Coverage::Set (NameError)` :dizzy_face:
* ruby 3.0 habe ich gar nicht geschafft (Error im Gemfile, and then some)

**Comment by caichinger** [comment]
Danke euch für's Anschauen.

Habe unsere Erkenntnisse im README des Repos festgehalten.

https://github.com/swkWien/SupermarketReceipt-Refactoring-Kata/commit/72ee9d3b10da74a98c5070319e0e70530f60543a
