### ISSUE TITLE
GDCR22: Orga Retro

### ISSUE THREAD

**Issue by caichinger** [swkWien/sessions#99]
- [ ] Zukunft von softwerkskammer.org
- [ ] Unterpunkt zur Homepage: Alternative/Zusatz zu Twitter (kommt aktuell etwas in Verruf, Ausgang unklar)
- [ ] Outreach
- [ ] *Bitte gerne Diskussionspunkte hinzufügen*

**Comment by dertseha** [comment]
Um ein paar Punkte als nicht-organizer anzubringen, nebst dem feedback form:
* Pair Programming sollten wir etwas anders verkaufen als das klassische und fixed "driver / navigator" - Bei Zühlke wurde ich von Steve Freeman informiert, dass das eine veraltete Ansicht ist und eigentlich nicht richtig ist. (Es gibt eigene Artikel und sogar papers dazu, kann ich nachreichen, wenn ich meine Notizen dazu wieder gefunden hab)
* "Law of Demeter" sollten wir auch etwas moderner benennen. Das ist auch in einem Buch (war es im 20th anniversary practical programmer?) angemerkt. Denn nichts und niemand weiß mehr, was eigentlich mit "Demeter" gemeint ist.
* Die DDD Session, so cool sie im Plan ist, viel etwas flach bei meinem Pair, weil der originale Code viel zu weit weg von einer "leichteren" Position zum refactoring war.

soweit meine PUnkte von meinen kurz-notizen.

**Comment by dertseha** [comment]
Ich hab in der Liste den Punkt zu Twitter hinzugefügt.
Zusammenhängend: https://twitter.com/dtanzer/status/1588394589710618632

**Comment by dertseha** [comment]
...und jetzt habe ich auch noch meine Referenzen in der ersten Antwort ausgebessert.
Zum pair-programming paper und keine unterschiedliche Rollen, hier ein Auszug:

> However, these role descriptions have been challenged by the results of recent studies [6, 7, 9] that show that driver and navigator do not think or act on different levels of abstraction. 
> [...]
>  They suggest defining the roles of driver and navigator by “the additional physical and cognitive load of typing borne by the driver” rather than “by segmenting the problem space according to level of abstraction”.

**Comment by codecop** [comment]
Don’t Chain Method Calls ist nicht LoD und es hat keinerlei Auswirkung auf Koppling. Wir benennen ja auch nicht XP in etwas anderes um, weil es keiner mehr kennt, oder?

**Comment by caichinger** [comment]
@heidererkatrin @CareForCode @maosmurf @rolger @ReaSu 

Hier eine Umfrage für alle, die bei der Nachbesprechung dabei sein wollen (Orga oder nicht). Bitte bis Donnerstag Abend ausfüllen.

https://pads.c3w.at/form/#/2/form/view/WUMs4WhRFFkqk1f3icHzjG2hU301Ef6XlZqqWHkI2x0/

Habe nicht all zu viele Termine angegeben, vielleicht schaffen wir es trotzdem.

---

@dertseha danke für deine Kommentare! Schau ich mir noch an.

**Comment by rolger** [comment]
@caichinger, wie ist der Rücklauf von Teilnehmer-Feedback? 

Mir ist eigefallenm wenn wir nicht die über softwerkskammer Mails verschicken, dann kann ich es über eventbrite. Ich habe alle Email Adressen über eventbrite. Wir könnten ein Dankeschön Email, mit Erinnerungsfotos und mit der Aufforderung nach Feedback verschicken. 

Was hält ihr davon?

**Comment by caichinger** [comment]
> @caichinger, wie ist der Rücklauf von Teilnehmer-Feedback?

7 Rückmeldungen.
 
> Mir ist eigefallen, wenn wir nicht die über softwerkskammer Mails verschicken, dann kann ich es über eventbrite. Ich habe alle Email Adressen von eventbrite erhalten. Wir könnten ein Dankeschön Email, mit Erinnerungsfotos und mit der Aufforderung nach Feedback verschicken.
> 
> Was hält ihr davon?

Würde ich machen, bin pro "Mail schicken". Die Veranstaltung ist zwar schon länger her, von meiner Seite gerne trotzdem.

**Comment by codecop** [comment]
Könnte verbunden sein mit der Frage was aus den Retro Plänen für die Zukunft schon passiert ist

**Comment by codecop** [comment]
Was ist denn das Ergebnis der Retro?

**Comment by caichinger** [comment]
Habe die Notizen aus der Retro hochgeladen https://github.com/swkWien/sessions/commit/3f1ecdba0022221673377e9c2a92a3bb1c16ee7c

@rolger würde mich noch freuen, von dir zu hören, falls du hier oder in's Repo schreiben magst. :)

**Comment by caichinger** [comment]
@dertseha danke für deine Kommentare, finde ich interessant.

>     * Pair Programming sollten wir etwas anders verkaufen als das klassische und fixed "driver / navigator" - Bei Zühlke wurde ich von Steve Freeman informiert, dass das eine veraltete Ansicht ist und eigentlich nicht richtig ist. (Edit: Zugehöriges paper: http://oro.open.ac.uk/28909/1/XP2011PlonkaSegalSharpVanderLinden.pdf )

Wenn du einen Vorschlag für die "role description" hast oder wie du derzeit Pair Programming kommunizierst, habe #105 aufgemacht.

 
>     * "Law of Demeter" sollten wir auch etwas moderner benennen. Das ist auch in einem Buch (Im 20th anniversary practical programmer: "We just recommend a somewhat simpler way of expressing almost the same thing: 'Don’t Chain Method Calls' ") angemerkt. Denn nichts und niemand weiß mehr, was eigentlich mit "Demeter" gemeint ist und man muss es immer erklären.

Hätte ich ein gutes Thema für Retro gefunden!

Ich habe mir LoD gemerkt, genau weil es "Law of **Demeter**" heißt. :)


>     * Die DDD Session, so cool sie im Plan ist, viel etwas flach bei meinem Pair, weil der originale Code viel zu weit weg von einer "leichteren" Position zum refactoring war.

Die Frage hat uns auch in der Vorbereitung länger beschäftigt. Wir haben uns für SupermarketReceipt entschieden, weil man gut rein findet und es Möglichkeiten bietet - es ist aber zweifellos limitiert.
Glaube die letzte Session wird bei allen recht unterschiedlich ausgesehen habe.

Wenn du ein Kata kennst, das sich für das Thema deiner mMn gut anbietet, bitte Info.
